<?php

/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

return [
    'AD' => [
        'name' => 'Andorra',
        'fullName' => 'Principality of Andorra',
        'demonyms' => [
            'Andorrans'
        ],
        'keywords' => [
            'andorran'
        ]
    ],
    'AE' => [
        'name' => 'United Arab Emirates',
        'fullName' => 'United Arab Emirates',
        'demonyms' => [
            'Emiratis',
            'Emaratians'
        ],
        'keywords' => [
            'uae',
            'emirati'
        ]
    ],
    'AF' => [
        'name' => 'Afghanistan',
        'fullName' => 'Islamic Emirate of Afghanistan',
        'demonyms' => [
            'Afghans'
        ],
        'keywords' => [
            'afghan'
        ]
    ],
    'AG' => [
        'name' => 'Antigua and Barbuda',
        'fullName' => 'Antigua and Barbuda',
        'demonyms' => [
            'Antiguans',
            'Barbudans'
        ],
        'keywords' => [
            'antiguan',
            'barbudan'
        ]
    ],
    'AI' => [
        'name' => 'Anguilla',
        'fullName' => 'Anguilla',
        'demonyms' => [
            'Anguillans'
        ],
        'keywords' => [
            'anguillan'
        ]
    ],
    'AL' => [
        'name' => 'Albania',
        'fullName' => 'Republic of Albania',
        'demonyms' => [
            'Albanians'
        ],
        'keywords' => [
            'albanian'
        ]
    ],
    'AM' => [
        'name' => 'Armenia',
        'fullName' => 'Republic of Armenia',
        'demonyms' => [
            'Armenians'
        ],
        'keywords' => [
            'armenian'
        ]
    ],
    'AO' => [
        'name' => 'Angola',
        'fullName' => 'Republic of Angola',
        'demonyms' => [
            'Angolans'
        ],
        'keywords' => [
            'angolan'
        ]
    ],
    'AQ' => [
        'name' => 'Antartica',
        'fullName' => 'Antartica',
        'demonyms' => [],
        'keywords' => [
            'antarctics',
            'antarctic'
        ]
    ],
    'AR' => [
        'name' => 'Argentina',
        'fullName' => 'Argentine Republic',
        'demonyms' => [
            'Argentinians'
        ],
        'keywords' => [
            'argentine',
            'argentines'
        ]
    ],
    'AS' => [
        'name' => 'American Samoa',
        'fullName' => 'American Samoa',
        'demonyms' => [
            'Samoans'
        ],
        'keywords' => [
            'samoan'
        ]
    ],
    'AT' => [
        'name' => 'Austria',
        'fullName' => 'Republic of Austria',
        'demonyms' => [
            'Austrians'
        ],
        'keywords' => [
            'austrian'
        ]
    ],
    'AU' => [
        'name' => 'Australia',
        'fullName' => 'Commonwealth of Australia',
        'demonyms' => [
            'Australians'
        ],
        'keywords' => [
            'aussie',
            'australian'
        ]
    ],
    'AW' => [
        'name' => 'Aruba',
        'fullName' => 'Country of Aruba',
        'demonyms' => [
            'Arubans'
        ],
        'keywords' => [
            'abc',
            'islands',
            'aruban'
        ]
    ],
    'AX' => [
        'name' => 'Åland Islands',
        'fullName' => 'Region of Åland',
        'demonyms' => [
            'Åland Islanders'
        ],
        'keywords' => [
            'alandic',
            'alandics'
        ]
    ],
    'AZ' => [
        'name' => 'Azerbaijan',
        'fullName' => 'Republic of Azerbaijan',
        'demonyms' => [
            'Azerbaijanis'
        ],
        'keywords' => [
            'azerbaijani'
        ]
    ],
    'BA' => [
        'name' => 'Bosnia and Herzegovina',
        'fullName' => 'Bosnia and Herzegovina',
        'demonyms' => [
            'Bosnians',
            'Herzegovinians'
        ],
        'keywords' => [
            'bosnian',
            'herzegovinian',
            'bosnianherzegovinian',
            'bosnianherzegovinians'
        ]
    ],
    'BB' => [
        'name' => 'Barbados',
        'fullName' => 'Barbados',
        'demonyms' => [
            'Barbadians'
        ],
        'keywords' => [
            'barbadian'
        ]
    ],
    'BD' => [
        'name' => 'Bangladesh',
        'fullName' => 'People\'s Republic of Bangladesh',
        'demonyms' => [
            'Bangladeshis'
        ],
        'keywords' => [
            'bangladeshi'
        ]
    ],
    'BE' => [
        'name' => 'Belgium',
        'fullName' => 'Kingdom of Belgium',
        'demonyms' => [
            'Belgians'
        ],
        'keywords' => [
            'belgian'
        ]
    ],
    'BF' => [
        'name' => 'Burkina Faso',
        'fullName' => 'Burkina Faso',
        'demonyms' => [
            'Burkinabés'
        ],
        'keywords' => [
            'burkinabe'
        ]
    ],
    'BG' => [
        'name' => 'Bulgaria',
        'fullName' => 'Republic of Bulgaria',
        'demonyms' => [
            'Bulgarians'
        ],
        'keywords' => [
            'bulgarian'
        ]
    ],
    'BH' => [
        'name' => 'Bahrain',
        'fullName' => 'Kingdom of Bahrain',
        'demonyms' => [
            'Bahrainis'
        ],
        'keywords' => [
            'bahraini'
        ]
    ],
    'BI' => [
        'name' => 'Burundi',
        'fullName' => 'Republic of Burundi',
        'demonyms' => [
            'Burundians'
        ],
        'keywords' => [
            'burundian'
        ]
    ],
    'BJ' => [
        'name' => 'Benin',
        'fullName' => 'Republic of Benin',
        'demonyms' => [
            'Beninese'
        ],
        'keywords' => [
            'dahomey'
        ]
    ],
    'BL' => [
        'name' => 'Saint Barthélemy',
        'fullName' => 'Overseas Collectivity of Saint Barthélemy',
        'demonyms' => [
            'Barthélemois',
            'Saint Barthélemy Islanders'
        ],
        'keywords' => [
            'com'
        ]
    ],
    'BM' => [
        'name' => 'Bermuda',
        'fullName' => 'Bermuda',
        'demonyms' => [
            'Bermudians'
        ],
        'keywords' => [
            'bermudian'
        ]
    ],
    'BN' => [
        'name' => 'Brunei',
        'fullName' => 'Brunei Darussalam',
        'demonyms' => [
            'Bruneians'
        ],
        'keywords' => [
            'bruneian'
        ]
    ],
    'BO' => [
        'name' => 'Bolivia',
        'fullName' => 'Plurinational State of Bolivia',
        'demonyms' => [
            'Bolivians'
        ],
        'keywords' => [
            'bolivian'
        ]
    ],
    'BQ' => [
        'name' => 'Bonaire, Sint Eustatius and Saba',
        'fullName' => 'Caribbean Netherlands',
        'demonyms' => [
            'Bonaireans',
            'Saba Islanders',
            'Sabans',
            'Sint Eustatians'
        ],
        'keywords' => [
            'abc',
            'islands',
            'sss',
            'bes',
            'bonairian',
            'bonairians',
            'eustatian',
            'saban'
        ]
    ],
    'BR' => [
        'name' => 'Brazil',
        'fullName' => 'Federative Republic of Brazil',
        'demonyms' => [
            'Brazilians'
        ],
        'keywords' => [
            'brazilian'
        ]
    ],
    'BS' => [
        'name' => 'Bahamas',
        'fullName' => 'Commonwealth of The Bahamas',
        'demonyms' => [
            'Bahamians'
        ],
        'keywords' => [
            'bahamian'
        ]
    ],
    'BT' => [
        'name' => 'Bhutan',
        'fullName' => 'Kingdom of Bhutan',
        'demonyms' => [
            'Bhutanese'
        ],
        'keywords' => [
            'thunder',
            'dragon',
            'kingdom',
            'druk',
            'yul'
        ]
    ],
    'BV' => [
        'name' => 'Bouvet Island',
        'fullName' => 'Bouvet Island',
        'demonyms' => [
            'Bouvet Islanders'
        ],
        'keywords' => []
    ],
    'BW' => [
        'name' => 'Botswana',
        'fullName' => 'Republic of Botswana',
        'demonyms' => [
            'Batswana'
        ],
        'keywords' => [
            'botswanan'
        ]
    ],
    'BY' => [
        'name' => 'Belarus',
        'fullName' => 'Republic of Belarus',
        'demonyms' => [
            'Belarusians'
        ],
        'keywords' => [
            'white',
            'russia',
            'belarusian'
        ]
    ],
    'BZ' => [
        'name' => 'Belize',
        'fullName' => 'Belize',
        'demonyms' => [
            'Belizeans'
        ],
        'keywords' => [
            'british',
            'honduras',
            'belizean'
        ]
    ],
    'CA' => [
        'name' => 'Canada',
        'fullName' => 'Canada',
        'demonyms' => [
            'Canadians'
        ],
        'keywords' => [
            'canadian'
        ]
    ],
    'CC' => [
        'name' => 'Cocos (Keeling) Islands',
        'fullName' => 'Cocos (Keeling) Islands',
        'demonyms' => [
            'Cocosian',
            'Cocos Islanders'
        ],
        'keywords' => []
    ],
    'CD' => [
        'name' => 'Congo (Democratic Republic of the)',
        'fullName' => 'Democratic Republic of the Congo',
        'demonyms' => [
            'Congolese'
        ],
        'keywords' => [
            'kinshasa',
            'rdc',
            'belgian',
            'zaire'
        ]
    ],
    'CF' => [
        'name' => 'Central African Republic',
        'fullName' => 'Central African Republic',
        'demonyms' => [
            'Central Africans'
        ],
        'keywords' => []
    ],
    'CG' => [
        'name' => 'Congo',
        'fullName' => 'Republic of the Congo',
        'demonyms' => [
            'Congolese'
        ],
        'keywords' => [
            'brazzaville',
            'french'
        ]
    ],
    'CH' => [
        'name' => 'Switzerland',
        'fullName' => 'Swiss Confederation',
        'demonyms' => [
            'Swiss'
        ],
        'keywords' => []
    ],
    'CI' => [
        'name' => 'Côte d\'Ivoire',
        'fullName' => 'Republic of Côte d\'Ivoire',
        'demonyms' => [
            'Ivorians'
        ],
        'keywords' => [
            'ivorian'
        ]
    ],
    'CK' => [
        'name' => 'Cook Islands',
        'fullName' => 'Cook Islands',
        'demonyms' => [
            'Cook Islanders'
        ],
        'keywords' => [
            'island'
        ]
    ],
    'CL' => [
        'name' => 'Chile',
        'fullName' => 'Republic of Chile',
        'demonyms' => [
            'Chileans'
        ],
        'keywords' => [
            'chilean'
        ]
    ],
    'CM' => [
        'name' => 'Cameroon',
        'fullName' => 'Republic of Cameroon',
        'demonyms' => [
            'Cameroonians'
        ],
        'keywords' => [
            'cameroonian'
        ]
    ],
    'CN' => [
        'name' => 'China',
        'fullName' => 'People\'s Republic of China',
        'demonyms' => [
            'Chinese'
        ],
        'keywords' => []
    ],
    'CO' => [
        'name' => 'Colombia',
        'fullName' => 'Republic of Colombia',
        'demonyms' => [
            'Colombians'
        ],
        'keywords' => [
            'colombian'
        ]
    ],
    'CR' => [
        'name' => 'Costa Rica',
        'fullName' => 'Republic of Costa Rica',
        'demonyms' => [
            'Costa Ricans'
        ],
        'keywords' => [
            'rican'
        ]
    ],
    'CU' => [
        'name' => 'Cuba',
        'fullName' => 'Republic of Cuba',
        'demonyms' => [
            'Cubans'
        ],
        'keywords' => [
            'cuban'
        ]
    ],
    'CV' => [
        'name' => 'Cabo Verde',
        'fullName' => 'Republic of Cabo Verde',
        'demonyms' => [
            'Cape Verdeans'
        ],
        'keywords' => [
            'verdean'
        ]
    ],
    'CW' => [
        'name' => 'Curaçao',
        'fullName' => 'Country of Curaçao',
        'demonyms' => [
            'Curaçaoans'
        ],
        'keywords' => [
            'abc',
            'islands',
            'curacaoan'
        ]
    ],
    'CX' => [
        'name' => 'Christmas Island',
        'fullName' => 'Christmas Island',
        'demonyms' => [
            'Christmas Islanders'
        ],
        'keywords' => [
            'kiritimati'
        ]
    ],
    'CY' => [
        'name' => 'Cyprus',
        'fullName' => 'Republic of Cyprus',
        'demonyms' => [
            'Cypriots'
        ],
        'keywords' => [
            'cypriot'
        ]
    ],
    'CZ' => [
        'name' => 'Czech Republic',
        'fullName' => 'Czech Republic',
        'demonyms' => [
            'Czechs'
        ],
        'keywords' => []
    ],
    'DE' => [
        'name' => 'Germany',
        'fullName' => 'Federal Republic of Germany',
        'demonyms' => [
            'Germans'
        ],
        'keywords' => [
            'german'
        ]
    ],
    'DJ' => [
        'name' => 'Djibouti',
        'fullName' => 'Republic of Djibouti',
        'demonyms' => [
            'Djiboutians'
        ],
        'keywords' => [
            'djiboutian'
        ]
    ],
    'DK' => [
        'name' => 'Denmark',
        'fullName' => 'Kingdom of Denmark',
        'demonyms' => [
            'Danes'
        ],
        'keywords' => [
            'danish'
        ]
    ],
    'DM' => [
        'name' => 'Dominica',
        'fullName' => 'Commonwealth of Dominica',
        'demonyms' => [
            'Dominicans'
        ],
        'keywords' => [
            'dominican'
        ]
    ],
    'DO' => [
        'name' => 'Dominican Republic',
        'fullName' => 'Dominican Republic',
        'demonyms' => [
            'Dominicans'
        ],
        'keywords' => []
    ],
    'DZ' => [
        'name' => 'Algeria',
        'fullName' => 'People\'s Democratic Republic of Algeria',
        'demonyms' => [
            'Algerians'
        ],
        'keywords' => [
            'algerian'
        ]
    ],
    'EC' => [
        'name' => 'Ecuador',
        'fullName' => 'Republic of Ecuador',
        'demonyms' => [
            'Ecuadorians'
        ],
        'keywords' => [
            'ecuadorian'
        ]
    ],
    'EE' => [
        'name' => 'Estonia',
        'fullName' => 'Republic of Estonia',
        'demonyms' => [
            'Estonians'
        ],
        'keywords' => [
            'estonian'
        ]
    ],
    'EG' => [
        'name' => 'Egypt',
        'fullName' => 'Arab Republic of Egypt',
        'demonyms' => [
            'Egyptians'
        ],
        'keywords' => [
            'egyptian'
        ]
    ],
    'EH' => [
        'name' => 'Western Sahara',
        'fullName' => 'Sahrawi Arab Democratic Republic',
        'demonyms' => [
            'Sahrawis',
            'Western Saharans'
        ],
        'keywords' => [
            'sahrawi'
        ]
    ],
    'ER' => [
        'name' => 'Eritrea',
        'fullName' => 'State of Eritrea',
        'demonyms' => [
            'Eritreans'
        ],
        'keywords' => [
            'eritrean'
        ]
    ],
    'ES' => [
        'name' => 'Spain',
        'fullName' => 'Kingdom of Spain',
        'demonyms' => [
            'Spaniards'
        ],
        'keywords' => [
            'iberia',
            'iberian',
            'peninsula',
            'spanish'
        ]
    ],
    'ET' => [
        'name' => 'Ethiopia',
        'fullName' => 'Federal Democratic Republic of Ethiopia',
        'demonyms' => [
            'Ethiopians'
        ],
        'keywords' => [
            'ethiopian'
        ]
    ],
    'FI' => [
        'name' => 'Finland',
        'fullName' => 'Republic of Finland',
        'demonyms' => [
            'Finns'
        ],
        'keywords' => [
            'finnish'
        ]
    ],
    'FJ' => [
        'name' => 'Fiji',
        'fullName' => 'Republic of Fiji',
        'demonyms' => [
            'Fijians'
        ],
        'keywords' => [
            'fijian'
        ]
    ],
    'FK' => [
        'name' => 'Falkland Islands',
        'fullName' => 'Falkland Islands',
        'demonyms' => [
            'Falkland Islanders'
        ],
        'keywords' => [
            'falklandian',
            'falklandic',
            'falklander',
            'falklandish'
        ]
    ],
    'FM' => [
        'name' => 'Micronesia (Federated States of)',
        'fullName' => 'Federated States of Micronesia',
        'demonyms' => [
            'Micronesians'
        ],
        'keywords' => [
            'com',
            'micronesian'
        ]
    ],
    'FO' => [
        'name' => 'Faroe Islands',
        'fullName' => 'Fær Øer',
        'demonyms' => [
            'Faroese'
        ],
        'keywords' => []
    ],
    'FR' => [
        'name' => 'France',
        'fullName' => 'French Republic',
        'demonyms' => [
            'French'
        ],
        'keywords' => []
    ],
    'GA' => [
        'name' => 'Gabon',
        'fullName' => 'Gabonese Republic',
        'demonyms' => [
            'Gabonese'
        ],
        'keywords' => []
    ],
    'GB' => [
        'name' => 'United Kingdom',
        'fullName' => 'United Kingdom of Great Britain and Northern Ireland',
        'demonyms' => [
            'British',
            'English',
            'Scottish',
            'Welsh',
            'Irish',
            'Northern Irish'
        ],
        'keywords' => [
            'uk',
            'ukgb',
            'gbeng',
            'gbnir',
            'gbsct',
            'gbwls',
            'gbcym',
            'gbeaw',
            'gbgbn',
            'gbukm',
            'isles',
            'caledonia',
            'england',
            'britannia',
            'albion',
            'scotland',
            'wales',
            'ireland',
            'alba',
            'cymru',
            'ulster',
            'britons'
        ]
    ],
    'GD' => [
        'name' => 'Grenada',
        'fullName' => 'Grenada',
        'demonyms' => [
            'Grenadians'
        ],
        'keywords' => [
            'grenadian'
        ]
    ],
    'GE' => [
        'name' => 'Georgia',
        'fullName' => 'Republic of Georgia',
        'demonyms' => [
            'Georgians'
        ],
        'keywords' => [
            'georgian'
        ]
    ],
    'GF' => [
        'name' => 'French Guiana',
        'fullName' => 'Department of French Guiana',
        'demonyms' => [
            'French Guianese'
        ],
        'keywords' => [
            'guyana',
            'dom'
        ]
    ],
    'GG' => [
        'name' => 'Guernsey',
        'fullName' => 'Bailiwick of Guernsey',
        'demonyms' => [
            'Channel Islanders',
            'Guernsey Islanders'
        ],
        'keywords' => []
    ],
    'GH' => [
        'name' => 'Ghana',
        'fullName' => 'Republic of Ghana',
        'demonyms' => [
            'Ghanaians'
        ],
        'keywords' => [
            'ghanaian'
        ]
    ],
    'GI' => [
        'name' => 'Gibraltar',
        'fullName' => 'Gibraltar',
        'demonyms' => [
            'Gibraltarians'
        ],
        'keywords' => []
    ],
    'GL' => [
        'name' => 'Greenland',
        'fullName' => 'Greenland',
        'demonyms' => [
            'Greenlanders'
        ],
        'keywords' => [
            'inuit',
            'greenlandic'
        ]
    ],
    'GM' => [
        'name' => 'Gambia',
        'fullName' => 'Republic of The Gambia',
        'demonyms' => [
            'Gambians'
        ],
        'keywords' => [
            'gambian'
        ]
    ],
    'GN' => [
        'name' => 'Guinea',
        'fullName' => 'Republic of Guinea',
        'demonyms' => [
            'Guineans'
        ],
        'keywords' => [
            'conakry',
            'guinean'
        ]
    ],
    'GP' => [
        'name' => 'Guadeloupe',
        'fullName' => 'Department of Guadeloupe',
        'demonyms' => [
            'Guadeloupeans'
        ],
        'keywords' => [
            'dom'
        ]
    ],
    'GQ' => [
        'name' => 'Equatorial Guinea',
        'fullName' => 'Republic of Equatorial Guinea',
        'demonyms' => [
            'Equatorial Guineans'
        ],
        'keywords' => [
            'guinean'
        ]
    ],
    'GR' => [
        'name' => 'Greece',
        'fullName' => 'Hellenic Republic',
        'demonyms' => [
            'Greeks'
        ],
        'keywords' => [
            'hellenic',
            'republic',
            'greek',
            'el'
        ]
    ],
    'GS' => [
        'name' => 'South Georgia and the South Sandwich Islands',
        'fullName' => 'South Georgia and the South Sandwich Islands',
        'demonyms' => [
            'South Georgians',
            'South Sandwich Islanders'
        ],
        'keywords' => [
            'georgian'
        ]
    ],
    'GT' => [
        'name' => 'Guatemala',
        'fullName' => 'Republic of Guatemala',
        'demonyms' => [
            'Guatemalans'
        ],
        'keywords' => [
            'guatemalan'
        ]
    ],
    'GU' => [
        'name' => 'Guam',
        'fullName' => 'Guam',
        'demonyms' => [
            'Guamanians'
        ],
        'keywords' => [
            'guamanian'
        ]
    ],
    'GW' => [
        'name' => 'Guinea-Bissau',
        'fullName' => 'Republic of Guinea-Bissau',
        'demonyms' => [
            'Bissau-Guineans'
        ],
        'keywords' => [
            'portuguese',
            'guinea',
            'guineabissauan',
            'guineabissauans'
        ]
    ],
    'GY' => [
        'name' => 'Guyana',
        'fullName' => 'Co-operative Republic of Guyana',
        'demonyms' => [
            'Guyanese'
        ],
        'keywords' => []
    ],
    'HK' => [
        'name' => 'Hong Kong',
        'fullName' => 'Hong Kong Special Administrative Region of the People\'s Republic of China',
        'demonyms' => [
            'Hong Kongers',
            'Hongkongers'
        ],
        'keywords' => [
            'kongese',
            'hongkongish'
        ]
    ],
    'HM' => [
        'name' => 'Heard Island and McDonald Islands',
        'fullName' => 'Territory of Heard Island and McDonald Islands',
        'demonyms' => [],
        'keywords' => [
            'heardian',
            'heardians'
        ]
    ],
    'HN' => [
        'name' => 'Honduras',
        'fullName' => 'Republic of Honduras',
        'demonyms' => [
            'Hondurans'
        ],
        'keywords' => [
            'honduran'
        ]
    ],
    'HR' => [
        'name' => 'Croatia',
        'fullName' => 'Republic of Croatia',
        'demonyms' => [
            'Croatians'
        ],
        'keywords' => [
            'croatian'
        ]
    ],
    'HT' => [
        'name' => 'Haiti',
        'fullName' => 'Republic of Haiti',
        'demonyms' => [
            'Haitians'
        ],
        'keywords' => [
            'haitian'
        ]
    ],
    'HU' => [
        'name' => 'Hungary',
        'fullName' => 'Hungary',
        'demonyms' => [
            'Hungarians'
        ],
        'keywords' => [
            'hungarian'
        ]
    ],
    'ID' => [
        'name' => 'Indonesia',
        'fullName' => 'Republic of Indonesia',
        'demonyms' => [
            'Indonesians'
        ],
        'keywords' => [
            'portuguese',
            'timor',
            'indonesian'
        ]
    ],
    'IE' => [
        'name' => 'Ireland',
        'fullName' => 'Republic of Ireland',
        'demonyms' => [
            'Irish'
        ],
        'keywords' => [
            'eire'
        ]
    ],
    'IL' => [
        'name' => 'Israel',
        'fullName' => 'State of Israel',
        'demonyms' => [
            'Israelis'
        ],
        'keywords' => [
            'israeli'
        ]
    ],
    'IM' => [
        'name' => 'Isle of Man',
        'fullName' => 'British islands Isle of Man',
        'demonyms' => [
            'Manx'
        ],
        'keywords' => [
            'mann'
        ]
    ],
    'IN' => [
        'name' => 'India',
        'fullName' => 'Republic of India',
        'demonyms' => [
            'Indians'
        ],
        'keywords' => [
            'indian'
        ]
    ],
    'IO' => [
        'name' => 'British Indian Ocean Territory',
        'fullName' => 'British Indian Ocean Territory',
        'demonyms' => [
            'British Indians'
        ],
        'keywords' => [
            'chagos',
            'biot',
            'oceanic'
        ]
    ],
    'IQ' => [
        'name' => 'Iraq',
        'fullName' => 'Republic of Iraq',
        'demonyms' => [
            'Iraqis'
        ],
        'keywords' => [
            'mesopotamia',
            'iraqi'
        ]
    ],
    'IR' => [
        'name' => 'Iran',
        'fullName' => 'Islamic Republic of Iran',
        'demonyms' => [
            'Iranians'
        ],
        'keywords' => [
            'persia',
            'persian',
            'persians',
            'iranian'
        ]
    ],
    'IS' => [
        'name' => 'Iceland',
        'fullName' => 'Republic of Iceland',
        'demonyms' => [
            'Icelanders'
        ],
        'keywords' => [
            'icelandic'
        ]
    ],
    'IT' => [
        'name' => 'Italy',
        'fullName' => 'Italian Republic',
        'demonyms' => [
            'Italians'
        ],
        'keywords' => [
            'italian'
        ]
    ],
    'JE' => [
        'name' => 'Jersey',
        'fullName' => 'Bailiwick of Jersey',
        'demonyms' => [
            'Channel Islanders',
            'Jersey Islanders'
        ],
        'keywords' => [
            'norman',
            'islands'
        ]
    ],
    'JM' => [
        'name' => 'Jamaica',
        'fullName' => 'Jamaica',
        'demonyms' => [
            'Jamaicans'
        ],
        'keywords' => [
            'jamaican'
        ]
    ],
    'JO' => [
        'name' => 'Jordan',
        'fullName' => 'Hashemite Kingdom of Jordan',
        'demonyms' => [
            'Jordanians'
        ],
        'keywords' => [
            'jordanian'
        ]
    ],
    'JP' => [
        'name' => 'Japan',
        'fullName' => 'Japan',
        'demonyms' => [
            'Japanese'
        ],
        'keywords' => [
            'nippon'
        ]
    ],
    'KE' => [
        'name' => 'Kenya',
        'fullName' => 'Republic of Kenya',
        'demonyms' => [
            'Kenyans'
        ],
        'keywords' => [
            'kenyan'
        ]
    ],
    'KG' => [
        'name' => 'Kyrgyzstan',
        'fullName' => 'Kyrgyz Republic',
        'demonyms' => [
            'Kyrgyz'
        ],
        'keywords' => [
            'kyrgyzstani',
            'kyrgyzstanis'
        ]
    ],
    'KH' => [
        'name' => 'Cambodia',
        'fullName' => 'Kingdom of Cambodia',
        'demonyms' => [
            'Cambodians'
        ],
        'keywords' => [
            'cambodian'
        ]
    ],
    'KI' => [
        'name' => 'Kiribati',
        'fullName' => 'Republic of Kiribati',
        'demonyms' => [
            'I-Kiribati'
        ],
        'keywords' => []
    ],
    'KM' => [
        'name' => 'Comoros',
        'fullName' => 'Union of the Comoros',
        'demonyms' => [
            'Comorians'
        ],
        'keywords' => [
            'comoran'
        ]
    ],
    'KN' => [
        'name' => 'Saint Kitts and Nevis',
        'fullName' => 'Federation of Saint Kitts and Nevis',
        'demonyms' => [
            'Kittitians',
            'Nevisians'
        ],
        'keywords' => [
            'kittitian',
            'nevisian'
        ]
    ],
    'KP' => [
        'name' => 'Korea (Democratic People\'s Republic of)',
        'fullName' => 'Democratic People\'s Republic of Korea',
        'demonyms' => [
            'North Koreans'
        ],
        'keywords' => [
            'korean'
        ]
    ],
    'KR' => [
        'name' => 'Korea (Republic of)',
        'fullName' => 'Republic of Korea',
        'demonyms' => [
            'South Koreans'
        ],
        'keywords' => [
            'korean'
        ]
    ],
    'KW' => [
        'name' => 'Kuwait',
        'fullName' => 'State of Kuwait',
        'demonyms' => [
            'Kuwaitis'
        ],
        'keywords' => [
            'kuwaiti'
        ]
    ],
    'KY' => [
        'name' => 'Cayman Islands',
        'fullName' => 'Cayman Islands',
        'demonyms' => [
            'Caymanians'
        ],
        'keywords' => [
            'caymanian'
        ]
    ],
    'KZ' => [
        'name' => 'Kazakhstan',
        'fullName' => 'Republic of Kazakhstan',
        'demonyms' => [
            'Kazakhs'
        ],
        'keywords' => [
            'kazakhstani'
        ]
    ],
    'LA' => [
        'name' => 'Lao People\'s Democratic Republic',
        'fullName' => 'Lao People\'s Democratic Republic',
        'demonyms' => [
            'Laotians'
        ],
        'keywords' => [
            'laotian'
        ]
    ],
    'LB' => [
        'name' => 'Lebanon',
        'fullName' => 'Lebanese Republic',
        'demonyms' => [
            'Lebanese'
        ],
        'keywords' => []
    ],
    'LC' => [
        'name' => 'Saint Lucia',
        'fullName' => 'Saint Lucia',
        'demonyms' => [
            'Saint Lucians'
        ],
        'keywords' => [
            'lucian'
        ]
    ],
    'LI' => [
        'name' => 'Liechtenstein',
        'fullName' => 'Principality of Liechtenstein',
        'demonyms' => [
            'Liechtensteiners'
        ],
        'keywords' => []
    ],
    'LK' => [
        'name' => 'Sri Lanka',
        'fullName' => 'Democratic Socialist Republic of Sri Lanka',
        'demonyms' => [
            'Sri Lankans'
        ],
        'keywords' => [
            'ceylon',
            'lankan'
        ]
    ],
    'LR' => [
        'name' => 'Liberia',
        'fullName' => 'Republic of Liberia',
        'demonyms' => [
            'Liberians'
        ],
        'keywords' => [
            'liberian'
        ]
    ],
    'LS' => [
        'name' => 'Lesotho',
        'fullName' => 'Kingdom of Lesotho',
        'demonyms' => [
            'Basotho'
        ],
        'keywords' => []
    ],
    'LT' => [
        'name' => 'Lithuania',
        'fullName' => 'Republic of Lithuania',
        'demonyms' => [
            'Lithuanians'
        ],
        'keywords' => [
            'lithuanian'
        ]
    ],
    'LU' => [
        'name' => 'Luxembourg',
        'fullName' => 'Grand Duchy of Luxembourg',
        'demonyms' => [
            'Luxembourgers'
        ],
        'keywords' => []
    ],
    'LV' => [
        'name' => 'Latvia',
        'fullName' => 'Republic of Latvia',
        'demonyms' => [
            'Latvians'
        ],
        'keywords' => [
            'latvian'
        ]
    ],
    'LY' => [
        'name' => 'Libya',
        'fullName' => 'State of Libya',
        'demonyms' => [
            'Libyans'
        ],
        'keywords' => [
            'libyan'
        ]
    ],
    'MA' => [
        'name' => 'Morocco',
        'fullName' => 'Kingdom of Morocco',
        'demonyms' => [
            'Moroccans'
        ],
        'keywords' => [
            'moroccan'
        ]
    ],
    'MC' => [
        'name' => 'Monaco',
        'fullName' => 'Principality of Monaco',
        'demonyms' => [
            'Monégasque'
        ],
        'keywords' => [
            'monegasques'
        ]
    ],
    'MD' => [
        'name' => 'Moldova',
        'fullName' => 'Republic of Moldova',
        'demonyms' => [
            'Moldovans'
        ],
        'keywords' => [
            'moldovan'
        ]
    ],
    'ME' => [
        'name' => 'Montenegro',
        'fullName' => 'Montenegro',
        'demonyms' => [
            'Montenegrins'
        ],
        'keywords' => [
            'montenegrin'
        ]
    ],
    'MF' => [
        'name' => 'Saint Martin (French part)',
        'fullName' => 'Overseas Collectivity of Saint Martin',
        'demonyms' => [
            'Saint-Martinois'
        ],
        'keywords' => [
            'com',
            'saintmartinoise'
        ]
    ],
    'MG' => [
        'name' => 'Madagascar',
        'fullName' => 'Republic of Madagascar',
        'demonyms' => [
            'Malagasy'
        ],
        'keywords' => []
    ],
    'MH' => [
        'name' => 'Marshall Islands',
        'fullName' => 'Republic of the Marshall Islands',
        'demonyms' => [
            'Marshallese'
        ],
        'keywords' => []
    ],
    'MK' => [
        'name' => 'North Macedonia',
        'fullName' => 'Republic of North Macedonia',
        'demonyms' => [
            'Macedonians'
        ],
        'keywords' => [
            'macedonian'
        ]
    ],
    'ML' => [
        'name' => 'Mali',
        'fullName' => 'Republic of Mali',
        'demonyms' => [
            'Malians'
        ],
        'keywords' => [
            'malian'
        ]
    ],
    'MM' => [
        'name' => 'Myanmar',
        'fullName' => 'Republic of the Union of Myanmar',
        'demonyms' => [
            'Burmese'
        ],
        'keywords' => [
            'burma'
        ]
    ],
    'MN' => [
        'name' => 'Mongolia',
        'fullName' => 'Mongolia',
        'demonyms' => [
            'Mongolians'
        ],
        'keywords' => [
            'mongolian'
        ]
    ],
    'MO' => [
        'name' => 'Macau',
        'fullName' => 'Macau Special Administrative Region of the People\'s Republic of China',
        'demonyms' => [
            'Macanese'
        ],
        'keywords' => []
    ],
    'MP' => [
        'name' => 'Northern Mariana Islands',
        'fullName' => 'Commonwealth of the Northern Mariana Islands',
        'demonyms' => [
            'Northern Mariana Islanders'
        ],
        'keywords' => [
            'marianan'
        ]
    ],
    'MQ' => [
        'name' => 'Martinique',
        'fullName' => 'Territorial Collectivity of Martinique',
        'demonyms' => [
            'Martiniquais'
        ],
        'keywords' => [
            'dom'
        ]
    ],
    'MR' => [
        'name' => 'Mauritania',
        'fullName' => 'Islamic Republic of Mauritania',
        'demonyms' => [
            'Mauritanians'
        ],
        'keywords' => [
            'mauritanian'
        ]
    ],
    'MS' => [
        'name' => 'Montserrat',
        'fullName' => 'Colony of Montserrat',
        'demonyms' => [
            'Montserratians'
        ],
        'keywords' => [
            'montserratian'
        ]
    ],
    'MT' => [
        'name' => 'Malta',
        'fullName' => 'Republic of Malta',
        'demonyms' => [
            'Maltese'
        ],
        'keywords' => []
    ],
    'MU' => [
        'name' => 'Mauritius',
        'fullName' => 'Republic of Mauritius',
        'demonyms' => [
            'Mauritians'
        ],
        'keywords' => [
            'mauritian'
        ]
    ],
    'MV' => [
        'name' => 'Maldives',
        'fullName' => 'Republic of Maldives',
        'demonyms' => [
            'Maldivians'
        ],
        'keywords' => [
            'maldivian'
        ]
    ],
    'MW' => [
        'name' => 'Malawi',
        'fullName' => 'Republic of Malawi',
        'demonyms' => [
            'Malawians'
        ],
        'keywords' => [
            'malawian'
        ]
    ],
    'MX' => [
        'name' => 'Mexico',
        'fullName' => 'United Mexican States',
        'demonyms' => [
            'Mexicans'
        ],
        'keywords' => [
            'mexican'
        ]
    ],
    'MY' => [
        'name' => 'Malaysia',
        'fullName' => 'Malaysia',
        'demonyms' => [
            'Malaysians'
        ],
        'keywords' => [
            'malaysian'
        ]
    ],
    'MZ' => [
        'name' => 'Mozambique',
        'fullName' => 'Republic of Mozambique',
        'demonyms' => [
            'Mozambicans'
        ],
        'keywords' => [
            'mozambican'
        ]
    ],
    'NA' => [
        'name' => 'Namibia',
        'fullName' => 'Republic of Namibia',
        'demonyms' => [
            'Namibians'
        ],
        'keywords' => [
            'namibian'
        ]
    ],
    'NC' => [
        'name' => 'New Caledonia',
        'fullName' => 'Government of New Caledonia',
        'demonyms' => [
            'New Caledonians'
        ],
        'keywords' => [
            'com',
            'caledonian'
        ]
    ],
    'NE' => [
        'name' => 'Niger',
        'fullName' => 'Republic of Niger',
        'demonyms' => [
            'Nigeriens'
        ],
        'keywords' => [
            'nigerien'
        ]
    ],
    'NF' => [
        'name' => 'Norfolk Island',
        'fullName' => 'Territory of Norfolk Island',
        'demonyms' => [
            'Norfolk Islanders'
        ],
        'keywords' => []
    ],
    'NG' => [
        'name' => 'Nigeria',
        'fullName' => 'Federal Republic of Nigeria',
        'demonyms' => [
            'Nigerians'
        ],
        'keywords' => [
            'nigerian'
        ]
    ],
    'NI' => [
        'name' => 'Nicaragua',
        'fullName' => 'Republic of Nicaragua',
        'demonyms' => [
            'Nicaraguans'
        ],
        'keywords' => [
            'nicaraguan'
        ]
    ],
    'NL' => [
        'name' => 'Netherlands',
        'fullName' => 'Kingdom of the Netherlands',
        'demonyms' => [
            'Dutch'
        ],
        'keywords' => [
            'holland'
        ]
    ],
    'NO' => [
        'name' => 'Norway',
        'fullName' => 'Kingdom of Norway',
        'demonyms' => [
            'Norwegians'
        ],
        'keywords' => [
            'norwegian'
        ]
    ],
    'NP' => [
        'name' => 'Nepal',
        'fullName' => 'Federal Democratic Republic of Nepal',
        'demonyms' => [
            'Nepalis'
        ],
        'keywords' => [
            'nepali'
        ]
    ],
    'NR' => [
        'name' => 'Nauru',
        'fullName' => 'Republic of Nauru',
        'demonyms' => [
            'Nauruans'
        ],
        'keywords' => [
            'nauruan'
        ]
    ],
    'NU' => [
        'name' => 'Niue',
        'fullName' => 'Niue',
        'demonyms' => [
            'Niueans'
        ],
        'keywords' => [
            'niuean'
        ]
    ],
    'NZ' => [
        'name' => 'New Zealand',
        'fullName' => 'New Zealand',
        'demonyms' => [
            'New Zealanders'
        ],
        'keywords' => [
            'zealandish',
            'zealander',
            'kiwi'
        ]
    ],
    'OM' => [
        'name' => 'Oman',
        'fullName' => 'Sultanate of Oman',
        'demonyms' => [
            'Omanis'
        ],
        'keywords' => [
            'omani'
        ]
    ],
    'PA' => [
        'name' => 'Panama',
        'fullName' => 'Republic of Panama',
        'demonyms' => [
            'Panamanians'
        ],
        'keywords' => [
            'panamanian'
        ]
    ],
    'PE' => [
        'name' => 'Peru',
        'fullName' => 'Republic of Peru',
        'demonyms' => [
            'Peruvians'
        ],
        'keywords' => [
            'peruvian'
        ]
    ],
    'PF' => [
        'name' => 'French Polynesia',
        'fullName' => 'Overseas Collectivity of French Polynesia',
        'demonyms' => [
            'French Polynesians'
        ],
        'keywords' => [
            'com',
            'polynesian'
        ]
    ],
    'PG' => [
        'name' => 'Papua New Guinea',
        'fullName' => 'Independent State of Papua New Guinea',
        'demonyms' => [
            'Papua New Guineans'
        ],
        'keywords' => [
            'guinean'
        ]
    ],
    'PH' => [
        'name' => 'Philippines',
        'fullName' => 'Republic of the Philippines',
        'demonyms' => [
            'Filipinos'
        ],
        'keywords' => [
            'filipino'
        ]
    ],
    'PK' => [
        'name' => 'Pakistan',
        'fullName' => 'Islamic Republic of Pakistan',
        'demonyms' => [
            'Pakistanis'
        ],
        'keywords' => [
            'pakistani'
        ]
    ],
    'PL' => [
        'name' => 'Poland',
        'fullName' => 'Republic of Poland',
        'demonyms' => [
            'Poles'
        ],
        'keywords' => [
            'polish'
        ]
    ],
    'PM' => [
        'name' => 'Saint Pierre and Miquelon',
        'fullName' => 'Overseas Collectivity of Saint-Pierre and Miquelon',
        'demonyms' => [
            'Saint-Pierrais',
            'Miquelonnais'
        ],
        'keywords' => [
            'com',
            'or'
        ]
    ],
    'PN' => [
        'name' => 'Pitcairn',
        'fullName' => 'Pitcairn, Henderson, Ducie and Oeno Islands',
        'demonyms' => [
            'Pitcairn Islanders'
        ],
        'keywords' => [
            'island'
        ]
    ],
    'PR' => [
        'name' => 'Puerto Rico',
        'fullName' => 'Commonwealth of Puerto Rico',
        'demonyms' => [
            'Puerto Ricans'
        ],
        'keywords' => [
            'rican'
        ]
    ],
    'PS' => [
        'name' => 'Palestine',
        'fullName' => 'State of Palestine',
        'demonyms' => [
            'Palestinians'
        ],
        'keywords' => [
            'palestinian'
        ]
    ],
    'PT' => [
        'name' => 'Portugal',
        'fullName' => 'Portuguese Republic',
        'demonyms' => [
            'Portuguese'
        ],
        'keywords' => []
    ],
    'PW' => [
        'name' => 'Palau',
        'fullName' => 'Republic of Palau',
        'demonyms' => [
            'Palauans'
        ],
        'keywords' => [
            'palauan'
        ]
    ],
    'PY' => [
        'name' => 'Paraguay',
        'fullName' => 'Republic of Paraguay',
        'demonyms' => [
            'Paraguayans'
        ],
        'keywords' => [
            'paraguayan'
        ]
    ],
    'QA' => [
        'name' => 'Qatar',
        'fullName' => 'State of Qatar',
        'demonyms' => [
            'Qataris'
        ],
        'keywords' => [
            'qatari'
        ]
    ],
    'RE' => [
        'name' => 'The Réunion',
        'fullName' => 'Department of Réunion',
        'demonyms' => [
            'Réunionnais'
        ],
        'keywords' => [
            'dom',
            'reunionese'
        ]
    ],
    'RO' => [
        'name' => 'Romania',
        'fullName' => 'Romania',
        'demonyms' => [
            'Romanians'
        ],
        'keywords' => [
            'romanian'
        ]
    ],
    'RS' => [
        'name' => 'Serbia',
        'fullName' => 'Republic of Serbia',
        'demonyms' => [
            'Serbians'
        ],
        'keywords' => [
            'serbian',
            'serbs'
        ]
    ],
    'RU' => [
        'name' => 'Russian Federation',
        'fullName' => 'Russian Federation',
        'demonyms' => [
            'Russians'
        ],
        'keywords' => []
    ],
    'RW' => [
        'name' => 'Rwanda',
        'fullName' => 'Republic of Rwanda',
        'demonyms' => [
            'Rwandans'
        ],
        'keywords' => [
            'rwandan'
        ]
    ],
    'SA' => [
        'name' => 'Saudi Arabia',
        'fullName' => 'Kingdom of Saudi Arabia',
        'demonyms' => [
            'Saudi Arabians'
        ],
        'keywords' => [
            'arabian'
        ]
    ],
    'SB' => [
        'name' => 'Solomon Islands',
        'fullName' => 'Solomon Islands',
        'demonyms' => [
            'Solomon Islanders'
        ],
        'keywords' => []
    ],
    'SC' => [
        'name' => 'Seychelles',
        'fullName' => 'Republic of Seychelles',
        'demonyms' => [
            'Seychellois'
        ],
        'keywords' => []
    ],
    'SD' => [
        'name' => 'Sudan',
        'fullName' => 'Republic of the Sudan',
        'demonyms' => [
            'Sudanese'
        ],
        'keywords' => []
    ],
    'SE' => [
        'name' => 'Sweden',
        'fullName' => 'Kingdom of Sweden',
        'demonyms' => [
            'Swedes'
        ],
        'keywords' => [
            'swedish'
        ]
    ],
    'SG' => [
        'name' => 'Singapore',
        'fullName' => 'Republic of Singapore',
        'demonyms' => [
            'Singaporeans'
        ],
        'keywords' => [
            'singaporean'
        ]
    ],
    'SH' => [
        'name' => 'Saint Helena, Ascension and Tristan da Cunha',
        'fullName' => 'Saint Helena, Ascension and Tristan da Cunha',
        'demonyms' => [
            'Saint Helenians'
        ],
        'keywords' => [
            'helenian'
        ]
    ],
    'SI' => [
        'name' => 'Slovenia',
        'fullName' => 'Republic of Slovenia',
        'demonyms' => [
            'Slovenes'
        ],
        'keywords' => [
            'slovenian',
            'slovenians'
        ]
    ],
    'SJ' => [
        'name' => 'Svalbard and Jan Mayen',
        'fullName' => 'Svalbard and Jan Mayen Islands',
        'demonyms' => [
            'Svalbard and Jan Mayen Islanders'
        ],
        'keywords' => []
    ],
    'SK' => [
        'name' => 'Slovakia',
        'fullName' => 'Slovak Republic',
        'demonyms' => [
            'Slovaks'
        ],
        'keywords' => [
            'slovak'
        ]
    ],
    'SL' => [
        'name' => 'Sierra Leone',
        'fullName' => 'Republic of Sierra Leone',
        'demonyms' => [
            'Sierra Leoneans'
        ],
        'keywords' => [
            'leonean'
        ]
    ],
    'SM' => [
        'name' => 'San Marino',
        'fullName' => 'Republic of San Marino',
        'demonyms' => [
            'Sammarinese'
        ],
        'keywords' => [
            'sanmarinese'
        ]
    ],
    'SN' => [
        'name' => 'Senegal',
        'fullName' => 'Republic of Senegal',
        'demonyms' => [
            'Senegalese'
        ],
        'keywords' => []
    ],
    'SO' => [
        'name' => 'Somalia',
        'fullName' => 'Federal Republic of Somalia',
        'demonyms' => [
            'Somalis'
        ],
        'keywords' => [
            'somali'
        ]
    ],
    'SR' => [
        'name' => 'Suriname',
        'fullName' => 'Republic of Suriname',
        'demonyms' => [
            'Surinamese'
        ],
        'keywords' => []
    ],
    'SS' => [
        'name' => 'South Sudan',
        'fullName' => 'Republic of South Sudan',
        'demonyms' => [
            'South Sudanese'
        ],
        'keywords' => []
    ],
    'ST' => [
        'name' => 'Sao Tome and Principe',
        'fullName' => 'Democratic Republic of São Tomé and Príncipe',
        'demonyms' => [
            'São Toméans'
        ],
        'keywords' => [
            'tomean'
        ]
    ],
    'SV' => [
        'name' => 'El Salvador',
        'fullName' => 'Republic of El Salvador',
        'demonyms' => [
            'Salvadorans'
        ],
        'keywords' => [
            'salvadoran'
        ]
    ],
    'SX' => [
        'name' => 'Sint Maarten',
        'fullName' => 'Sint Maarten',
        'demonyms' => [
            'Sint Maarteners'
        ],
        'keywords' => [
            'sss',
            'islands'
        ]
    ],
    'SY' => [
        'name' => 'Syrian Arab Republic',
        'fullName' => 'Syrian Arab Republic',
        'demonyms' => [
            'Syrians'
        ],
        'keywords' => []
    ],
    'SZ' => [
        'name' => 'Eswatini',
        'fullName' => 'Kingdom of Eswatini',
        'demonyms' => [
            'Swazis'
        ],
        'keywords' => [
            'swazi'
        ]
    ],
    'TC' => [
        'name' => 'Turks and Caicos Islands',
        'fullName' => 'Turks and Caicos Islands',
        'demonyms' => [
            'Turks and Caicos Islanders'
        ],
        'keywords' => [
            'island'
        ]
    ],
    'TD' => [
        'name' => 'Chad',
        'fullName' => 'Republic of Chad',
        'demonyms' => [
            'Chadians'
        ],
        'keywords' => [
            'chadian'
        ]
    ],
    'TF' => [
        'name' => 'French Southern Territories',
        'fullName' => 'French Southern and Antarctic Lands',
        'demonyms' => [
            'French Southern and Antarctic Lands'
        ],
        'keywords' => [
            'taaf'
        ]
    ],
    'TG' => [
        'name' => 'Togo',
        'fullName' => 'Togolese Republic',
        'demonyms' => [
            'Togolese'
        ],
        'keywords' => []
    ],
    'TH' => [
        'name' => 'Thailand',
        'fullName' => 'Kingdom of Thailand',
        'demonyms' => [
            'Thais'
        ],
        'keywords' => [
            'thai'
        ]
    ],
    'TJ' => [
        'name' => 'Tajikistan',
        'fullName' => 'Republic of Tajikistan',
        'demonyms' => [
            'Tajiks'
        ],
        'keywords' => [
            'tajikistani'
        ]
    ],
    'TK' => [
        'name' => 'Tokelau',
        'fullName' => 'Tokelau Islands',
        'demonyms' => [
            'Tokelauans'
        ],
        'keywords' => [
            'union',
            'islands',
            'tokelauan'
        ]
    ],
    'TL' => [
        'name' => 'East Timor',
        'fullName' => 'Democratic Republic of Timor-Leste',
        'demonyms' => [
            'East Timorese'
        ],
        'keywords' => []
    ],
    'TM' => [
        'name' => 'Turkmenistan',
        'fullName' => 'Turkmenistan',
        'demonyms' => [
            'Turkmen'
        ],
        'keywords' => [
            'turkmens'
        ]
    ],
    'TN' => [
        'name' => 'Tunisia',
        'fullName' => 'Republic of Tunisia',
        'demonyms' => [
            'Tunisians'
        ],
        'keywords' => [
            'tunisian'
        ]
    ],
    'TO' => [
        'name' => 'Tonga',
        'fullName' => 'Kingdom of Tonga',
        'demonyms' => [
            'Tongans'
        ],
        'keywords' => [
            'tongan'
        ]
    ],
    'TR' => [
        'name' => 'Turkey',
        'fullName' => 'Republic of Turkey',
        'demonyms' => [
            'Turks'
        ],
        'keywords' => [
            'turkish'
        ]
    ],
    'TT' => [
        'name' => 'Trinidad and Tobago',
        'fullName' => 'Republic of Trinidad and Tobago',
        'demonyms' => [
            'Trinidadians',
            'Tobagonians'
        ],
        'keywords' => [
            'trinidadian'
        ]
    ],
    'TV' => [
        'name' => 'Tuvalu',
        'fullName' => 'Tuvalu',
        'demonyms' => [
            'Tuvaluans'
        ],
        'keywords' => [
            'tuvaluan'
        ]
    ],
    'TW' => [
        'name' => 'Taiwan',
        'fullName' => 'Republic of China',
        'demonyms' => [
            'Taiwanese'
        ],
        'keywords' => [
            'formosa'
        ]
    ],
    'TZ' => [
        'name' => 'Tanzania, United Republic of',
        'fullName' => 'United Republic of Tanzania',
        'demonyms' => [
            'Tanzanians'
        ],
        'keywords' => [
            'tanzanian'
        ]
    ],
    'UA' => [
        'name' => 'Ukraine',
        'fullName' => 'Ukraine',
        'demonyms' => [
            'Ukrainians'
        ],
        'keywords' => [
            'little',
            'russia',
            'ukrainian'
        ]
    ],
    'UG' => [
        'name' => 'Uganda',
        'fullName' => 'Republic of Uganda',
        'demonyms' => [
            'Ugandans'
        ],
        'keywords' => [
            'ugandan'
        ]
    ],
    'UM' => [
        'name' => 'United States Minor Outlying Islands',
        'fullName' => 'United States Minor Outlying Islands',
        'demonyms' => [],
        'keywords' => [
            'usmoi'
        ]
    ],
    'US' => [
        'name' => 'United States',
        'fullName' => 'United States of America',
        'demonyms' => [
            'Americans'
        ],
        'keywords' => [
            'usa',
            'us',
            'america',
            'american'
        ]
    ],
    'UY' => [
        'name' => 'Uruguay',
        'fullName' => 'Oriental Republic of Uruguay',
        'demonyms' => [
            'Uruguayans'
        ],
        'keywords' => [
            'uruguayan'
        ]
    ],
    'UZ' => [
        'name' => 'Uzbekistan',
        'fullName' => 'Republic of Uzbekistan',
        'demonyms' => [
            'Uzbeks'
        ],
        'keywords' => [
            'uzbekistani'
        ]
    ],
    'VA' => [
        'name' => 'Holy See',
        'fullName' => 'Vatican City State',
        'demonyms' => [
            'Vatican Citizens'
        ],
        'keywords' => []
    ],
    'VC' => [
        'name' => 'Saint Vincent and the Grenadines',
        'fullName' => 'Saint Vincent and the Grenadines',
        'demonyms' => [
            'Saint Vincentians',
            'Grenadines'
        ],
        'keywords' => [
            'vincentian'
        ]
    ],
    'VE' => [
        'name' => 'Venezuela',
        'fullName' => 'Bolivarian Republic of Venezuela',
        'demonyms' => [
            'Venezuelans'
        ],
        'keywords' => [
            'venezuelan'
        ]
    ],
    'VG' => [
        'name' => 'Virgin Islands (British)',
        'fullName' => 'British Virgin Islands',
        'demonyms' => [
            'British Virgin Islanders'
        ],
        'keywords' => []
    ],
    'VI' => [
        'name' => 'Virgin Islands (U.S.)',
        'fullName' => 'United States Virgin Islands',
        'demonyms' => [
            'United States Virgin Islanders'
        ],
        'keywords' => []
    ],
    'VN' => [
        'name' => 'Viet Nam',
        'fullName' => 'Socialist Republic of Vietnam',
        'demonyms' => [
            'Vietnamese'
        ],
        'keywords' => []
    ],
    'VU' => [
        'name' => 'Vanuatu',
        'fullName' => 'Republic of Vanuatu',
        'demonyms' => [
            'Ni-Vanuatu'
        ],
        'keywords' => [
            'vanuatuan',
            'vanuatuans'
        ]
    ],
    'WF' => [
        'name' => 'Wallis and Futuna',
        'fullName' => 'Overseas Collectivity of the Wallis and Futuna Islands',
        'demonyms' => [
            'Wallis and Futuna Islanders',
            'Wallisian-Futunan'
        ],
        'keywords' => [
            'alofi',
            'com'
        ]
    ],
    'WS' => [
        'name' => 'Samoa',
        'fullName' => 'Independent State of Samoa',
        'demonyms' => [
            'Samoans'
        ],
        'keywords' => [
            'samoan'
        ]
    ],
    'XK' => [
        'name' => 'Kosovo',
        'fullName' => 'Republic of Kosovo',
        'demonyms' => [
            'Yemenis'
        ],
        'keywords' => [
            'kosovar',
            'kosovars',
            'kosovan',
            'kosovans'
        ]
    ],
    'YE' => [
        'name' => 'Yemen',
        'fullName' => 'Republic of Yemen',
        'demonyms' => [
            'Yemenis'
        ],
        'keywords' => [
            'yemeni'
        ]
    ],
    'YT' => [
        'name' => 'Mayotte',
        'fullName' => 'Departmental Collectivity of Mayotte',
        'demonyms' => [
            'Mahorais'
        ],
        'keywords' => [
            'dom',
            'mahoran',
            'mahorans'
        ]
    ],
    'ZA' => [
        'name' => 'South Africa',
        'fullName' => 'Republic of South Africa',
        'demonyms' => [
            'South Africans'
        ],
        'keywords' => [
            'african'
        ]
    ],
    'ZM' => [
        'name' => 'Zambia',
        'fullName' => 'Republic of Zambia',
        'demonyms' => [
            'Zambians'
        ],
        'keywords' => [
            'zambian'
        ]
    ],
    'ZW' => [
        'name' => 'Zimbabwe',
        'fullName' => 'Republic of Zimbabwe',
        'demonyms' => [
            'Zimbabweans'
        ],
        'keywords' => [
            'zimbabwean'
        ]
    ]
];
