<?php

/**
 * This file has been automatically generated by the `build` script in the `dev` section.
 * Any modifications you make will be overwritten.
 * To modify the parameters in this file, please follow these steps:
 * - Go to the `dev/origin` section.
 * - Modify the corresponding JSON file.
 * - Run the `build` script again from the root of this project using one of these commands:
 *   - `dev/build`
 *   - `sh dev/build`
 * For further and more detailed information, please read the README.md file in the dev section.
*/

return [
  'AD' => [
    'name' => 'Andorra',
    'completeName' => 'Principality of Andorra',
    'demonyms' => [
       'Andorrans',
    ],
    'keywords' => [
       'andorran',
    ],
  ],
  'AE' => [
    'name' => 'United Arab Emirates',
    'completeName' => 'United Arab Emirates',
    'demonyms' => [
       'Emiratis',
       'Emaratians',
    ],
    'keywords' => [
       'uae',
       'emirati',
    ],
  ],
  'AF' => [
    'name' => 'Afghanistan',
    'completeName' => 'Islamic Emirate of Afghanistan',
    'demonyms' => [
       'Afghans',
    ],
    'keywords' => [
       'afghan',
    ],
  ],
  'AG' => [
    'name' => 'Antigua and Barbuda',
    'completeName' => 'Antigua and Barbuda',
    'demonyms' => [
       'Antiguans',
       'Barbudans',
    ],
    'keywords' => [
       'antiguan',
       'barbudan',
    ],
  ],
  'AI' => [
    'name' => 'Anguilla',
    'completeName' => 'Anguilla',
    'demonyms' => [
       'Anguillans',
    ],
    'keywords' => [
       'anguillan',
    ],
  ],
  'AL' => [
    'name' => 'Albania',
    'completeName' => 'Republic of Albania',
    'demonyms' => [
       'Albanians',
    ],
    'keywords' => [
       'albanian',
    ],
  ],
  'AM' => [
    'name' => 'Armenia',
    'completeName' => 'Republic of Armenia',
    'demonyms' => [
       'Armenians',
    ],
    'keywords' => [
       'armenian',
    ],
  ],
  'AO' => [
    'name' => 'Angola',
    'completeName' => 'Republic of Angola',
    'demonyms' => [
       'Angolans',
    ],
    'keywords' => [
       'angolan',
    ],
  ],
  'AQ' => [
    'name' => 'Antarctica',
    'completeName' => 'Antarctica',
    'demonyms' => [
    ],
    'keywords' => [
       'antarctics',
       'antarctic',
    ],
  ],
  'AR' => [
    'name' => 'Argentina',
    'completeName' => 'Argentine Republic',
    'demonyms' => [
       'Argentinians',
    ],
    'keywords' => [
       'argentines',
    ],
  ],
  'AS' => [
    'name' => 'American Samoa',
    'completeName' => 'American Samoa',
    'demonyms' => [
       'Samoans',
    ],
    'keywords' => [
       'samoan',
    ],
  ],
  'AT' => [
    'name' => 'Austria',
    'completeName' => 'Republic of Austria',
    'demonyms' => [
       'Austrians',
    ],
    'keywords' => [
       'austrian',
    ],
  ],
  'AU' => [
    'name' => 'Australia',
    'completeName' => 'Commonwealth of Australia',
    'demonyms' => [
       'Australians',
    ],
    'keywords' => [
       'aussie',
       'australian',
    ],
  ],
  'AW' => [
    'name' => 'Aruba',
    'completeName' => 'Country of Aruba',
    'demonyms' => [
       'Arubans',
    ],
    'keywords' => [
       'abc',
       'islands',
       'aruban',
    ],
  ],
  'AX' => [
    'name' => 'Åland Islands',
    'completeName' => 'Region of Åland',
    'demonyms' => [
       'Åland Islanders',
    ],
    'keywords' => [
       'alandic',
       'alandics',
    ],
  ],
  'AZ' => [
    'name' => 'Azerbaijan',
    'completeName' => 'Republic of Azerbaijan',
    'demonyms' => [
       'Azerbaijanis',
    ],
    'keywords' => [
       'azerbaijani',
    ],
  ],
  'BA' => [
    'name' => 'Bosnia and Herzegovina',
    'completeName' => 'Bosnia and Herzegovina',
    'demonyms' => [
       'Bosnians',
       'Herzegovinians',
    ],
    'keywords' => [
       'bosnian',
       'herzegovinian',
    ],
  ],
  'BB' => [
    'name' => 'Barbados',
    'completeName' => 'Barbados',
    'demonyms' => [
       'Barbadians',
    ],
    'keywords' => [
       'barbadian',
    ],
  ],
  'BD' => [
    'name' => 'Bangladesh',
    'completeName' => 'People\'s Republic of Bangladesh',
    'demonyms' => [
       'Bangladeshis',
    ],
    'keywords' => [
       'bangladeshi',
    ],
  ],
  'BE' => [
    'name' => 'Belgium',
    'completeName' => 'Kingdom of Belgium',
    'demonyms' => [
       'Belgians',
    ],
    'keywords' => [
       'belgian',
    ],
  ],
  'BF' => [
    'name' => 'Burkina Faso',
    'completeName' => 'Burkina Faso',
    'demonyms' => [
       'Burkinabés',
    ],
    'keywords' => [
       'burkinabe',
    ],
  ],
  'BG' => [
    'name' => 'Bulgaria',
    'completeName' => 'Republic of Bulgaria',
    'demonyms' => [
       'Bulgarians',
    ],
    'keywords' => [
       'bulgarian',
    ],
  ],
  'BH' => [
    'name' => 'Bahrain',
    'completeName' => 'Kingdom of Bahrain',
    'demonyms' => [
       'Bahrainis',
    ],
    'keywords' => [
       'bahraini',
    ],
  ],
  'BI' => [
    'name' => 'Burundi',
    'completeName' => 'Republic of Burundi',
    'demonyms' => [
       'Burundians',
    ],
    'keywords' => [
       'burundian',
    ],
  ],
  'BJ' => [
    'name' => 'Benin',
    'completeName' => 'Republic of Benin',
    'demonyms' => [
       'Beninese',
    ],
    'keywords' => [
       'dahomey',
    ],
  ],
  'BL' => [
    'name' => 'Saint Barthélemy',
    'completeName' => 'Overseas Collectivity of Saint Barthélemy',
    'demonyms' => [
       'Barthélemois',
       'Saint Barthélemy Islanders',
    ],
    'keywords' => [
       'com',
    ],
  ],
  'BM' => [
    'name' => 'Bermuda',
    'completeName' => 'Bermuda',
    'demonyms' => [
       'Bermudians',
    ],
    'keywords' => [
       'bermudian',
    ],
  ],
  'BN' => [
    'name' => 'Brunei',
    'completeName' => 'Brunei Darussalam',
    'demonyms' => [
       'Bruneians',
    ],
    'keywords' => [
       'bruneian',
    ],
  ],
  'BO' => [
    'name' => 'Bolivia',
    'completeName' => 'Plurinational State of Bolivia',
    'demonyms' => [
       'Bolivians',
    ],
    'keywords' => [
       'bolivian',
    ],
  ],
  'BQ' => [
    'name' => 'Bonaire, Sint Eustatius and Saba',
    'completeName' => 'Caribbean Netherlands',
    'demonyms' => [
       'Bonaireans',
       'Saba Islanders',
       'Sabans',
       'Sint Eustatians',
    ],
    'keywords' => [
       'abc',
       'islands',
       'sss',
       'bes',
       'bonairian',
       'bonairians',
       'eustatian',
       'saban',
    ],
  ],
  'BR' => [
    'name' => 'Brazil',
    'completeName' => 'Federative Republic of Brazil',
    'demonyms' => [
       'Brazilians',
    ],
    'keywords' => [
       'brazilian',
    ],
  ],
  'BS' => [
    'name' => 'Bahamas',
    'completeName' => 'Commonwealth of The Bahamas',
    'demonyms' => [
       'Bahamians',
    ],
    'keywords' => [
       'bahamian',
    ],
  ],
  'BT' => [
    'name' => 'Bhutan',
    'completeName' => 'Kingdom of Bhutan',
    'demonyms' => [
       'Bhutanese',
    ],
    'keywords' => [
       'thunder',
       'dragon',
       'druk',
       'yul',
    ],
  ],
  'BV' => [
    'name' => 'Bouvet Island',
    'completeName' => 'Bouvet Island',
    'demonyms' => [
       'Bouvet Islanders',
    ],
    'keywords' => [
    ],
  ],
  'BW' => [
    'name' => 'Botswana',
    'completeName' => 'Republic of Botswana',
    'demonyms' => [
       'Batswana',
    ],
    'keywords' => [
       'botswanan',
    ],
  ],
  'BY' => [
    'name' => 'Belarus',
    'completeName' => 'Republic of Belarus',
    'demonyms' => [
       'Belarusians',
    ],
    'keywords' => [
       'white',
       'russia',
       'belarusian',
    ],
  ],
  'BZ' => [
    'name' => 'Belize',
    'completeName' => 'Belize',
    'demonyms' => [
       'Belizeans',
    ],
    'keywords' => [
       'british',
       'honduras',
       'belizean',
    ],
  ],
  'CA' => [
    'name' => 'Canada',
    'completeName' => 'Canada',
    'demonyms' => [
       'Canadians',
    ],
    'keywords' => [
       'canadian',
    ],
  ],
  'CC' => [
    'name' => 'Cocos (Keeling) Islands',
    'completeName' => 'Cocos (Keeling) Islands',
    'demonyms' => [
       'Cocosian',
       'Cocos Islanders',
    ],
    'keywords' => [
    ],
  ],
  'CD' => [
    'name' => 'Congo (Democratic Republic of the)',
    'completeName' => 'Democratic Republic of the Congo',
    'demonyms' => [
       'Congolese',
    ],
    'keywords' => [
       'kinshasa',
       'rdc',
       'belgian',
       'zaire',
    ],
  ],
  'CF' => [
    'name' => 'Central African Republic',
    'completeName' => 'Central African Republic',
    'demonyms' => [
       'Central Africans',
    ],
    'keywords' => [
    ],
  ],
  'CG' => [
    'name' => 'Congo',
    'completeName' => 'Republic of the Congo',
    'demonyms' => [
       'Congolese',
    ],
    'keywords' => [
       'brazzaville',
       'french',
    ],
  ],
  'CH' => [
    'name' => 'Switzerland',
    'completeName' => 'Swiss Confederation',
    'demonyms' => [
       'Swiss',
    ],
    'keywords' => [
    ],
  ],
  'CI' => [
    'name' => 'Côte d\'Ivoire',
    'completeName' => 'Republic of Côte d\'Ivoire',
    'demonyms' => [
       'Ivorians',
    ],
    'keywords' => [
       'ivorian',
    ],
  ],
  'CK' => [
    'name' => 'Cook Islands',
    'completeName' => 'Cook Islands',
    'demonyms' => [
       'Cook Islanders',
    ],
    'keywords' => [
       'island',
    ],
  ],
  'CL' => [
    'name' => 'Chile',
    'completeName' => 'Republic of Chile',
    'demonyms' => [
       'Chileans',
    ],
    'keywords' => [
       'chilean',
    ],
  ],
  'CM' => [
    'name' => 'Cameroon',
    'completeName' => 'Republic of Cameroon',
    'demonyms' => [
       'Cameroonians',
    ],
    'keywords' => [
       'cameroonian',
    ],
  ],
  'CN' => [
    'name' => 'China',
    'completeName' => 'People\'s Republic of China',
    'demonyms' => [
       'Chinese',
    ],
    'keywords' => [
    ],
  ],
  'CO' => [
    'name' => 'Colombia',
    'completeName' => 'Republic of Colombia',
    'demonyms' => [
       'Colombians',
    ],
    'keywords' => [
       'colombian',
    ],
  ],
  'CR' => [
    'name' => 'Costa Rica',
    'completeName' => 'Republic of Costa Rica',
    'demonyms' => [
       'Costa Ricans',
    ],
    'keywords' => [
       'rican',
    ],
  ],
  'CU' => [
    'name' => 'Cuba',
    'completeName' => 'Republic of Cuba',
    'demonyms' => [
       'Cubans',
    ],
    'keywords' => [
       'cuban',
    ],
  ],
  'CV' => [
    'name' => 'Cabo Verde',
    'completeName' => 'Republic of Cabo Verde',
    'demonyms' => [
       'Cape Verdeans',
    ],
    'keywords' => [
       'verdean',
    ],
  ],
  'CW' => [
    'name' => 'Curaçao',
    'completeName' => 'Country of Curaçao',
    'demonyms' => [
       'Curaçaoans',
    ],
    'keywords' => [
       'abc',
       'islands',
       'curacaoan',
    ],
  ],
  'CX' => [
    'name' => 'Christmas Island',
    'completeName' => 'Christmas Island',
    'demonyms' => [
       'Christmas Islanders',
    ],
    'keywords' => [
       'kiritimati',
    ],
  ],
  'CY' => [
    'name' => 'Cyprus',
    'completeName' => 'Republic of Cyprus',
    'demonyms' => [
       'Cypriots',
    ],
    'keywords' => [
       'cypriot',
    ],
  ],
  'CZ' => [
    'name' => 'Czech Republic',
    'completeName' => 'Czech Republic',
    'demonyms' => [
       'Czechs',
    ],
    'keywords' => [
    ],
  ],
  'DE' => [
    'name' => 'Germany',
    'completeName' => 'Federal Republic of Germany',
    'demonyms' => [
       'Germans',
    ],
    'keywords' => [
       'german',
    ],
  ],
  'DJ' => [
    'name' => 'Djibouti',
    'completeName' => 'Republic of Djibouti',
    'demonyms' => [
       'Djiboutians',
    ],
    'keywords' => [
       'djiboutian',
    ],
  ],
  'DK' => [
    'name' => 'Denmark',
    'completeName' => 'Kingdom of Denmark',
    'demonyms' => [
       'Danes',
    ],
    'keywords' => [
       'danish',
    ],
  ],
  'DM' => [
    'name' => 'Dominica',
    'completeName' => 'Commonwealth of Dominica',
    'demonyms' => [
       'Dominicans',
    ],
    'keywords' => [
       'dominican',
    ],
  ],
  'DO' => [
    'name' => 'Dominican Republic',
    'completeName' => 'Dominican Republic',
    'demonyms' => [
       'Dominicans',
    ],
    'keywords' => [
    ],
  ],
  'DZ' => [
    'name' => 'Algeria',
    'completeName' => 'People\'s Democratic Republic of Algeria',
    'demonyms' => [
       'Algerians',
    ],
    'keywords' => [
       'algerian',
    ],
  ],
  'EC' => [
    'name' => 'Ecuador',
    'completeName' => 'Republic of Ecuador',
    'demonyms' => [
       'Ecuadorians',
    ],
    'keywords' => [
       'ecuadorian',
    ],
  ],
  'EE' => [
    'name' => 'Estonia',
    'completeName' => 'Republic of Estonia',
    'demonyms' => [
       'Estonians',
    ],
    'keywords' => [
       'estonian',
    ],
  ],
  'EG' => [
    'name' => 'Egypt',
    'completeName' => 'Arab Republic of Egypt',
    'demonyms' => [
       'Egyptians',
    ],
    'keywords' => [
       'egyptian',
    ],
  ],
  'EH' => [
    'name' => 'Western Sahara',
    'completeName' => 'Sahrawi Arab Democratic Republic',
    'demonyms' => [
       'Sahrawis',
       'Western Saharans',
    ],
    'keywords' => [
    ],
  ],
  'ER' => [
    'name' => 'Eritrea',
    'completeName' => 'State of Eritrea',
    'demonyms' => [
       'Eritreans',
    ],
    'keywords' => [
       'eritrean',
    ],
  ],
  'ES' => [
    'name' => 'Spain',
    'completeName' => 'Kingdom of Spain',
    'demonyms' => [
       'Spaniards',
    ],
    'keywords' => [
       'iberia',
       'iberian',
       'peninsula',
       'spanish',
    ],
  ],
  'ET' => [
    'name' => 'Ethiopia',
    'completeName' => 'Federal Democratic Republic of Ethiopia',
    'demonyms' => [
       'Ethiopians',
    ],
    'keywords' => [
       'ethiopian',
    ],
  ],
  'FI' => [
    'name' => 'Finland',
    'completeName' => 'Republic of Finland',
    'demonyms' => [
       'Finns',
    ],
    'keywords' => [
       'finnish',
    ],
  ],
  'FJ' => [
    'name' => 'Fiji',
    'completeName' => 'Republic of Fiji',
    'demonyms' => [
       'Fijians',
    ],
    'keywords' => [
       'fijian',
    ],
  ],
  'FK' => [
    'name' => 'Falkland Islands',
    'completeName' => 'Falkland Islands',
    'demonyms' => [
       'Falkland Islanders',
    ],
    'keywords' => [
       'falklandian',
       'falklandic',
       'falklander',
       'falklandish',
    ],
  ],
  'FM' => [
    'name' => 'Micronesia (Federated States of)',
    'completeName' => 'Federated States of Micronesia',
    'demonyms' => [
       'Micronesians',
    ],
    'keywords' => [
       'com',
       'micronesian',
    ],
  ],
  'FO' => [
    'name' => 'Faroe Islands',
    'completeName' => 'Fær Øer',
    'demonyms' => [
       'Faroese',
    ],
    'keywords' => [
    ],
  ],
  'FR' => [
    'name' => 'France',
    'completeName' => 'French Republic',
    'demonyms' => [
       'French',
    ],
    'keywords' => [
    ],
  ],
  'GA' => [
    'name' => 'Gabon',
    'completeName' => 'Gabonese Republic',
    'demonyms' => [
       'Gabonese',
    ],
    'keywords' => [
    ],
  ],
  'GB' => [
    'name' => 'United Kingdom',
    'completeName' => 'United Kingdom of Great Britain and Northern Ireland',
    'demonyms' => [
       'British',
       'English',
       'Scottish',
       'Welsh',
       'Irish',
       'Northern Irish',
    ],
    'keywords' => [
       'uk',
       'gb',
       'ukgb',
       'eng',
       'nir',
       'sct',
       'wls',
       'cym',
       'eaw',
       'gbn',
       'ukm',
       'isles',
       'caledonia',
       'england',
       'britannia',
       'albion',
       'scotland',
       'wales',
       'alba',
       'cymru',
       'ulster',
       'britons',
    ],
  ],
  'GD' => [
    'name' => 'Grenada',
    'completeName' => 'Grenada',
    'demonyms' => [
       'Grenadians',
    ],
    'keywords' => [
       'grenadian',
    ],
  ],
  'GE' => [
    'name' => 'Georgia',
    'completeName' => 'Republic of Georgia',
    'demonyms' => [
       'Georgians',
    ],
    'keywords' => [
       'georgian',
    ],
  ],
  'GF' => [
    'name' => 'French Guiana',
    'completeName' => 'Department of French Guiana',
    'demonyms' => [
       'French Guianese',
    ],
    'keywords' => [
       'guyana',
       'dom',
    ],
  ],
  'GG' => [
    'name' => 'Guernsey',
    'completeName' => 'Bailiwick of Guernsey',
    'demonyms' => [
       'Channel Islanders',
       'Guernsey Islanders',
    ],
    'keywords' => [
    ],
  ],
  'GH' => [
    'name' => 'Ghana',
    'completeName' => 'Republic of Ghana',
    'demonyms' => [
       'Ghanaians',
    ],
    'keywords' => [
       'ghanaian',
    ],
  ],
  'GI' => [
    'name' => 'Gibraltar',
    'completeName' => 'Gibraltar',
    'demonyms' => [
       'Gibraltarians',
    ],
    'keywords' => [
    ],
  ],
  'GL' => [
    'name' => 'Greenland',
    'completeName' => 'Greenland',
    'demonyms' => [
       'Greenlanders',
    ],
    'keywords' => [
       'inuit',
       'greenlandic',
    ],
  ],
  'GM' => [
    'name' => 'Gambia',
    'completeName' => 'Republic of The Gambia',
    'demonyms' => [
       'Gambians',
    ],
    'keywords' => [
       'gambian',
    ],
  ],
  'GN' => [
    'name' => 'Guinea',
    'completeName' => 'Republic of Guinea',
    'demonyms' => [
       'Guineans',
    ],
    'keywords' => [
       'conakry',
       'guinean',
    ],
  ],
  'GP' => [
    'name' => 'Guadeloupe',
    'completeName' => 'Department of Guadeloupe',
    'demonyms' => [
       'Guadeloupeans',
    ],
    'keywords' => [
       'dom',
    ],
  ],
  'GQ' => [
    'name' => 'Equatorial Guinea',
    'completeName' => 'Republic of Equatorial Guinea',
    'demonyms' => [
       'Equatorial Guineans',
    ],
    'keywords' => [
       'guinean',
    ],
  ],
  'GR' => [
    'name' => 'Greece',
    'completeName' => 'Hellenic Republic',
    'demonyms' => [
       'Greeks',
    ],
    'keywords' => [
       'greek',
    ],
  ],
  'GS' => [
    'name' => 'South Georgia and the South Sandwich Islands',
    'completeName' => 'South Georgia and the South Sandwich Islands',
    'demonyms' => [
       'South Georgians',
       'South Sandwich Islanders',
    ],
    'keywords' => [
       'georgian',
    ],
  ],
  'GT' => [
    'name' => 'Guatemala',
    'completeName' => 'Republic of Guatemala',
    'demonyms' => [
       'Guatemalans',
    ],
    'keywords' => [
       'guatemalan',
    ],
  ],
  'GU' => [
    'name' => 'Guam',
    'completeName' => 'Guam',
    'demonyms' => [
       'Guamanians',
    ],
    'keywords' => [
       'guamanian',
    ],
  ],
  'GW' => [
    'name' => 'Guinea-Bissau',
    'completeName' => 'Republic of Guinea-Bissau',
    'demonyms' => [
       'Bissau-Guineans',
    ],
    'keywords' => [
       'portuguese',
       'bissauan',
       'bissauans',
    ],
  ],
  'GY' => [
    'name' => 'Guyana',
    'completeName' => 'Co-operative Republic of Guyana',
    'demonyms' => [
       'Guyanese',
    ],
    'keywords' => [
    ],
  ],
  'HK' => [
    'name' => 'Hong Kong',
    'completeName' => 'Hong Kong Special Administrative Region of the People\'s Republic of China',
    'demonyms' => [
       'Hong Kongers',
       'Hongkongers',
    ],
    'keywords' => [
       'kongese',
       'hongkongish',
    ],
  ],
  'HM' => [
    'name' => 'Heard Island and McDonald Islands',
    'completeName' => 'Territory of Heard Island and McDonald Islands',
    'demonyms' => [
    ],
    'keywords' => [
       'heardian',
       'heardians',
    ],
  ],
  'HN' => [
    'name' => 'Honduras',
    'completeName' => 'Republic of Honduras',
    'demonyms' => [
       'Hondurans',
    ],
    'keywords' => [
       'honduran',
    ],
  ],
  'HR' => [
    'name' => 'Croatia',
    'completeName' => 'Republic of Croatia',
    'demonyms' => [
       'Croatians',
    ],
    'keywords' => [
       'croatian',
    ],
  ],
  'HT' => [
    'name' => 'Haiti',
    'completeName' => 'Republic of Haiti',
    'demonyms' => [
       'Haitians',
    ],
    'keywords' => [
       'haitian',
    ],
  ],
  'HU' => [
    'name' => 'Hungary',
    'completeName' => 'Hungary',
    'demonyms' => [
       'Hungarians',
    ],
    'keywords' => [
       'hungarian',
    ],
  ],
  'ID' => [
    'name' => 'Indonesia',
    'completeName' => 'Republic of Indonesia',
    'demonyms' => [
       'Indonesians',
    ],
    'keywords' => [
       'portuguese',
       'timor',
       'indonesian',
    ],
  ],
  'IE' => [
    'name' => 'Ireland',
    'completeName' => 'Republic of Ireland',
    'demonyms' => [
       'Irish',
    ],
    'keywords' => [
       'eire',
    ],
  ],
  'IL' => [
    'name' => 'Israel',
    'completeName' => 'State of Israel',
    'demonyms' => [
       'Israelis',
    ],
    'keywords' => [
       'israeli',
    ],
  ],
  'IM' => [
    'name' => 'Isle of Man',
    'completeName' => 'British islands Isle of Man',
    'demonyms' => [
       'Manx',
    ],
    'keywords' => [
       'mann',
    ],
  ],
  'IN' => [
    'name' => 'India',
    'completeName' => 'Republic of India',
    'demonyms' => [
       'Indians',
    ],
    'keywords' => [
       'indian',
    ],
  ],
  'IO' => [
    'name' => 'British Indian Ocean Territory',
    'completeName' => 'British Indian Ocean Territory',
    'demonyms' => [
       'British Indians',
    ],
    'keywords' => [
       'chagos',
       'biot',
       'oceanic',
    ],
  ],
  'IQ' => [
    'name' => 'Iraq',
    'completeName' => 'Republic of Iraq',
    'demonyms' => [
       'Iraqis',
    ],
    'keywords' => [
       'mesopotamia',
       'iraqi',
    ],
  ],
  'IR' => [
    'name' => 'Iran',
    'completeName' => 'Islamic Republic of Iran',
    'demonyms' => [
       'Iranians',
    ],
    'keywords' => [
       'persia',
       'persian',
       'persians',
       'iranian',
    ],
  ],
  'IS' => [
    'name' => 'Iceland',
    'completeName' => 'Republic of Iceland',
    'demonyms' => [
       'Icelanders',
    ],
    'keywords' => [
       'icelandic',
    ],
  ],
  'IT' => [
    'name' => 'Italy',
    'completeName' => 'Italian Republic',
    'demonyms' => [
       'Italians',
    ],
    'keywords' => [
    ],
  ],
  'JE' => [
    'name' => 'Jersey',
    'completeName' => 'Bailiwick of Jersey',
    'demonyms' => [
       'Channel Islanders',
       'Jersey Islanders',
    ],
    'keywords' => [
       'norman',
       'islands',
    ],
  ],
  'JM' => [
    'name' => 'Jamaica',
    'completeName' => 'Jamaica',
    'demonyms' => [
       'Jamaicans',
    ],
    'keywords' => [
       'jamaican',
    ],
  ],
  'JO' => [
    'name' => 'Jordan',
    'completeName' => 'Hashemite Kingdom of Jordan',
    'demonyms' => [
       'Jordanians',
    ],
    'keywords' => [
       'jordanian',
    ],
  ],
  'JP' => [
    'name' => 'Japan',
    'completeName' => 'Japan',
    'demonyms' => [
       'Japanese',
    ],
    'keywords' => [
       'nippon',
    ],
  ],
  'KE' => [
    'name' => 'Kenya',
    'completeName' => 'Republic of Kenya',
    'demonyms' => [
       'Kenyans',
    ],
    'keywords' => [
       'kenyan',
    ],
  ],
  'KG' => [
    'name' => 'Kyrgyzstan',
    'completeName' => 'Kyrgyz Republic',
    'demonyms' => [
       'Kyrgyz',
    ],
    'keywords' => [
       'kyrgyzstani',
       'kyrgyzstanis',
    ],
  ],
  'KH' => [
    'name' => 'Cambodia',
    'completeName' => 'Kingdom of Cambodia',
    'demonyms' => [
       'Cambodians',
    ],
    'keywords' => [
       'cambodian',
    ],
  ],
  'KI' => [
    'name' => 'Kiribati',
    'completeName' => 'Republic of Kiribati',
    'demonyms' => [
       'I-Kiribati',
    ],
    'keywords' => [
    ],
  ],
  'KM' => [
    'name' => 'Comoros',
    'completeName' => 'Union of the Comoros',
    'demonyms' => [
       'Comorians',
    ],
    'keywords' => [
       'comoran',
    ],
  ],
  'KN' => [
    'name' => 'Saint Kitts and Nevis',
    'completeName' => 'Federation of Saint Kitts and Nevis',
    'demonyms' => [
       'Kittitians',
       'Nevisians',
    ],
    'keywords' => [
       'kittitian',
       'nevisian',
    ],
  ],
  'KP' => [
    'name' => 'Korea (Democratic People\'s Republic of)',
    'completeName' => 'Democratic People\'s Republic of Korea',
    'demonyms' => [
       'North Koreans',
    ],
    'keywords' => [
       'korean',
    ],
  ],
  'KR' => [
    'name' => 'Korea (Republic of)',
    'completeName' => 'Republic of Korea',
    'demonyms' => [
       'South Koreans',
    ],
    'keywords' => [
       'korean',
    ],
  ],
  'KW' => [
    'name' => 'Kuwait',
    'completeName' => 'State of Kuwait',
    'demonyms' => [
       'Kuwaitis',
    ],
    'keywords' => [
       'kuwaiti',
    ],
  ],
  'KY' => [
    'name' => 'Cayman Islands',
    'completeName' => 'Cayman Islands',
    'demonyms' => [
       'Caymanians',
    ],
    'keywords' => [
       'caymanian',
    ],
  ],
  'KZ' => [
    'name' => 'Kazakhstan',
    'completeName' => 'Republic of Kazakhstan',
    'demonyms' => [
       'Kazakhs',
    ],
    'keywords' => [
       'kazakhstani',
    ],
  ],
  'LA' => [
    'name' => 'Lao People\'s Democratic Republic',
    'completeName' => 'Lao People\'s Democratic Republic',
    'demonyms' => [
       'Laotians',
    ],
    'keywords' => [
       'laotian',
    ],
  ],
  'LB' => [
    'name' => 'Lebanon',
    'completeName' => 'Lebanese Republic',
    'demonyms' => [
       'Lebanese',
    ],
    'keywords' => [
    ],
  ],
  'LC' => [
    'name' => 'Saint Lucia',
    'completeName' => 'Saint Lucia',
    'demonyms' => [
       'Saint Lucians',
    ],
    'keywords' => [
       'lucian',
    ],
  ],
  'LI' => [
    'name' => 'Liechtenstein',
    'completeName' => 'Principality of Liechtenstein',
    'demonyms' => [
       'Liechtensteiners',
    ],
    'keywords' => [
    ],
  ],
  'LK' => [
    'name' => 'Sri Lanka',
    'completeName' => 'Democratic Socialist Republic of Sri Lanka',
    'demonyms' => [
       'Sri Lankans',
    ],
    'keywords' => [
       'ceylon',
       'lankan',
    ],
  ],
  'LR' => [
    'name' => 'Liberia',
    'completeName' => 'Republic of Liberia',
    'demonyms' => [
       'Liberians',
    ],
    'keywords' => [
       'liberian',
    ],
  ],
  'LS' => [
    'name' => 'Lesotho',
    'completeName' => 'Kingdom of Lesotho',
    'demonyms' => [
       'Basotho',
    ],
    'keywords' => [
    ],
  ],
  'LT' => [
    'name' => 'Lithuania',
    'completeName' => 'Republic of Lithuania',
    'demonyms' => [
       'Lithuanians',
    ],
    'keywords' => [
       'lithuanian',
    ],
  ],
  'LU' => [
    'name' => 'Luxembourg',
    'completeName' => 'Grand Duchy of Luxembourg',
    'demonyms' => [
       'Luxembourgers',
    ],
    'keywords' => [
    ],
  ],
  'LV' => [
    'name' => 'Latvia',
    'completeName' => 'Republic of Latvia',
    'demonyms' => [
       'Latvians',
    ],
    'keywords' => [
       'latvian',
    ],
  ],
  'LY' => [
    'name' => 'Libya',
    'completeName' => 'State of Libya',
    'demonyms' => [
       'Libyans',
    ],
    'keywords' => [
       'libyan',
    ],
  ],
  'MA' => [
    'name' => 'Morocco',
    'completeName' => 'Kingdom of Morocco',
    'demonyms' => [
       'Moroccans',
    ],
    'keywords' => [
       'moroccan',
    ],
  ],
  'MC' => [
    'name' => 'Monaco',
    'completeName' => 'Principality of Monaco',
    'demonyms' => [
       'Monégasque',
    ],
    'keywords' => [
       'monegasques',
    ],
  ],
  'MD' => [
    'name' => 'Moldova',
    'completeName' => 'Republic of Moldova',
    'demonyms' => [
       'Moldovans',
    ],
    'keywords' => [
       'moldovan',
    ],
  ],
  'ME' => [
    'name' => 'Montenegro',
    'completeName' => 'Montenegro',
    'demonyms' => [
       'Montenegrins',
    ],
    'keywords' => [
       'montenegrin',
    ],
  ],
  'MF' => [
    'name' => 'Saint Martin (French part)',
    'completeName' => 'Overseas Collectivity of Saint Martin',
    'demonyms' => [
       'Saint-Martinois',
    ],
    'keywords' => [
       'com',
       'martinoise',
    ],
  ],
  'MG' => [
    'name' => 'Madagascar',
    'completeName' => 'Republic of Madagascar',
    'demonyms' => [
       'Malagasy',
    ],
    'keywords' => [
    ],
  ],
  'MH' => [
    'name' => 'Marshall Islands',
    'completeName' => 'Republic of the Marshall Islands',
    'demonyms' => [
       'Marshallese',
    ],
    'keywords' => [
    ],
  ],
  'MK' => [
    'name' => 'North Macedonia',
    'completeName' => 'Republic of North Macedonia',
    'demonyms' => [
       'Macedonians',
    ],
    'keywords' => [
       'macedonian',
    ],
  ],
  'ML' => [
    'name' => 'Mali',
    'completeName' => 'Republic of Mali',
    'demonyms' => [
       'Malians',
    ],
    'keywords' => [
       'malian',
    ],
  ],
  'MM' => [
    'name' => 'Myanmar',
    'completeName' => 'Republic of the Union of Myanmar',
    'demonyms' => [
       'Burmese',
    ],
    'keywords' => [
       'burma',
    ],
  ],
  'MN' => [
    'name' => 'Mongolia',
    'completeName' => 'Mongolia',
    'demonyms' => [
       'Mongolians',
    ],
    'keywords' => [
       'mongolian',
    ],
  ],
  'MO' => [
    'name' => 'Macau',
    'completeName' => 'Macau Special Administrative Region of the People\'s Republic of China',
    'demonyms' => [
       'Macanese',
    ],
    'keywords' => [
    ],
  ],
  'MP' => [
    'name' => 'Northern Mariana Islands',
    'completeName' => 'Commonwealth of the Northern Mariana Islands',
    'demonyms' => [
       'Northern Mariana Islanders',
    ],
    'keywords' => [
       'marianan',
    ],
  ],
  'MQ' => [
    'name' => 'Martinique',
    'completeName' => 'Territorial Collectivity of Martinique',
    'demonyms' => [
       'Martiniquais',
    ],
    'keywords' => [
       'dom',
    ],
  ],
  'MR' => [
    'name' => 'Mauritania',
    'completeName' => 'Islamic Republic of Mauritania',
    'demonyms' => [
       'Mauritanians',
    ],
    'keywords' => [
       'mauritanian',
    ],
  ],
  'MS' => [
    'name' => 'Montserrat',
    'completeName' => 'Colony of Montserrat',
    'demonyms' => [
       'Montserratians',
    ],
    'keywords' => [
       'montserratian',
    ],
  ],
  'MT' => [
    'name' => 'Malta',
    'completeName' => 'Republic of Malta',
    'demonyms' => [
       'Maltese',
    ],
    'keywords' => [
    ],
  ],
  'MU' => [
    'name' => 'Mauritius',
    'completeName' => 'Republic of Mauritius',
    'demonyms' => [
       'Mauritians',
    ],
    'keywords' => [
       'mauritian',
    ],
  ],
  'MV' => [
    'name' => 'Maldives',
    'completeName' => 'Republic of Maldives',
    'demonyms' => [
       'Maldivians',
    ],
    'keywords' => [
       'maldivian',
    ],
  ],
  'MW' => [
    'name' => 'Malawi',
    'completeName' => 'Republic of Malawi',
    'demonyms' => [
       'Malawians',
    ],
    'keywords' => [
       'malawian',
    ],
  ],
  'MX' => [
    'name' => 'Mexico',
    'completeName' => 'United Mexican States',
    'demonyms' => [
       'Mexicans',
    ],
    'keywords' => [
    ],
  ],
  'MY' => [
    'name' => 'Malaysia',
    'completeName' => 'Malaysia',
    'demonyms' => [
       'Malaysians',
    ],
    'keywords' => [
       'malaysian',
    ],
  ],
  'MZ' => [
    'name' => 'Mozambique',
    'completeName' => 'Republic of Mozambique',
    'demonyms' => [
       'Mozambicans',
    ],
    'keywords' => [
       'mozambican',
    ],
  ],
  'NA' => [
    'name' => 'Namibia',
    'completeName' => 'Republic of Namibia',
    'demonyms' => [
       'Namibians',
    ],
    'keywords' => [
       'namibian',
    ],
  ],
  'NC' => [
    'name' => 'New Caledonia',
    'completeName' => 'Government of New Caledonia',
    'demonyms' => [
       'New Caledonians',
    ],
    'keywords' => [
       'com',
       'caledonian',
    ],
  ],
  'NE' => [
    'name' => 'Niger',
    'completeName' => 'Republic of Niger',
    'demonyms' => [
       'Nigeriens',
    ],
    'keywords' => [
       'nigerien',
    ],
  ],
  'NF' => [
    'name' => 'Norfolk Island',
    'completeName' => 'Territory of Norfolk Island',
    'demonyms' => [
       'Norfolk Islanders',
    ],
    'keywords' => [
    ],
  ],
  'NG' => [
    'name' => 'Nigeria',
    'completeName' => 'Federal Republic of Nigeria',
    'demonyms' => [
       'Nigerians',
    ],
    'keywords' => [
       'nigerian',
    ],
  ],
  'NI' => [
    'name' => 'Nicaragua',
    'completeName' => 'Republic of Nicaragua',
    'demonyms' => [
       'Nicaraguans',
    ],
    'keywords' => [
       'nicaraguan',
    ],
  ],
  'NL' => [
    'name' => 'Netherlands',
    'completeName' => 'Kingdom of the Netherlands',
    'demonyms' => [
       'Dutch',
    ],
    'keywords' => [
       'holland',
    ],
  ],
  'NO' => [
    'name' => 'Norway',
    'completeName' => 'Kingdom of Norway',
    'demonyms' => [
       'Norwegians',
    ],
    'keywords' => [
       'norwegian',
    ],
  ],
  'NP' => [
    'name' => 'Nepal',
    'completeName' => 'Federal Democratic Republic of Nepal',
    'demonyms' => [
       'Nepalis',
    ],
    'keywords' => [
       'nepali',
    ],
  ],
  'NR' => [
    'name' => 'Nauru',
    'completeName' => 'Republic of Nauru',
    'demonyms' => [
       'Nauruans',
    ],
    'keywords' => [
       'nauruan',
    ],
  ],
  'NU' => [
    'name' => 'Niue',
    'completeName' => 'Niue',
    'demonyms' => [
       'Niueans',
    ],
    'keywords' => [
       'niuean',
    ],
  ],
  'NZ' => [
    'name' => 'New Zealand',
    'completeName' => 'New Zealand',
    'demonyms' => [
       'New Zealanders',
    ],
    'keywords' => [
       'zealandish',
       'zealander',
       'kiwi',
    ],
  ],
  'OM' => [
    'name' => 'Oman',
    'completeName' => 'Sultanate of Oman',
    'demonyms' => [
       'Omanis',
    ],
    'keywords' => [
       'omani',
    ],
  ],
  'PA' => [
    'name' => 'Panama',
    'completeName' => 'Republic of Panama',
    'demonyms' => [
       'Panamanians',
    ],
    'keywords' => [
       'panamanian',
    ],
  ],
  'PE' => [
    'name' => 'Peru',
    'completeName' => 'Republic of Peru',
    'demonyms' => [
       'Peruvians',
    ],
    'keywords' => [
       'peruvian',
    ],
  ],
  'PF' => [
    'name' => 'French Polynesia',
    'completeName' => 'Overseas Collectivity of French Polynesia',
    'demonyms' => [
       'French Polynesians',
    ],
    'keywords' => [
       'com',
       'polynesian',
    ],
  ],
  'PG' => [
    'name' => 'Papua New Guinea',
    'completeName' => 'Independent State of Papua New Guinea',
    'demonyms' => [
       'Papua New Guineans',
    ],
    'keywords' => [
       'guinean',
    ],
  ],
  'PH' => [
    'name' => 'Philippines',
    'completeName' => 'Republic of the Philippines',
    'demonyms' => [
       'Filipinos',
    ],
    'keywords' => [
       'filipino',
    ],
  ],
  'PK' => [
    'name' => 'Pakistan',
    'completeName' => 'Islamic Republic of Pakistan',
    'demonyms' => [
       'Pakistanis',
    ],
    'keywords' => [
       'pakistani',
    ],
  ],
  'PL' => [
    'name' => 'Poland',
    'completeName' => 'Republic of Poland',
    'demonyms' => [
       'Poles',
    ],
    'keywords' => [
       'polish',
    ],
  ],
  'PM' => [
    'name' => 'Saint Pierre and Miquelon',
    'completeName' => 'Overseas Collectivity of Saint-Pierre and Miquelon',
    'demonyms' => [
       'Saint-Pierrais',
       'Miquelonnais',
    ],
    'keywords' => [
       'com',
       'or',
    ],
  ],
  'PN' => [
    'name' => 'Pitcairn',
    'completeName' => 'Pitcairn, Henderson, Ducie and Oeno Islands',
    'demonyms' => [
       'Pitcairn Islanders',
    ],
    'keywords' => [
       'island',
    ],
  ],
  'PR' => [
    'name' => 'Puerto Rico',
    'completeName' => 'Commonwealth of Puerto Rico',
    'demonyms' => [
       'Puerto Ricans',
    ],
    'keywords' => [
       'rican',
    ],
  ],
  'PS' => [
    'name' => 'Palestine',
    'completeName' => 'State of Palestine',
    'demonyms' => [
       'Palestinians',
    ],
    'keywords' => [
       'palestinian',
    ],
  ],
  'PT' => [
    'name' => 'Portugal',
    'completeName' => 'Portuguese Republic',
    'demonyms' => [
       'Portuguese',
    ],
    'keywords' => [
    ],
  ],
  'PW' => [
    'name' => 'Palau',
    'completeName' => 'Republic of Palau',
    'demonyms' => [
       'Palauans',
    ],
    'keywords' => [
       'palauan',
    ],
  ],
  'PY' => [
    'name' => 'Paraguay',
    'completeName' => 'Republic of Paraguay',
    'demonyms' => [
       'Paraguayans',
    ],
    'keywords' => [
       'paraguayan',
    ],
  ],
  'QA' => [
    'name' => 'Qatar',
    'completeName' => 'State of Qatar',
    'demonyms' => [
       'Qataris',
    ],
    'keywords' => [
       'qatari',
    ],
  ],
  'RE' => [
    'name' => 'The Réunion',
    'completeName' => 'Department of Réunion',
    'demonyms' => [
       'Réunionnais',
    ],
    'keywords' => [
       'dom',
       'reunionese',
    ],
  ],
  'RO' => [
    'name' => 'Romania',
    'completeName' => 'Romania',
    'demonyms' => [
       'Romanians',
    ],
    'keywords' => [
       'romanian',
    ],
  ],
  'RS' => [
    'name' => 'Serbia',
    'completeName' => 'Republic of Serbia',
    'demonyms' => [
       'Serbians',
    ],
    'keywords' => [
       'serbian',
       'serbs',
    ],
  ],
  'RU' => [
    'name' => 'Russian Federation',
    'completeName' => 'Russian Federation',
    'demonyms' => [
       'Russians',
    ],
    'keywords' => [
    ],
  ],
  'RW' => [
    'name' => 'Rwanda',
    'completeName' => 'Republic of Rwanda',
    'demonyms' => [
       'Rwandans',
    ],
    'keywords' => [
       'rwandan',
    ],
  ],
  'SA' => [
    'name' => 'Saudi Arabia',
    'completeName' => 'Kingdom of Saudi Arabia',
    'demonyms' => [
       'Saudi Arabians',
    ],
    'keywords' => [
       'arabian',
    ],
  ],
  'SB' => [
    'name' => 'Solomon Islands',
    'completeName' => 'Solomon Islands',
    'demonyms' => [
       'Solomon Islanders',
    ],
    'keywords' => [
    ],
  ],
  'SC' => [
    'name' => 'Seychelles',
    'completeName' => 'Republic of Seychelles',
    'demonyms' => [
       'Seychellois',
    ],
    'keywords' => [
    ],
  ],
  'SD' => [
    'name' => 'Sudan',
    'completeName' => 'Republic of the Sudan',
    'demonyms' => [
       'Sudanese',
    ],
    'keywords' => [
    ],
  ],
  'SE' => [
    'name' => 'Sweden',
    'completeName' => 'Kingdom of Sweden',
    'demonyms' => [
       'Swedes',
    ],
    'keywords' => [
       'swedish',
    ],
  ],
  'SG' => [
    'name' => 'Singapore',
    'completeName' => 'Republic of Singapore',
    'demonyms' => [
       'Singaporeans',
    ],
    'keywords' => [
       'singaporean',
    ],
  ],
  'SH' => [
    'name' => 'Saint Helena, Ascension and Tristan da Cunha',
    'completeName' => 'Saint Helena, Ascension and Tristan da Cunha',
    'demonyms' => [
       'Saint Helenians',
    ],
    'keywords' => [
       'helenian',
    ],
  ],
  'SI' => [
    'name' => 'Slovenia',
    'completeName' => 'Republic of Slovenia',
    'demonyms' => [
       'Slovenes',
    ],
    'keywords' => [
       'slovenian',
       'slovenians',
    ],
  ],
  'SJ' => [
    'name' => 'Svalbard and Jan Mayen',
    'completeName' => 'Svalbard and Jan Mayen Islands',
    'demonyms' => [
       'Svalbard and Jan Mayen Islanders',
    ],
    'keywords' => [
    ],
  ],
  'SK' => [
    'name' => 'Slovakia',
    'completeName' => 'Slovak Republic',
    'demonyms' => [
       'Slovaks',
    ],
    'keywords' => [
    ],
  ],
  'SL' => [
    'name' => 'Sierra Leone',
    'completeName' => 'Republic of Sierra Leone',
    'demonyms' => [
       'Sierra Leoneans',
    ],
    'keywords' => [
       'leonean',
    ],
  ],
  'SM' => [
    'name' => 'San Marino',
    'completeName' => 'Republic of San Marino',
    'demonyms' => [
       'Sammarinese',
    ],
    'keywords' => [
       'sanmarinese',
    ],
  ],
  'SN' => [
    'name' => 'Senegal',
    'completeName' => 'Republic of Senegal',
    'demonyms' => [
       'Senegalese',
    ],
    'keywords' => [
    ],
  ],
  'SO' => [
    'name' => 'Somalia',
    'completeName' => 'Federal Republic of Somalia',
    'demonyms' => [
       'Somalis',
    ],
    'keywords' => [
       'somali',
    ],
  ],
  'SR' => [
    'name' => 'Suriname',
    'completeName' => 'Republic of Suriname',
    'demonyms' => [
       'Surinamese',
    ],
    'keywords' => [
    ],
  ],
  'SS' => [
    'name' => 'South Sudan',
    'completeName' => 'Republic of South Sudan',
    'demonyms' => [
       'South Sudanese',
    ],
    'keywords' => [
    ],
  ],
  'ST' => [
    'name' => 'Sao Tome and Principe',
    'completeName' => 'Democratic Republic of São Tomé and Príncipe',
    'demonyms' => [
       'São Toméans',
    ],
    'keywords' => [
       'tomean',
    ],
  ],
  'SV' => [
    'name' => 'El Salvador',
    'completeName' => 'Republic of El Salvador',
    'demonyms' => [
       'Salvadorans',
    ],
    'keywords' => [
       'salvadoran',
    ],
  ],
  'SX' => [
    'name' => 'Sint Maarten',
    'completeName' => 'Sint Maarten',
    'demonyms' => [
       'Sint Maarteners',
    ],
    'keywords' => [
       'sss',
       'islands',
    ],
  ],
  'SY' => [
    'name' => 'Syrian Arab Republic',
    'completeName' => 'Syrian Arab Republic',
    'demonyms' => [
       'Syrians',
    ],
    'keywords' => [
    ],
  ],
  'SZ' => [
    'name' => 'Eswatini',
    'completeName' => 'Kingdom of Eswatini',
    'demonyms' => [
       'Swazis',
    ],
    'keywords' => [
       'swazi',
    ],
  ],
  'TC' => [
    'name' => 'Turks and Caicos Islands',
    'completeName' => 'Turks and Caicos Islands',
    'demonyms' => [
       'Turks and Caicos Islanders',
    ],
    'keywords' => [
       'island',
    ],
  ],
  'TD' => [
    'name' => 'Chad',
    'completeName' => 'Republic of Chad',
    'demonyms' => [
       'Chadians',
    ],
    'keywords' => [
       'chadian',
    ],
  ],
  'TF' => [
    'name' => 'French Southern Territories',
    'completeName' => 'French Southern and Antarctic Lands',
    'demonyms' => [
       'French Southern and Antarctic Lands',
    ],
    'keywords' => [
       'taaf',
    ],
  ],
  'TG' => [
    'name' => 'Togo',
    'completeName' => 'Togolese Republic',
    'demonyms' => [
       'Togolese',
    ],
    'keywords' => [
    ],
  ],
  'TH' => [
    'name' => 'Thailand',
    'completeName' => 'Kingdom of Thailand',
    'demonyms' => [
       'Thais',
    ],
    'keywords' => [
       'thai',
    ],
  ],
  'TJ' => [
    'name' => 'Tajikistan',
    'completeName' => 'Republic of Tajikistan',
    'demonyms' => [
       'Tajiks',
    ],
    'keywords' => [
       'tajikistani',
    ],
  ],
  'TK' => [
    'name' => 'Tokelau',
    'completeName' => 'Tokelau Islands',
    'demonyms' => [
       'Tokelauans',
    ],
    'keywords' => [
       'union',
       'tokelauan',
    ],
  ],
  'TL' => [
    'name' => 'East Timor',
    'completeName' => 'Democratic Republic of Timor-Leste',
    'demonyms' => [
       'East Timorese',
    ],
    'keywords' => [
    ],
  ],
  'TM' => [
    'name' => 'Turkmenistan',
    'completeName' => 'Turkmenistan',
    'demonyms' => [
       'Turkmen',
    ],
    'keywords' => [
       'turkmens',
    ],
  ],
  'TN' => [
    'name' => 'Tunisia',
    'completeName' => 'Republic of Tunisia',
    'demonyms' => [
       'Tunisians',
    ],
    'keywords' => [
       'tunisian',
    ],
  ],
  'TO' => [
    'name' => 'Tonga',
    'completeName' => 'Kingdom of Tonga',
    'demonyms' => [
       'Tongans',
    ],
    'keywords' => [
       'tongan',
    ],
  ],
  'TR' => [
    'name' => 'Turkey',
    'completeName' => 'Republic of Turkey',
    'demonyms' => [
       'Turks',
    ],
    'keywords' => [
       'turkish',
    ],
  ],
  'TT' => [
    'name' => 'Trinidad and Tobago',
    'completeName' => 'Republic of Trinidad and Tobago',
    'demonyms' => [
       'Trinidadians',
       'Tobagonians',
    ],
    'keywords' => [
       'trinidadian',
    ],
  ],
  'TV' => [
    'name' => 'Tuvalu',
    'completeName' => 'Tuvalu',
    'demonyms' => [
       'Tuvaluans',
    ],
    'keywords' => [
       'tuvaluan',
    ],
  ],
  'TW' => [
    'name' => 'Taiwan',
    'completeName' => 'Republic of China',
    'demonyms' => [
       'Taiwanese',
    ],
    'keywords' => [
       'formosa',
    ],
  ],
  'TZ' => [
    'name' => 'Tanzania, United Republic of',
    'completeName' => 'United Republic of Tanzania',
    'demonyms' => [
       'Tanzanians',
    ],
    'keywords' => [
       'tanzanian',
    ],
  ],
  'UA' => [
    'name' => 'Ukraine',
    'completeName' => 'Ukraine',
    'demonyms' => [
       'Ukrainians',
    ],
    'keywords' => [
       'little',
       'russia',
       'ukrainian',
    ],
  ],
  'UG' => [
    'name' => 'Uganda',
    'completeName' => 'Republic of Uganda',
    'demonyms' => [
       'Ugandans',
    ],
    'keywords' => [
       'ugandan',
    ],
  ],
  'UM' => [
    'name' => 'United States Minor Outlying Islands',
    'completeName' => 'United States Minor Outlying Islands',
    'demonyms' => [
    ],
    'keywords' => [
       'usmoi',
    ],
  ],
  'US' => [
    'name' => 'United States',
    'completeName' => 'United States of America',
    'demonyms' => [
       'Americans',
    ],
    'keywords' => [
       'vatican',
       'city',
       'state',
       'papal',
       'holy',
       'see',
       'apostolic',
       'american',
    ],
  ],
  'UY' => [
    'name' => 'Uruguay',
    'completeName' => 'Oriental Republic of Uruguay',
    'demonyms' => [
       'Uruguayans',
    ],
    'keywords' => [
       'uruguayan',
    ],
  ],
  'UZ' => [
    'name' => 'Uzbekistan',
    'completeName' => 'Republic of Uzbekistan',
    'demonyms' => [
       'Uzbeks',
    ],
    'keywords' => [
       'uzbekistani',
    ],
  ],
  'VA' => [
    'name' => 'Holy See',
    'completeName' => 'Vatican City State',
    'demonyms' => [
       'Vatican Citizens',
    ],
    'keywords' => [
    ],
  ],
  'VC' => [
    'name' => 'Saint Vincent and the Grenadines',
    'completeName' => 'Saint Vincent and the Grenadines',
    'demonyms' => [
       'Saint Vincentians',
       'Grenadines',
    ],
    'keywords' => [
       'vincentian',
    ],
  ],
  'VE' => [
    'name' => 'Venezuela',
    'completeName' => 'Bolivarian Republic of Venezuela',
    'demonyms' => [
       'Venezuelans',
    ],
    'keywords' => [
       'venezuelan',
    ],
  ],
  'VG' => [
    'name' => 'Virgin Islands (British)',
    'completeName' => 'British Virgin Islands',
    'demonyms' => [
       'British Virgin Islanders',
    ],
    'keywords' => [
    ],
  ],
  'VI' => [
    'name' => 'Virgin Islands (U.S.)',
    'completeName' => 'United States Virgin Islands',
    'demonyms' => [
       'United States Virgin Islanders',
    ],
    'keywords' => [
    ],
  ],
  'VN' => [
    'name' => 'Viet Nam',
    'completeName' => 'Socialist Republic of Vietnam',
    'demonyms' => [
       'Vietnamese',
    ],
    'keywords' => [
    ],
  ],
  'VU' => [
    'name' => 'Vanuatu',
    'completeName' => 'Republic of Vanuatu',
    'demonyms' => [
       'Ni-Vanuatu',
    ],
    'keywords' => [
       'vanuatuan',
       'vanuatuans',
    ],
  ],
  'WF' => [
    'name' => 'Wallis and Futuna',
    'completeName' => 'Overseas Collectivity of the Wallis and Futuna Islands',
    'demonyms' => [
       'Wallis and Futuna Islanders',
       'Wallisian-Futunan',
    ],
    'keywords' => [
       'alofi',
       'com',
    ],
  ],
  'WS' => [
    'name' => 'Samoa',
    'completeName' => 'Independent State of Samoa',
    'demonyms' => [
       'Samoans',
    ],
    'keywords' => [
       'samoan',
    ],
  ],
  'YE' => [
    'name' => 'Yemen',
    'completeName' => 'Republic of Yemen',
    'demonyms' => [
       'Yemenis',
    ],
    'keywords' => [
       'yemeni',
    ],
  ],
  'YT' => [
    'name' => 'Mayotte',
    'completeName' => 'Departmental Collectivity of Mayotte',
    'demonyms' => [
       'Mahorais',
    ],
    'keywords' => [
       'dom',
       'mahoran',
       'mahorans',
    ],
  ],
  'ZA' => [
    'name' => 'South Africa',
    'completeName' => 'Republic of South Africa',
    'demonyms' => [
       'South Africans',
    ],
    'keywords' => [
       'african',
    ],
  ],
  'ZM' => [
    'name' => 'Zambia',
    'completeName' => 'Republic of Zambia',
    'demonyms' => [
       'Zambians',
    ],
    'keywords' => [
       'zambian',
    ],
  ],
  'ZW' => [
    'name' => 'Zimbabwe',
    'completeName' => 'Republic of Zimbabwe',
    'demonyms' => [
       'Zimbabweans',
    ],
    'keywords' => [
       'zimbabwean',
    ],
  ],
];
