<?php
        
/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */
 
 
return [
    'CONV-G20' => [
        'name' => 'Group of Twenty (G20)'
    ],
    'CONV-G7' => [
        'name' => 'Group of Seven (G7)'
    ],
    'CONV-SCHENGEN' => [
        'name' => 'Schengen Area'
    ],
    'CONV-UNCAC' => [
        'name' => 'United Nations Convention Against Corruption (UNCAC)'
    ],
    'GEOG-AF' => [
        'name' => 'Africa'
    ],
    'GEOG-AF-NO' => [
        'name' => 'Northern Africa'
    ],
    'GEOG-AF-SS' => [
        'name' => 'Sub-Saharan Africa'
    ],
    'GEOG-AF-SS-EA' => [
        'name' => 'Eastern Africa'
    ],
    'GEOG-AF-SS-MD' => [
        'name' => 'Middle Africa'
    ],
    'GEOG-AF-SS-SO' => [
        'name' => 'Southern Africa'
    ],
    'GEOG-AF-SS-WE' => [
        'name' => 'Western Africa'
    ],
    'GEOG-AM' => [
        'name' => 'Americas'
    ],
    'GEOG-AM-LA' => [
        'name' => 'Latin America and the Caribbean'
    ],
    'GEOG-AM-LA-CA' => [
        'name' => 'Caribbean'
    ],
    'GEOG-AM-LA-CT' => [
        'name' => 'Central America'
    ],
    'GEOG-AM-LA-SO' => [
        'name' => 'South America'
    ],
    'GEOG-AM-NO' => [
        'name' => 'Northern America'
    ],
    'GEOG-AQ' => [
        'name' => 'Antartica'
    ],
    'GEOG-AS' => [
        'name' => 'Asia'
    ],
    'GEOG-AS-CT' => [
        'name' => 'Central Asia'
    ],
    'GEOG-AS-EA' => [
        'name' => 'Eastern Asia'
    ],
    'GEOG-AS-SE' => [
        'name' => 'South-eastern Asia'
    ],
    'GEOG-AS-SO' => [
        'name' => 'Southern Asia'
    ],
    'GEOG-AS-WE' => [
        'name' => 'Western Asia'
    ],
    'GEOG-EU' => [
        'name' => 'Europe'
    ],
    'GEOG-EU-EA' => [
        'name' => 'Eastern Europe'
    ],
    'GEOG-EU-NO' => [
        'name' => 'Northern Europe'
    ],
    'GEOG-EU-NO-CH' => [
        'name' => 'Channel Islands'
    ],
    'GEOG-EU-SO' => [
        'name' => 'Southern Europe'
    ],
    'GEOG-EU-WE' => [
        'name' => 'Western Europe'
    ],
    'GEOG-OC' => [
        'name' => 'Oceania'
    ],
    'GEOG-OC-AN' => [
        'name' => 'Australia and New Zealand'
    ],
    'GEOG-OC-ME' => [
        'name' => 'Melanesia'
    ],
    'GEOG-OC-MI' => [
        'name' => 'Micronesia'
    ],
    'GEOG-OC-PO' => [
        'name' => 'Polynesia'
    ],
    'ORGS-ACTO' => [
        'name' => 'Amazon Cooperation Treaty Organization (ACTO)'
    ],
    'ORGS-ASEAN' => [
        'name' => 'Association of Southeast Asian Nations (ASEAN)'
    ],
    'ORGS-AU' => [
        'name' => 'African Union (AU)'
    ],
    'ORGS-BRICS' => [
        'name' => 'BRICS'
    ],
    'ORGS-CIS' => [
        'name' => 'Commonwealth of Independent States (CIS)'
    ],
    'ORGS-COE' => [
        'name' => 'Council of Europe (CoE)'
    ],
    'ORGS-CSTO' => [
        'name' => 'Collective Security Treaty Organization (CSTO)'
    ],
    'ORGS-CWNAT' => [
        'name' => 'Commonwealth of the Nations'
    ],
    'ORGS-CWRLM' => [
        'name' => 'Commonwealth realm'
    ],
    'ORGS-EU' => [
        'name' => 'European Union (EU)'
    ],
    'ORGS-IBRD' => [
        'name' => 'International Bank for Reconstruction and Development (IBRD)'
    ],
    'ORGS-ICC' => [
        'name' => 'International Criminal Court (ICC)'
    ],
    'ORGS-ICSID' => [
        'name' => 'International Centre for Settlement of Investment Disputes (ICSID)'
    ],
    'ORGS-IDA' => [
        'name' => 'International Development Association (IDA)'
    ],
    'ORGS-IFC' => [
        'name' => 'International Finance Corporation (IFC)'
    ],
    'ORGS-IPOL' => [
        'name' => 'International Criminal Police Organization (Interpol)'
    ],
    'ORGS-MIGA' => [
        'name' => 'Multilateral Investment Guarantee Agency (MIGA)'
    ],
    'ORGS-NATO' => [
        'name' => 'North Atlantic Treaty Organization (NATO)'
    ],
    'ORGS-OAS' => [
        'name' => 'Organization of American States (OAS)'
    ],
    'ORGS-OECD' => [
        'name' => 'Organisation for Economic Co-operation and Development (OECD)'
    ],
    'ORGS-OPEC' => [
        'name' => 'Organization of the Petroleum Exporting Countries (OPEC)'
    ],
    'ORGS-OSCE' => [
        'name' => 'Organization for Security and Co-operation in Europe (OSCE)'
    ],
    'ORGS-SCO' => [
        'name' => 'Shanghai Cooperation Organisation (SCO)'
    ],
    'ORGS-UN' => [
        'name' => 'United Nations (UN)'
    ],
    'ORGS-WCO' => [
        'name' => 'World Customs Organization (WCO)'
    ],
    'ORGS-WTO' => [
        'name' => 'World Trade Organization (WTO)'
    ],
    'ZONE-EZ' => [
        'name' => 'Eurozone (EZ)'
    ]
];