<?php

/**
 * This file has been automatically generated by the `build` script in the `dev` section.
 * Any modifications you make will be overwritten.
 * To modify the parameters in this file, please follow these steps:
 * - Go to the `dev/origin` section.
 * - Modify the corresponding JSON file.
 * - Run the `build` script again from the root of this project using one of these commands:
 *   - `dev/build`
 *   - `sh dev/build`
 * For further and more detailed information, please read the README.md file in the dev section.
*/

return [
  'CONV-G20' => 'Group of Twenty (G20)',
  'CONV-G7' => 'Group of Seven (G7)',
  'CONV-SCHENGEN' => 'Schengen Area',
  'CONV-UNCAC' => 'United Nations Convention Against Corruption (UNCAC)',
  'GEOG-AF' => 'Africa',
  'GEOG-AF-NO' => 'Northern Africa',
  'GEOG-AF-SS' => 'Sub-Saharan Africa',
  'GEOG-AF-SS-EA' => 'Eastern Africa',
  'GEOG-AF-SS-MD' => 'Middle Africa',
  'GEOG-AF-SS-SO' => 'Southern Africa',
  'GEOG-AF-SS-WE' => 'Western Africa',
  'GEOG-AM' => 'Americas',
  'GEOG-AM-LA' => 'Latin America and the Caribbean',
  'GEOG-AM-LA-CA' => 'Caribbean',
  'GEOG-AM-LA-CT' => 'Central America',
  'GEOG-AM-LA-SO' => 'South America',
  'GEOG-AM-NO' => 'Northern America',
  'GEOG-AQ' => 'Antartica',
  'GEOG-AS' => 'Asia',
  'GEOG-AS-CT' => 'Central Asia',
  'GEOG-AS-EA' => 'Eastern Asia',
  'GEOG-AS-SE' => 'South-eastern Asia',
  'GEOG-AS-SO' => 'Southern Asia',
  'GEOG-AS-WE' => 'Western Asia',
  'GEOG-EU' => 'Europe',
  'GEOG-EU-EA' => 'Eastern Europe',
  'GEOG-EU-NO' => 'Northern Europe',
  'GEOG-EU-NO-CH' => 'Channel Islands',
  'GEOG-EU-SO' => 'Southern Europe',
  'GEOG-EU-WE' => 'Western Europe',
  'GEOG-OC' => 'Oceania',
  'GEOG-OC-AN' => 'Australia and New Zealand',
  'GEOG-OC-ME' => 'Melanesia',
  'GEOG-OC-MI' => 'Micronesia',
  'GEOG-OC-PO' => 'Polynesia',
  'ORGS-ACTO' => 'Amazon Cooperation Treaty Organization (ACTO)',
  'ORGS-ASEAN' => 'Association of Southeast Asian Nations (ASEAN)',
  'ORGS-AU' => 'African Union (AU)',
  'ORGS-BRICS' => 'BRICS',
  'ORGS-CIS' => 'Commonwealth of Independent States (CIS)',
  'ORGS-COE' => 'Council of Europe (CoE)',
  'ORGS-CSTO' => 'Collective Security Treaty Organization (CSTO)',
  'ORGS-CWNAT' => 'Commonwealth of the Nations',
  'ORGS-CWRLM' => 'Commonwealth realm',
  'ORGS-EU' => 'European Union (EU)',
  'ORGS-IBRD' => 'International Bank for Reconstruction and Development (IBRD)',
  'ORGS-ICC' => 'International Criminal Court (ICC)',
  'ORGS-ICSID' => 'International Centre for Settlement of Investment Disputes (ICSID)',
  'ORGS-IDA' => 'International Development Association (IDA)',
  'ORGS-IFC' => 'International Finance Corporation (IFC)',
  'ORGS-IPOL' => 'The International Criminal Police Organization (Interpol)',
  'ORGS-MIGA' => 'Multilateral Investment Guarantee Agency (MIGA)',
  'ORGS-NATO' => 'North Atlantic Treaty Organization (NATO)',
  'ORGS-OAS' => 'Organization of American States (OAS)',
  'ORGS-OECD' => 'Organisation for Economic Co-operation and Development (OECD)',
  'ORGS-OPEC' => 'Organization of the Petroleum Exporting Countries (OPEC)',
  'ORGS-OSCE' => 'Organization for Security and Co-operation in Europe (OSCE)',
  'ORGS-SCO' => 'Shanghai Cooperation Organisation (SCO)',
  'ORGS-UN' => 'United Nations (UN)',
  'ORGS-WCO' => 'World Customs Organization (WCO)',
  'ORGS-WTO' => 'World Trade Organization (WTO)',
  'ZONE-EZ' => 'Eurozone (EZ)',
];
