<?php

/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

return [
    'AD' => [
        'name' => 'Andorra',
        'fullName' => 'Principato di Andorra',
        'demonyms' => [
            'Andorrani'
        ],
        'keywords' => [
            'andorrano',
            'andorrana',
            'andorrane'
        ]
    ],
    'AE' => [
        'name' => 'Emirati Arabi Uniti',
        'fullName' => 'Stato degli Emirati Arabi Uniti',
        'demonyms' => [
            'Emiratènsi',
            'Imaratènsi'
        ],
        'keywords' => [
            'uae',
            'eau',
            'emiratense',
            'imaratense',
            'emiratino',
            'emiratina',
            'emiratine',
            'emiratini',
            'emiratiano',
            'emiratiana',
            'emiratiane',
            'emiratiani'
        ]
    ],
    'AF' => [
        'name' => 'Afghanistan',
        'fullName' => 'Emirato Islamico d\'Afghanistan',
        'demonyms' => [
            'Afgani',
            'Afghani',
            'Afgàn',
            'Afghan'
        ],
        'keywords' => [
            'afgano',
            'afgana',
            'afgane',
            'afghano',
            'afghana',
            'afghane',
            'afganistan'
        ]
    ],
    'AG' => [
        'name' => 'Antigua e Barbuda',
        'fullName' => 'Antigua and Barbuda',
        'demonyms' => [
            'Antìguo-barbudani',
            'Antiguani',
            'Barbudani'
        ],
        'keywords' => [
            'antiguobarbudano',
            'antiguobarbudana',
            'antiguobarbudane',
            'antiguano',
            'antiguana',
            'antiguane',
            'barbudano',
            'barbudana',
            'barbudane',
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'indie',
            'occidentali',
            'isole',
            'delle',
            'leeward'
        ]
    ],
    'AI' => [
        'name' => 'Anguilla',
        'fullName' => 'Anguilla',
        'demonyms' => [
            'Anguillani'
        ],
        'keywords' => [
            'anguillano',
            'anguillana',
            'anguillane',
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'territorio',
            'britannico',
            'd',
            'oltremare',
            'di'
        ]
    ],
    'AL' => [
        'name' => 'Albania',
        'fullName' => 'Repubblica di Albania',
        'demonyms' => [
            'Albanési'
        ],
        'keywords' => [
            'albanese',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'AM' => [
        'name' => 'Armenia',
        'fullName' => 'Repubblica di Armenia',
        'demonyms' => [
            'Armèni'
        ],
        'keywords' => [
            'armeno',
            'armena',
            'armene'
        ]
    ],
    'AO' => [
        'name' => 'Angola',
        'fullName' => 'Repubblica di Angola',
        'demonyms' => [
            'Angolani'
        ],
        'keywords' => [
            'angolano',
            'angolana',
            'angolane',
            'dell',
            'stato'
        ]
    ],
    'AQ' => [
        'name' => 'Antartide',
        'fullName' => 'Antartide',
        'demonyms' => [],
        'keywords' => [
            'polo',
            'sud',
            'terra',
            'australis',
            'continente',
            'australe',
            'antartico',
            'antartica',
            'antartici',
            'antartiche'
        ]
    ],
    'AR' => [
        'name' => 'Argentina',
        'fullName' => 'Repubblica Argentina',
        'demonyms' => [
            'Argentini'
        ],
        'keywords' => [
            'argentino',
            'argentine'
        ]
    ],
    'AS' => [
        'name' => 'Samoa Americane',
        'fullName' => 'Samoa Americane',
        'demonyms' => [
            'Samoani'
        ],
        'keywords' => [
            'samoano',
            'samoana',
            'samoane',
            'territorio',
            'delle',
            'isole'
        ]
    ],
    'AT' => [
        'name' => 'Austria',
        'fullName' => 'Repubblica d\'Austria',
        'demonyms' => [
            'Austrìaci'
        ],
        'keywords' => [
            'austriaco',
            'austriaca',
            'austriache'
        ]
    ],
    'AU' => [
        'name' => 'Australia',
        'fullName' => 'Commonwealth d\'Australia',
        'demonyms' => [
            'Australiani'
        ],
        'keywords' => [
            'aussie',
            'australiano',
            'australiana',
            'australiane',
            'dell',
            'autraliano',
            'autraliana',
            'autraliani',
            'autraliane'
        ]
    ],
    'AW' => [
        'name' => 'Aruba',
        'fullName' => 'Paese di Aruba',
        'demonyms' => [
            'Arubani'
        ],
        'keywords' => [
            'isole',
            'abc',
            'arubano',
            'arubana',
            'arubane',
            'caraibi',
            'olandesi',
            'antille',
            'sottovento',
            'piccole',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane'
        ]
    ],
    'AX' => [
        'name' => 'Isole Åland',
        'fullName' => 'Provincia delle Åland',
        'demonyms' => [
            'Alandési'
        ],
        'keywords' => [
            'alandese'
        ]
    ],
    'AZ' => [
        'name' => 'Azerbaigian',
        'fullName' => 'Repubblica d\'Azerbaigian',
        'demonyms' => [
            'Ażèri'
        ],
        'keywords' => [
            'azero',
            'azera',
            'azere',
            'dell',
            'baku'
        ]
    ],
    'BA' => [
        'name' => 'Bosnia-Erzegovina',
        'fullName' => 'Bosnia ed Erzegovina',
        'demonyms' => [
            'Bosnìaci',
            'Erzegovési',
            'Erzegòvini',
            'Bosnìaco-Erzegovési',
            'Bosnìaco-Erzegòvini'
        ],
        'keywords' => [
            'bosniaco',
            'bosniaca',
            'bosniache',
            'erzegovese',
            'erzegovino',
            'erzegovina',
            'erzegovine',
            'bosniacoerzegovese',
            'bosniacoerzegovino',
            'bosniacoerzegovina',
            'bosniacoerzegovine',
            'repubblica',
            'di',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'BB' => [
        'name' => 'Barbados',
        'fullName' => 'Barbados',
        'demonyms' => [
            'Barbadiani',
            'Barbadoregni'
        ],
        'keywords' => [
            'barbadiano',
            'barbadiana',
            'barbadiane',
            'barbadoregno',
            'barbadoregna',
            'barbadoregne'
        ]
    ],
    'BD' => [
        'name' => 'Bangladesh',
        'fullName' => 'Repubblica Popolare del Bangladesh',
        'demonyms' => [
            'Bangladési',
            'Bengalési',
            'Bengalini'
        ],
        'keywords' => [
            'bangladese',
            'bengalese',
            'bengalino',
            'bengalina',
            'bengaline'
        ]
    ],
    'BE' => [
        'name' => 'Belgio',
        'fullName' => 'Regno del Belgio',
        'demonyms' => [
            'Bèlgi'
        ],
        'keywords' => [
            'belga',
            'belghe'
        ]
    ],
    'BF' => [
        'name' => 'Burkina Faso',
        'fullName' => 'Burkina Faso',
        'demonyms' => [
            'Burkinabé'
        ],
        'keywords' => [
            'alto',
            'volta',
            'repubblica',
            'del'
        ]
    ],
    'BG' => [
        'name' => 'Bulgaria',
        'fullName' => 'Repubblica di Bulgaria',
        'demonyms' => [
            'Bùlgari'
        ],
        'keywords' => [
            'bulgaro',
            'bulgara',
            'bulgare',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'BH' => [
        'name' => 'Bahrein',
        'fullName' => 'Regno del Bahrein',
        'demonyms' => [
            'Bahreiniti',
            'Bahrainiti'
        ],
        'keywords' => [
            'bahreinita',
            'bahreinite',
            'bahrainita',
            'bahrainite'
        ]
    ],
    'BI' => [
        'name' => 'Burundi',
        'fullName' => 'Repubblica del Burundi',
        'demonyms' => [
            'Burundési'
        ],
        'keywords' => [
            'burundese'
        ]
    ],
    'BJ' => [
        'name' => 'Benin',
        'fullName' => 'Repubblica del Benin',
        'demonyms' => [
            'Beninési',
            'Beniniani'
        ],
        'keywords' => [
            'dahomey',
            'beninese',
            'beniniano',
            'beniniana',
            'beniniane'
        ]
    ],
    'BL' => [
        'name' => 'Saint Barthélemy',
        'fullName' => 'Collettività d\'oltremare di Saint Barthélemy',
        'demonyms' => [
            'Barthélemesi',
            'Santabarthesi'
        ],
        'keywords' => [
            'com',
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'barthelemese',
            'santabarthese'
        ]
    ],
    'BM' => [
        'name' => 'Bermuda',
        'fullName' => 'Bermuda (o Bermude)',
        'demonyms' => [
            'Bermudiani'
        ],
        'keywords' => [
            'bermudiano',
            'bermudiana',
            'bermudiane',
            'isole'
        ]
    ],
    'BN' => [
        'name' => 'Brunei',
        'fullName' => 'Stato del Brunei, Dimora della Pace',
        'demonyms' => [
            'Bruneiani'
        ],
        'keywords' => [
            'bruneiano',
            'bruneiana',
            'bruneiane',
            'sultanato'
        ]
    ],
    'BO' => [
        'name' => 'Bolivia',
        'fullName' => 'Stato plurinazionale del Bolivia',
        'demonyms' => [
            'Boliviani'
        ],
        'keywords' => [
            'boliviano',
            'boliviana',
            'boliviane',
            'di'
        ]
    ],
    'BQ' => [
        'name' => 'Bonaire, Sint Eustatius e Saba',
        'fullName' => 'Paesi Bassi caraibici',
        'demonyms' => [
            'Boneriani',
            'Statianesi',
            'Sabani'
        ],
        'keywords' => [
            'isole',
            'abc',
            'sss',
            'bes',
            'caraibi',
            'olandesi',
            'antille',
            'piccole',
            'caraibico',
            'caraibica',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'bonairiano',
            'bonairiani',
            'sabaiano',
            'sabaiani',
            'statiano',
            'statiani',
            'boneriano',
            'boneriana',
            'boneriane',
            'statianese',
            'sabano',
            'sabana',
            'sabane'
        ]
    ],
    'BR' => [
        'name' => 'Brasile',
        'fullName' => 'Repubblica Federale del Brasile',
        'demonyms' => [
            'Braṡiliani'
        ],
        'keywords' => [
            'brailiano',
            'brailiana',
            'brailiane',
            'federativa'
        ]
    ],
    'BS' => [
        'name' => 'Bahamas',
        'fullName' => 'Commonwealth delle Bahamas',
        'demonyms' => [
            'Bahamènsi'
        ],
        'keywords' => [
            'bahamense'
        ]
    ],
    'BT' => [
        'name' => 'Bhutan',
        'fullName' => 'Regno del Bhutan',
        'demonyms' => [
            'Bhutanési'
        ],
        'keywords' => [
            'regno',
            'del',
            'drago',
            'tonante',
            'di',
            'tuono',
            'druk',
            'yul',
            'bhutanese',
            'butan'
        ]
    ],
    'BV' => [
        'name' => 'Isola di Bouvet',
        'fullName' => 'Isola di Bouvet',
        'demonyms' => [],
        'keywords' => [
            'buvet',
            'buve',
            'bouvetiano',
            'bouvetiana',
            'bouvetiani',
            'bouvetiane'
        ]
    ],
    'BW' => [
        'name' => 'Botswana',
        'fullName' => 'Republic of Botswana',
        'demonyms' => [
            'Botswani',
            'Bozzu̯àni'
        ],
        'keywords' => [
            'botswano',
            'botswane',
            'bozzuano',
            'bozzuana',
            'bozzuane',
            'repubblica',
            'del',
            'botswanesi',
            'botswanese'
        ]
    ],
    'BY' => [
        'name' => 'Bielorussia',
        'fullName' => 'Repubblica di Bielorussia',
        'demonyms' => [
            'Bielorussi',
            'Belorussi'
        ],
        'keywords' => [
            'russia',
            'bianca',
            'belarus',
            'bielorusso',
            'bielorussa',
            'bielorusse',
            'belorusso',
            'belorussa',
            'belorusse'
        ]
    ],
    'BZ' => [
        'name' => 'Belize',
        'fullName' => 'Belize',
        'demonyms' => [
            'Beliżiani'
        ],
        'keywords' => [
            'honduras',
            'britannico',
            'beliziano',
            'beliziana',
            'beliziane'
        ]
    ],
    'CA' => [
        'name' => 'Canada',
        'fullName' => 'Canada (o Canadà)',
        'demonyms' => [
            'Canadési'
        ],
        'keywords' => [
            'canadese'
        ]
    ],
    'CC' => [
        'name' => 'Isole Cocos (Keeling)',
        'fullName' => 'Territorio delle Isole Cocos (Keeling)',
        'demonyms' => [
            'Cocosi',
            'Cocosiani'
        ],
        'keywords' => [
            'cocoso',
            'cocosa',
            'cocose',
            'cocosiano',
            'cocosiana',
            'cocosiane'
        ]
    ],
    'CD' => [
        'name' => 'Congo (Rep. Dem.)',
        'fullName' => 'Repubblica Democratica del Congo',
        'demonyms' => [
            'Congolési'
        ],
        'keywords' => [
            'kinshasa',
            'repubblica',
            'rdc',
            'belga',
            'ex',
            'zaire',
            'congolese'
        ]
    ],
    'CF' => [
        'name' => 'Repubblica Centrafricana',
        'fullName' => 'Repubblica Centrafricana',
        'demonyms' => [
            'Centrafricani',
            'Centroafricani'
        ],
        'keywords' => [
            'centrafricano',
            'centrafricane',
            'centroafricano',
            'centroafricana',
            'centroafricane',
            'centrafrica'
        ]
    ],
    'CG' => [
        'name' => 'Congo',
        'fullName' => 'Repubblica del Congo',
        'demonyms' => [
            'Congolési'
        ],
        'keywords' => [
            'brazzaville',
            'repubblica',
            'francese',
            'ex',
            'congolese'
        ]
    ],
    'CH' => [
        'name' => 'Svizzera',
        'fullName' => 'Confederazione svizzera',
        'demonyms' => [
            'Svìzzeri',
            'Elvètici'
        ],
        'keywords' => [
            'svizzero',
            'svizzere',
            'elvetico',
            'elvetica',
            'elvetiche'
        ]
    ],
    'CI' => [
        'name' => 'Costa d\'Avorio',
        'fullName' => 'Repubblica della Costa d\'Avorio',
        'demonyms' => [
            'Ivoriani',
            'Avoriano'
        ],
        'keywords' => [
            'ivoriano',
            'ivoriana',
            'ivoriane',
            'avoriana',
            'avoriani',
            'avoriane',
            'di'
        ]
    ],
    'CK' => [
        'name' => 'Isole Cook',
        'fullName' => 'Isole Cook',
        'demonyms' => [
            'Cookiani'
        ],
        'keywords' => [
            'cookiano',
            'cookiana',
            'cookiane',
            'cookese',
            'cookesi'
        ]
    ],
    'CL' => [
        'name' => 'Cile',
        'fullName' => 'Repubblica del Cile',
        'demonyms' => [
            'Cilèni'
        ],
        'keywords' => [
            'cileno',
            'cilena',
            'cilene'
        ]
    ],
    'CM' => [
        'name' => 'Camerun',
        'fullName' => 'Repubblica del Camerun',
        'demonyms' => [
            'Camerunési'
        ],
        'keywords' => [
            'camerunese',
            'camerunense',
            'camerunensi'
        ]
    ],
    'CN' => [
        'name' => 'Cina',
        'fullName' => 'Repubblica Popolare Cinese',
        'demonyms' => [
            'Cinési'
        ],
        'keywords' => [
            'cinese'
        ]
    ],
    'CO' => [
        'name' => 'Colombia',
        'fullName' => 'Repubblica della Colombia',
        'demonyms' => [
            'Colombiani',
            'Columbiani'
        ],
        'keywords' => [
            'colombiano',
            'colombiana',
            'colombiane',
            'columbiano',
            'columbiana',
            'columbiane',
            'di'
        ]
    ],
    'CR' => [
        'name' => 'Costa Rica',
        'fullName' => 'Repubblica di Costa Rica',
        'demonyms' => [
            'Costaricani',
            'Costaricènsi'
        ],
        'keywords' => [
            'costaricano',
            'costaricana',
            'costaricane',
            'costaricense'
        ]
    ],
    'CU' => [
        'name' => 'Cuba',
        'fullName' => 'Repubblica di Cuba',
        'demonyms' => [
            'Cubani'
        ],
        'keywords' => [
            'cubano',
            'cubana',
            'cubane',
            'caraibi',
            'grandi',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane'
        ]
    ],
    'CV' => [
        'name' => 'Capo Verde',
        'fullName' => 'Repubblica di Capo Verde',
        'demonyms' => [
            'Capoverdiani'
        ],
        'keywords' => [
            'capoverdiano',
            'capoverdiana',
            'capoverdiane'
        ]
    ],
    'CW' => [
        'name' => 'Curaçao',
        'fullName' => 'Paese di Curaçao',
        'demonyms' => [
            'Curasanesi',
            'Curaçanesi'
        ],
        'keywords' => [
            'isole',
            'abc',
            'caraibi',
            'olandesi',
            'antille',
            'piccole',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'curasanese',
            'curacanese',
            'curacaoiano',
            'curacaoiane',
            'curacaoiana',
            'curacaoiani',
            'curacaoano',
            'curacaoana',
            'curacaoane',
            'curacaoani',
            'curaziano',
            'curaziane',
            'curaziani'
        ]
    ],
    'CX' => [
        'name' => 'Isola di Natale',
        'fullName' => 'Isola di Natale',
        'demonyms' => [
            'Natalensi',
            'Natalini'
        ],
        'keywords' => [
            'kiritimati',
            'natalense',
            'natalino',
            'natalina',
            'nataline'
        ]
    ],
    'CY' => [
        'name' => 'Cipro',
        'fullName' => 'Repubblica di Cipro',
        'demonyms' => [
            'Ciprïòti'
        ],
        'keywords' => [
            'cipriota',
            'cipriote'
        ]
    ],
    'CZ' => [
        'name' => 'Repubblica Ceca',
        'fullName' => 'Repubblica Ceca',
        'demonyms' => [
            'Cèchi',
            'Cèki',
            'Czèchi'
        ],
        'keywords' => [
            'ceco',
            'ceche',
            'ceko',
            'ceka',
            'ceke',
            'czeco',
            'czeca',
            'czeche',
            'cechia'
        ]
    ],
    'DE' => [
        'name' => 'Germania',
        'fullName' => 'Repubblica Federale di Germania',
        'demonyms' => [
            'Tedéschi'
        ],
        'keywords' => [
            'tedesco',
            'tedesca',
            'tedesche',
            'alemanno',
            'alemanna',
            'alemanne',
            'alemanni',
            'teutonico',
            'teutonica',
            'teutoniche',
            'teutonici',
            'teutone',
            'teutoni',
            'teutonia'
        ]
    ],
    'DJ' => [
        'name' => 'Gibuti',
        'fullName' => 'Repubblica di Gibuti',
        'demonyms' => [
            'Gibutiani'
        ],
        'keywords' => [
            'gibutiano',
            'gibutiana',
            'gibutiane'
        ]
    ],
    'DK' => [
        'name' => 'Danimarca',
        'fullName' => 'Regno di Danimarca',
        'demonyms' => [
            'Danési'
        ],
        'keywords' => [
            'danese'
        ]
    ],
    'DM' => [
        'name' => 'Dominica',
        'fullName' => 'Commonwealth della Dominica',
        'demonyms' => [
            'Dominicani'
        ],
        'keywords' => [
            'dominicano',
            'dominicana',
            'dominicane',
            'di',
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'dominicense',
            'dominicensi'
        ]
    ],
    'DO' => [
        'name' => 'Repubblica Dominicana',
        'fullName' => 'Repubblica Dominicana',
        'demonyms' => [
            'Dominicani'
        ],
        'keywords' => [
            'dominicano',
            'dominicane',
            'caraibi',
            'grandi',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'domenicano',
            'dominicense',
            'dominicensi'
        ]
    ],
    'DZ' => [
        'name' => 'Algeria',
        'fullName' => 'Repubblica Democratica Popolare di Algeria',
        'demonyms' => [
            'Algerini'
        ],
        'keywords' => [
            'algerino',
            'algerina',
            'algerine',
            'e'
        ]
    ],
    'EC' => [
        'name' => 'Ecuador',
        'fullName' => 'Repubblica dell\'Ecuador',
        'demonyms' => [
            'Ecuadoriani'
        ],
        'keywords' => [
            'ecuadoriano',
            'ecuadoriana',
            'ecuadoriane',
            'ecuatoriano',
            'ecuatoriana',
            'ecuatoriane',
            'ecuatoriani',
            'equadoregno',
            'equadoregna',
            'equadoregne'
        ]
    ],
    'EE' => [
        'name' => 'Estonia',
        'fullName' => 'Repubblica d\'Estonia',
        'demonyms' => [
            'Èstoni',
            'Estóni'
        ],
        'keywords' => [
            'estone',
            'di'
        ]
    ],
    'EG' => [
        'name' => 'Egitto',
        'fullName' => 'Repubblica Araba d\'Egitto',
        'demonyms' => [
            'Egiziani'
        ],
        'keywords' => [
            'egiziano',
            'egiziana',
            'egiziane',
            'egizio',
            'egizi'
        ]
    ],
    'EH' => [
        'name' => 'Sahara Occidentale',
        'fullName' => 'Repubblica Democratica Araba Sahrawi',
        'demonyms' => [
            'Sahariani',
            'Sahariani occidentali'
        ],
        'keywords' => [
            'sahrawi',
            'sahariano',
            'sahariana',
            'sahariane',
            'del'
        ]
    ],
    'ER' => [
        'name' => 'Eritrea',
        'fullName' => 'Stato di Eritrea',
        'demonyms' => [
            'Eritrèi'
        ],
        'keywords' => [
            'eritreo',
            'eritree'
        ]
    ],
    'ES' => [
        'name' => 'Spagna',
        'fullName' => 'Regno di Spagna',
        'demonyms' => [
            'Spagnòli',
            'Ispànici',
            'Ispàni',
            'Ibèrici',
            'Spagnuòli'
        ],
        'keywords' => [
            'iberia',
            'penisola',
            'iberica',
            'spagnolo',
            'spagnola',
            'spagnole',
            'ispanico',
            'ispanica',
            'ispaniche',
            'ispano',
            'ispana',
            'ispane',
            'iberico',
            'iberiche',
            'spagnuolo',
            'spagnuola',
            'spagnuole'
        ]
    ],
    'ET' => [
        'name' => 'Etiopia',
        'fullName' => 'Repubblica Federale Democratica d\'Etiopia',
        'demonyms' => [
            'Etìopi',
            'Etìopi',
            'Etïòpi',
            'Etïòpi'
        ],
        'keywords' => [
            'abissinia',
            'abissino',
            'abissini',
            'abissine',
            'abissina',
            'etiope',
            'etiopo'
        ]
    ],
    'FI' => [
        'name' => 'Finlandia',
        'fullName' => 'Repubblica di Finlandia',
        'demonyms' => [
            'Finlandési',
            'Fìnnici'
        ],
        'keywords' => [
            'finlandese',
            'finnico',
            'finnica',
            'finniche'
        ]
    ],
    'FJ' => [
        'name' => 'Figi',
        'fullName' => 'Repubblica di Figi',
        'demonyms' => [
            'Figiani'
        ],
        'keywords' => [
            'figiano',
            'figiana',
            'figiane',
            'delle',
            'isola',
            'isole'
        ]
    ],
    'FK' => [
        'name' => 'Isole Falkland',
        'fullName' => 'Isole Falkland',
        'demonyms' => [
            'Falklandési'
        ],
        'keywords' => [
            'malvine',
            'malvinese',
            'malvinesi',
            'falklandese'
        ]
    ],
    'FM' => [
        'name' => 'Micronesia',
        'fullName' => 'Stati Federati di Micronesia',
        'demonyms' => [
            'Microneṡiani'
        ],
        'keywords' => [
            'com',
            'stati',
            'federati',
            'di',
            'microneiano',
            'microneiana',
            'microneiane'
        ]
    ],
    'FO' => [
        'name' => 'Isole Fær Øer',
        'fullName' => 'Isole Faroe (Feringie)',
        'demonyms' => [
            'Farìngi',
            'Feroesi',
            'Faroesi',
            'Faroensi'
        ],
        'keywords' => [
            'faroe',
            'feringie',
            'faringio',
            'faringia',
            'faringie',
            'feroese',
            'faroese',
            'faroense'
        ]
    ],
    'FR' => [
        'name' => 'Francia',
        'fullName' => 'Repubblica francese',
        'demonyms' => [
            'Francéṡi'
        ],
        'keywords' => [
            'repubblica',
            'transalpina',
            'francee',
            'transalpino',
            'transalpini',
            'transalpine'
        ]
    ],
    'GA' => [
        'name' => 'Gabon',
        'fullName' => 'Repubblica Gabonese',
        'demonyms' => [
            'Gabonési'
        ],
        'keywords' => [
            'gabonese'
        ]
    ],
    'GB' => [
        'name' => 'Regno Unito',
        'fullName' => 'Regno Unito di Gran Bretagna ed Irlanda del Nord',
        'demonyms' => [
            'Britànnici',
            'Inglési',
            'Scozzési',
            'Gallési',
            'Irlandési',
            'Nordirlandési',
            'Nòrd-Irlandési',
            'Irlandési del Nòrd'
        ],
        'keywords' => [
            'uk',
            'ukgb',
            'gbeng',
            'gbnir',
            'gbsct',
            'gbwls',
            'gbcym',
            'gbeaw',
            'gbgbn',
            'gbukm',
            'isola',
            'britannica',
            'isole',
            'britanniche',
            'caledonia',
            'inghilterra',
            'britannia',
            'albione',
            'scozia',
            'galles',
            'irlanda',
            'settentrionale',
            'alba',
            'cymru',
            'ulster',
            'britannico',
            'inglese',
            'scozzese',
            'gallese',
            'irlandese',
            'nordirlandese',
            'anglo',
            'angla',
            'angli',
            'angle',
            'albionico',
            'albionica',
            'albionici',
            'albioniche',
            'anglico',
            'anglica',
            'anglici',
            'angliche',
            'britanno',
            'britanna',
            'britanni',
            'britanne',
            'scoto',
            'scota',
            'scoti',
            'scote'
        ]
    ],
    'GD' => [
        'name' => 'Grenada',
        'fullName' => 'Grenada',
        'demonyms' => [
            'Grenadini',
            'Grenadiani'
        ],
        'keywords' => [
            'grenadino',
            'grenadina',
            'grenadine',
            'grenadiano',
            'grenadiana',
            'grenadiane',
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'isola',
            'di'
        ]
    ],
    'GE' => [
        'name' => 'Georgia',
        'fullName' => 'Repubblica della Georgia',
        'demonyms' => [
            'Georgiani'
        ],
        'keywords' => [
            'georgiano',
            'georgiana',
            'georgiane'
        ]
    ],
    'GF' => [
        'name' => 'Guyana Francese',
        'fullName' => 'Dipartimento della Guyana francese',
        'demonyms' => [
            'Guianési',
            'Guyanési'
        ],
        'keywords' => [
            'dom',
            'guianese',
            'guyanese',
            'della',
            'francesi'
        ]
    ],
    'GG' => [
        'name' => 'Guernsey',
        'fullName' => 'Baliato di Guernsey',
        'demonyms' => [
            'Guernesiani',
            'Guernesi'
        ],
        'keywords' => [
            'isole',
            'normanne',
            'guernseiano',
            'guernseiana',
            'guernseiane',
            'guernseiani',
            'guernesiano',
            'guernesiana',
            'guernesiane',
            'guernese'
        ]
    ],
    'GH' => [
        'name' => 'Ghana',
        'fullName' => 'Repubblica del Ghana',
        'demonyms' => [
            'Ghanési',
            'Ghanaési',
            'Ganaési',
            'Ghanaènsi',
            'Ganaènsi'
        ],
        'keywords' => [
            'ghanese',
            'ghanaese',
            'ganaese',
            'ghanaense',
            'ganaense',
            'ganesi'
        ]
    ],
    'GI' => [
        'name' => 'Gibilterra',
        'fullName' => 'Gibilterra',
        'demonyms' => [
            'Gibilterriani'
        ],
        'keywords' => [
            'colonia',
            'di',
            'gibilterriano',
            'gibilterriana',
            'gibilterriane'
        ]
    ],
    'GL' => [
        'name' => 'Groenlandia',
        'fullName' => 'Groenlandia',
        'demonyms' => [
            'Groenlandési'
        ],
        'keywords' => [
            'inuit',
            'groenlandese'
        ]
    ],
    'GM' => [
        'name' => 'Gambia',
        'fullName' => 'Repubblica del Gambia (o della Gambia)',
        'demonyms' => [
            'Gambiani'
        ],
        'keywords' => [
            'gambiano',
            'gambiana',
            'gambiane'
        ]
    ],
    'GN' => [
        'name' => 'Guinea',
        'fullName' => 'Repubblica di Guinea',
        'demonyms' => [
            'Guineani'
        ],
        'keywords' => [
            'conakry',
            'guineano',
            'guineana',
            'guineane'
        ]
    ],
    'GP' => [
        'name' => 'Guadalupa',
        'fullName' => 'Dipartimento di Guadalupa',
        'demonyms' => [
            'Guadalupensi',
            'Guadalupiani'
        ],
        'keywords' => [
            'dom',
            'guadalupe',
            'isola',
            'di',
            'guadalupense',
            'guadalupiano',
            'guadalupiana',
            'guadalupiane',
            'antille',
            'francesi',
            'caraibi',
            'piccole',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane'
        ]
    ],
    'GQ' => [
        'name' => 'Guinea Equatoriale',
        'fullName' => 'Repubblica della Guinea Equatoriale',
        'demonyms' => [
            'Guineani'
        ],
        'keywords' => [
            'guineano',
            'guineana',
            'guineane',
            'di'
        ]
    ],
    'GR' => [
        'name' => 'Grecia',
        'fullName' => 'Repubblica ellenica',
        'demonyms' => [
            'Grèci',
            'Ellènici'
        ],
        'keywords' => [
            'repubblica',
            'ellenica',
            'greco',
            'greca',
            'greche',
            'ellenico',
            'elleniche',
            'el'
        ]
    ],
    'GS' => [
        'name' => 'Georgia del Sud e Isole Sandwich Meridionali',
        'fullName' => 'Georgia del Sud e Isole Sandwich Australi',
        'demonyms' => [
            'Sudgeorgiani'
        ],
        'keywords' => [
            'sudgeorgiano',
            'sudgeorgiana',
            'sudgeorgiane'
        ]
    ],
    'GT' => [
        'name' => 'Guatemala',
        'fullName' => 'Repubblica del Guatemala',
        'demonyms' => [
            'Guatemaltèchi'
        ],
        'keywords' => [
            'guatemalteco',
            'guatemalteca',
            'guatemalteche',
            'guatemalese',
            'guatemalesi'
        ]
    ],
    'GU' => [
        'name' => 'Guam',
        'fullName' => 'Guam',
        'demonyms' => [
            'Mariannènsi'
        ],
        'keywords' => [
            'isola',
            'di',
            'mariannense'
        ]
    ],
    'GW' => [
        'name' => 'Guinea-Bissau',
        'fullName' => 'Repubblica della Guinea-Bissau',
        'demonyms' => [
            'Guineani'
        ],
        'keywords' => [
            'guinea',
            'portoghese',
            'guineano',
            'guineana',
            'guineane',
            'di',
            'guineabissauiano',
            'guineabissauiana',
            'bissauiano',
            'bissauiana'
        ]
    ],
    'GY' => [
        'name' => 'Guyana',
        'fullName' => 'Repubblica Cooperativa di Guyana',
        'demonyms' => [
            'Guianési',
            'Guyanési'
        ],
        'keywords' => [
            'cooperativa',
            'repubblica',
            'di',
            'guianese',
            'guyanese'
        ]
    ],
    'HK' => [
        'name' => 'Hong Kong',
        'fullName' => 'Regione amministrativa speciale di Hong Kong della Repubblica Popolare Cinese',
        'demonyms' => [
            'Hongkonghesi'
        ],
        'keywords' => [
            'hongkonghese'
        ]
    ],
    'HM' => [
        'name' => 'Isole Heard e McDonald',
        'fullName' => 'Territorio delle Isole Heard e McDonald',
        'demonyms' => [],
        'keywords' => []
    ],
    'HN' => [
        'name' => 'Honduras',
        'fullName' => 'Repubblica dell\'Honduras',
        'demonyms' => [
            'Hondurégni',
            'Ondurégni'
        ],
        'keywords' => [
            'honduregno',
            'honduregna',
            'honduregne',
            'onduregno',
            'onduregna',
            'onduregne'
        ]
    ],
    'HR' => [
        'name' => 'Croazia',
        'fullName' => 'Repubblica di Croazia',
        'demonyms' => [
            'Croati'
        ],
        'keywords' => [
            'croato',
            'croata',
            'croate',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'HT' => [
        'name' => 'Haiti',
        'fullName' => 'Repubblica di Haiti',
        'demonyms' => [
            'Haitiani'
        ],
        'keywords' => [
            'haitiano',
            'haitiana',
            'haitiane',
            'caraibi',
            'grandi',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane'
        ]
    ],
    'HU' => [
        'name' => 'Ungheria',
        'fullName' => 'Ungheria',
        'demonyms' => [
            'Ungherési',
            'Magiàri',
            'Màgiari',
            'Ùngari',
            'Ungàrici'
        ],
        'keywords' => [
            'ungherese',
            'magiaro',
            'magiara',
            'magiare',
            'ungaro',
            'ungara',
            'ungare',
            'ungarico',
            'ungarica',
            'ungariche'
        ]
    ],
    'ID' => [
        'name' => 'Indonesia',
        'fullName' => 'Repubblica d\'Indonesia',
        'demonyms' => [
            'Indonesiani'
        ],
        'keywords' => [
            'timor',
            'portoghese',
            'indonesiano',
            'indonesiana',
            'indonesiane',
            'di'
        ]
    ],
    'IE' => [
        'name' => 'Irlanda',
        'fullName' => 'Repubblica d\'Irlanda',
        'demonyms' => [
            'Irlandési'
        ],
        'keywords' => [
            'eire',
            'irlandese'
        ]
    ],
    'IL' => [
        'name' => 'Israele',
        'fullName' => 'Stato d\'Israele',
        'demonyms' => [
            'Israeliani'
        ],
        'keywords' => [
            'israeliano',
            'israeliana',
            'israeliane',
            'di',
            'israelita',
            'israeliti'
        ]
    ],
    'IM' => [
        'name' => 'Isola di Man',
        'fullName' => 'Isola di Man',
        'demonyms' => [
            'Mannési'
        ],
        'keywords' => [
            'mann',
            'mannese'
        ]
    ],
    'IN' => [
        'name' => 'India',
        'fullName' => 'Repubblica dell\'India',
        'demonyms' => [
            'Indiani'
        ],
        'keywords' => [
            'indiano',
            'indiana',
            'indiane'
        ]
    ],
    'IO' => [
        'name' => 'Territorio britannico dell\'oceano Indiano',
        'fullName' => 'Territorio britannico dell\'oceano Indiano',
        'demonyms' => [],
        'keywords' => [
            'chagos',
            'biot'
        ]
    ],
    'IQ' => [
        'name' => 'Iraq',
        'fullName' => 'Repubblica d\'Iraq',
        'demonyms' => [
            'Irachèni',
            'Irakèni'
        ],
        'keywords' => [
            'mesopotamia',
            'iracheno',
            'irachena',
            'irachene',
            'irakeno',
            'irakena',
            'irakene'
        ]
    ],
    'IR' => [
        'name' => 'Iran',
        'fullName' => 'Repubblica Islamica dell\'Iran',
        'demonyms' => [
            'Iraniani'
        ],
        'keywords' => [
            'persia',
            'persiano',
            'persiana',
            'persiane',
            'persiani',
            'iraniano',
            'iraniana',
            'iraniane'
        ]
    ],
    'IS' => [
        'name' => 'Islanda',
        'fullName' => 'Repubblica d\'Islanda',
        'demonyms' => [
            'Islandési'
        ],
        'keywords' => [
            'islandese'
        ]
    ],
    'IT' => [
        'name' => 'Italia',
        'fullName' => 'Repubblica Italiana',
        'demonyms' => [
            'Italiani'
        ],
        'keywords' => [
            'penisola',
            'italiano',
            'italiana',
            'italiane'
        ]
    ],
    'JE' => [
        'name' => 'Jersey',
        'fullName' => 'Baliato di Jersey',
        'demonyms' => [
            'Jersesi'
        ],
        'keywords' => [
            'isole',
            'normanne',
            'jersese'
        ]
    ],
    'JM' => [
        'name' => 'Giamaica',
        'fullName' => 'Giamaica',
        'demonyms' => [
            'Giamaicani'
        ],
        'keywords' => [
            'giamaicano',
            'giamaicana',
            'giamaicane',
            'caraibi',
            'grandi',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane'
        ]
    ],
    'JO' => [
        'name' => 'Giordania',
        'fullName' => 'Regno Hascemita di Giordania',
        'demonyms' => [
            'Giordani',
            'Giordaniani'
        ],
        'keywords' => [
            'regno',
            'hascemita',
            'di',
            'giordano',
            'giordana',
            'giordane',
            'giordaniano',
            'giordaniana',
            'giordaniane'
        ]
    ],
    'JP' => [
        'name' => 'Giappone',
        'fullName' => 'Stato del Giappone',
        'demonyms' => [
            'Giapponési',
            'Nippònici'
        ],
        'keywords' => [
            'nippon',
            'giapponese',
            'nipponico',
            'nipponica',
            'nipponiche'
        ]
    ],
    'KE' => [
        'name' => 'Kenya',
        'fullName' => 'Repubblica del Kenya',
        'demonyms' => [
            'Keniani',
            'Kenioti'
        ],
        'keywords' => [
            'keniano',
            'keniana',
            'keniane',
            'keniota'
        ]
    ],
    'KG' => [
        'name' => 'Kirghizistan',
        'fullName' => 'Repubblica del Kirghizistan',
        'demonyms' => [
            'Kirghiṡi',
            'Kirghiżi',
            'Chirghiṡi'
        ],
        'keywords' => [
            'kirghio',
            'kirghia',
            'kirghie',
            'kirghizo',
            'kirghiza',
            'kirghize',
            'chirghio',
            'chirghia',
            'chirghie'
        ]
    ],
    'KH' => [
        'name' => 'Cambogia',
        'fullName' => 'Regno di Cambogia',
        'demonyms' => [
            'Cambogiani'
        ],
        'keywords' => [
            'cambogiano',
            'cambogiana',
            'cambogiane'
        ]
    ],
    'KI' => [
        'name' => 'Kiribati',
        'fullName' => 'Repubblica delle Kiribati',
        'demonyms' => [
            'Kiribatési'
        ],
        'keywords' => [
            'kiribatese'
        ]
    ],
    'KM' => [
        'name' => 'Comore',
        'fullName' => 'Unione delle Comore',
        'demonyms' => [
            'Comoriani'
        ],
        'keywords' => [
            'comoriano',
            'comoriana',
            'comoriane'
        ]
    ],
    'KN' => [
        'name' => 'Saint Kitts e Nevis',
        'fullName' => 'Federazione di Saint Kitts e Nevis',
        'demonyms' => [
            'Nevisiani',
            'Cristoforiani',
            'Christopheriani',
            'Christoforiani'
        ],
        'keywords' => [
            'caraibi',
            'christopher',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'nevisiano',
            'nevisiana',
            'nevisiane',
            'cristoforiano',
            'cristoforiana',
            'cristoforiane',
            'christopheriano',
            'christopheriana',
            'christopheriane',
            'christoforiano',
            'christoforiana',
            'christoforiane'
        ]
    ],
    'KP' => [
        'name' => 'Corea del Nord',
        'fullName' => 'Repubblica Popolare Democratica di Corea',
        'demonyms' => [
            'Coreani',
            'Nordcoreani',
            'Coreani del Nord',
            'Nòrd-Coreani'
        ],
        'keywords' => [
            'coreano',
            'coreana',
            'coreane',
            'nordcoreano',
            'nordcoreana',
            'nordcoreane'
        ]
    ],
    'KR' => [
        'name' => 'Corea del Sud',
        'fullName' => 'Repubblica di Corea',
        'demonyms' => [
            'Coreani',
            'Sudcoreani',
            'Coreani del Sud',
            'Sud-Coreani'
        ],
        'keywords' => [
            'coreano',
            'coreana',
            'coreane',
            'sudcoreano',
            'sudcoreana',
            'sudcoreane'
        ]
    ],
    'KW' => [
        'name' => 'Kuwait',
        'fullName' => 'Stato del Kuwait',
        'demonyms' => [
            'Kuwaitiani'
        ],
        'keywords' => [
            'kuwaitiano',
            'kuwaitiana',
            'kuwaitiane'
        ]
    ],
    'KY' => [
        'name' => 'Isole Cayman',
        'fullName' => 'Isole Cayman',
        'demonyms' => [
            'Caymaniani',
            'Caymanesi'
        ],
        'keywords' => [
            'collettivita',
            'delle',
            'caymaniano',
            'caymaniana',
            'caymaniane',
            'caymanese',
            'caimaniano',
            'caimaniana',
            'caimaniani',
            'caimaniane',
            'caimanese',
            'caimanesi'
        ]
    ],
    'KZ' => [
        'name' => 'Kazakistan',
        'fullName' => 'Repubblica del Kazakistan',
        'demonyms' => [
            'Każachi',
            'Każaki'
        ],
        'keywords' => [
            'kazaco',
            'kazaca',
            'kazache',
            'kazako',
            'kazaka',
            'kazake'
        ]
    ],
    'LA' => [
        'name' => 'Laos',
        'fullName' => 'Repubblica Popolare Democratica del Laos',
        'demonyms' => [
            'Laotiani',
            'Laosiani'
        ],
        'keywords' => [
            'laotiano',
            'laotiana',
            'laotiane',
            'laosiano',
            'laosiana',
            'laosiane'
        ]
    ],
    'LB' => [
        'name' => 'Libano',
        'fullName' => 'Repubblica Libanese',
        'demonyms' => [
            'Libanési'
        ],
        'keywords' => [
            'libanese',
            'del'
        ]
    ],
    'LC' => [
        'name' => 'Santa Lucia',
        'fullName' => 'Saint Lucia',
        'demonyms' => [
            'Santaluciani'
        ],
        'keywords' => [
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'santaluciano',
            'santaluciana',
            'santaluciane'
        ]
    ],
    'LI' => [
        'name' => 'Liechtenstein',
        'fullName' => 'Principato del Liechtenstein',
        'demonyms' => [
            'Liechtensteiniani'
        ],
        'keywords' => [
            'liechtensteiniano',
            'liechtensteiniana',
            'liechtensteiniane',
            'liechtensteinese',
            'liechtensteinesi',
            'licchenstain',
            'licchestain'
        ]
    ],
    'LK' => [
        'name' => 'Sri Lanka',
        'fullName' => 'Repubblica Democratica Socialista dello Sri Lanka',
        'demonyms' => [
            'Srilankési',
            'Singalési',
            'Cingalési'
        ],
        'keywords' => [
            'ceylon',
            'srilankese',
            'singalese',
            'cingalese'
        ]
    ],
    'LR' => [
        'name' => 'Liberia',
        'fullName' => 'Repubblica della Liberia',
        'demonyms' => [
            'Liberiani'
        ],
        'keywords' => [
            'liberiano',
            'liberiana',
            'liberiane'
        ]
    ],
    'LS' => [
        'name' => 'Lesotho',
        'fullName' => 'Regno del Lesotho',
        'demonyms' => [
            'Lesothiani'
        ],
        'keywords' => [
            'basotho',
            'lesothiano',
            'lesothiana',
            'lesothiane',
            'lesoto',
            'basoto',
            'lesotiano',
            'lesotiana',
            'lesotiani',
            'lesotiane'
        ]
    ],
    'LT' => [
        'name' => 'Lituania',
        'fullName' => 'Repubblica di Lituania',
        'demonyms' => [
            'Litüani'
        ],
        'keywords' => [
            'lituano',
            'lituana',
            'lituane'
        ]
    ],
    'LU' => [
        'name' => 'Lussemburgo',
        'fullName' => 'Granducato di Lussemburgo',
        'demonyms' => [
            'Lussemburghési'
        ],
        'keywords' => [
            'lussemburghese'
        ]
    ],
    'LV' => [
        'name' => 'Lettonia',
        'fullName' => 'Repubblica di Lettonia',
        'demonyms' => [
            'Lèttoni',
            'Lettóni'
        ],
        'keywords' => [
            'lettone'
        ]
    ],
    'LY' => [
        'name' => 'Libia',
        'fullName' => 'Stato della Libia',
        'demonyms' => [
            'Lìbici'
        ],
        'keywords' => [
            'libico',
            'libica',
            'libiche'
        ]
    ],
    'MA' => [
        'name' => 'Marocco',
        'fullName' => 'Regno del Marocco',
        'demonyms' => [
            'Marocchini',
            'Marrocchini'
        ],
        'keywords' => [
            'marocchino',
            'marocchina',
            'marocchine',
            'marrocchino',
            'marrocchina',
            'marrocchine'
        ]
    ],
    'MC' => [
        'name' => 'Monaco',
        'fullName' => 'Principato di Monaco',
        'demonyms' => [
            'Monegaschi'
        ],
        'keywords' => [
            'monegasco',
            'monegasca',
            'monegasche'
        ]
    ],
    'MD' => [
        'name' => 'Moldavia',
        'fullName' => 'Repubblica di Moldavia',
        'demonyms' => [
            'Moldavi'
        ],
        'keywords' => [
            'moldavo',
            'moldava',
            'moldave'
        ]
    ],
    'ME' => [
        'name' => 'Montenegro',
        'fullName' => 'Montenegro',
        'demonyms' => [
            'Montenegrini'
        ],
        'keywords' => [
            'montenegrino',
            'montenegrina',
            'montenegrine',
            'repubblica',
            'del',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'MF' => [
        'name' => 'Saint Martin',
        'fullName' => 'Collettività d\'oltremare di Saint Martin',
        'demonyms' => [
            'Sanmartinesi',
            'Sammartinesi'
        ],
        'keywords' => [
            'com',
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'sanmartinese',
            'sammartinese'
        ]
    ],
    'MG' => [
        'name' => 'Madagascar',
        'fullName' => 'Repubblica del Madagascar',
        'demonyms' => [
            'Malgasci'
        ],
        'keywords' => [
            'malgascio',
            'malgascia',
            'malgascie',
            'malgasce'
        ]
    ],
    'MH' => [
        'name' => 'Isole Marshall',
        'fullName' => 'Repubblica delle Isole Marshall',
        'demonyms' => [
            'Marshallési'
        ],
        'keywords' => [
            'marshallese',
            'marshalliano',
            'marciallese',
            'marciallesi'
        ]
    ],
    'MK' => [
        'name' => 'Macedonia del Nord',
        'fullName' => 'Repubblica della Macedonia del Nord',
        'demonyms' => [
            'Macèdoni',
            'Macèdoni del Nord'
        ],
        'keywords' => [
            'macedone',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'ML' => [
        'name' => 'Mali',
        'fullName' => 'Repubblica del Mali',
        'demonyms' => [
            'Maliani'
        ],
        'keywords' => [
            'maliano',
            'maliana',
            'maliane'
        ]
    ],
    'MM' => [
        'name' => 'Myanmar',
        'fullName' => 'Repubblica dell\'Unione del Myanmar',
        'demonyms' => [
            'Birmani'
        ],
        'keywords' => [
            'birmania',
            'birmano',
            'birmana',
            'birmane',
            'mianmar',
            'mianmmar',
            'myanmmar'
        ]
    ],
    'MN' => [
        'name' => 'Mongolia',
        'fullName' => 'Mongolia',
        'demonyms' => [
            'Mòngoli'
        ],
        'keywords' => [
            'mongolo',
            'mongola',
            'mongole',
            'repubblica',
            'di'
        ]
    ],
    'MO' => [
        'name' => 'Macao',
        'fullName' => 'Regione Amministrativa Speciale di Macao della Repubblica Popolare Cinese',
        'demonyms' => [
            'Macaensi'
        ],
        'keywords' => [
            'macau',
            'macaonese',
            'macaonesi',
            'macaense'
        ]
    ],
    'MP' => [
        'name' => 'Isole Marianne Settentrionali',
        'fullName' => 'Commonwealth delle Isole Marianne Settentrionali',
        'demonyms' => [
            'Mariannènsi'
        ],
        'keywords' => [
            'mariannense',
            'marianense'
        ]
    ],
    'MQ' => [
        'name' => 'Martinica',
        'fullName' => 'Collettività territoriale della Martinica',
        'demonyms' => [
            'Martinicani'
        ],
        'keywords' => [
            'dom',
            'martinicano',
            'martinicana',
            'martinicane',
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane'
        ]
    ],
    'MR' => [
        'name' => 'Mauritania',
        'fullName' => 'Repubblica Islamica della Mauritania',
        'demonyms' => [
            'Mauritaniani',
            'Mauritani'
        ],
        'keywords' => [
            'mauritaniano',
            'mauritaniana',
            'mauritaniane',
            'mauritano',
            'mauritana',
            'mauritane',
            'mauretania',
            'di'
        ]
    ],
    'MS' => [
        'name' => 'Montserrat',
        'fullName' => 'Colonia di Montserrat',
        'demonyms' => [
            'Montserratiani'
        ],
        'keywords' => [
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'montserratiano',
            'montserratiana',
            'montserratiane'
        ]
    ],
    'MT' => [
        'name' => 'Malta',
        'fullName' => 'Repubblica di Malta',
        'demonyms' => [
            'Maltési'
        ],
        'keywords' => [
            'maltese'
        ]
    ],
    'MU' => [
        'name' => 'Mauritius',
        'fullName' => 'Repubblica di Mauritius',
        'demonyms' => [
            'Mauriziani'
        ],
        'keywords' => [
            'mauriziano',
            'mauriziana',
            'mauriziane'
        ]
    ],
    'MV' => [
        'name' => 'Maldive',
        'fullName' => 'Repubblica delle Maldive',
        'demonyms' => [
            'Maldiviani'
        ],
        'keywords' => [
            'maldiviano',
            'maldiviana',
            'maldiviane',
            'maldivano',
            'maldivana',
            'maldivane',
            'maldivani'
        ]
    ],
    'MW' => [
        'name' => 'Malawi',
        'fullName' => 'Repubblica di Malawi',
        'demonyms' => [
            'Malawènsi',
            'Malau̯ènsi',
            'Malawi',
            'Malaui',
            'Malawiani',
            'Malau̯iani'
        ],
        'keywords' => [
            'malawense',
            'malauense',
            'malawiano',
            'malawiana',
            'malawiane',
            'malauiano',
            'malauiana',
            'malauiane',
            'del'
        ]
    ],
    'MX' => [
        'name' => 'Messico',
        'fullName' => 'Stati Uniti Messicani',
        'demonyms' => [
            'Messicani'
        ],
        'keywords' => [
            'messicano',
            'messicana',
            'messicane',
            'del'
        ]
    ],
    'MY' => [
        'name' => 'Malesia',
        'fullName' => 'Malaysia',
        'demonyms' => [
            'Malayṡiani',
            'Malési'
        ],
        'keywords' => [
            'malayiano',
            'malayiana',
            'malayiane',
            'malese',
            'grande',
            'federazione',
            'della',
            'malaisia',
            'malaiiano',
            'malaiiana',
            'malaiiane',
            'malaiiani'
        ]
    ],
    'MZ' => [
        'name' => 'Mozambico',
        'fullName' => 'Repubblica del Mozambico',
        'demonyms' => [
            'Możambicani'
        ],
        'keywords' => [
            'mozambicano',
            'mozambicana',
            'mozambicane'
        ]
    ],
    'NA' => [
        'name' => 'Namibia',
        'fullName' => 'Repubblica della Namibia',
        'demonyms' => [
            'Namibiani'
        ],
        'keywords' => [
            'namibiano',
            'namibiana',
            'namibiane',
            'di'
        ]
    ],
    'NC' => [
        'name' => 'Nuova Caledonia',
        'fullName' => 'Governo della Nuova Caledonia',
        'demonyms' => [
            'Neocaledoni',
            'Neocaledoniani'
        ],
        'keywords' => [
            'isola',
            'com',
            'neocaledone',
            'neocaledoniano',
            'neocaledoniana',
            'neocaledoniane'
        ]
    ],
    'NE' => [
        'name' => 'Niger',
        'fullName' => 'Repubblica del Niger',
        'demonyms' => [
            'Nigerini'
        ],
        'keywords' => [
            'nigerino',
            'nigerina',
            'nigerine'
        ]
    ],
    'NF' => [
        'name' => 'Isola Norfolk',
        'fullName' => 'Territorio dell\'isola Norfolk',
        'demonyms' => [
            'Norfolcani',
            'Norfolkiani'
        ],
        'keywords' => [
            'norfolcano',
            'norfolcana',
            'norfolcane',
            'norfolkiano',
            'norfolkiana',
            'norfolkiane'
        ]
    ],
    'NG' => [
        'name' => 'Nigeria',
        'fullName' => 'Repubblica Federale della Nigeria',
        'demonyms' => [
            'Nigeriani'
        ],
        'keywords' => [
            'nigeriano',
            'nigeriana',
            'nigeriane'
        ]
    ],
    'NI' => [
        'name' => 'Nicaragua',
        'fullName' => 'Repubblica del Nicaragua',
        'demonyms' => [
            'Nicaraguènsi',
            'Nicaraguési',
            'Nicaraguégni'
        ],
        'keywords' => [
            'nicaraguense',
            'nicaraguese',
            'nicaraguegno',
            'nicaraguegna',
            'nicaraguegne'
        ]
    ],
    'NL' => [
        'name' => 'Paesi Bassi',
        'fullName' => 'Regno dei Paesi Bassi',
        'demonyms' => [
            'Olandési',
            'Neerlandési',
            'Nederlandési'
        ],
        'keywords' => [
            'olanda',
            'olandese',
            'neerlandese',
            'nederlandese'
        ]
    ],
    'NO' => [
        'name' => 'Norvegia',
        'fullName' => 'Regno di Norvegia',
        'demonyms' => [
            'Norvegési'
        ],
        'keywords' => [
            'norvegese'
        ]
    ],
    'NP' => [
        'name' => 'Nepal',
        'fullName' => 'Repubblica Federale Democratica del Nepal',
        'demonyms' => [
            'Nepalési'
        ],
        'keywords' => [
            'nepalese',
            'nepaliano',
            'nepaliana',
            'nepaliani',
            'nepaliane'
        ]
    ],
    'NR' => [
        'name' => 'Nauru',
        'fullName' => 'Repubblica di Nauru',
        'demonyms' => [
            'Nauruani'
        ],
        'keywords' => [
            'nauruano',
            'nauruana',
            'nauruane',
            'naruano',
            'naruana',
            'naruani',
            'naruane',
            'nauruese',
            'nauruesi',
            'naruese',
            'naruesi'
        ]
    ],
    'NU' => [
        'name' => 'Niue',
        'fullName' => 'Niue',
        'demonyms' => [
            'Niueani'
        ],
        'keywords' => [
            'niueano',
            'niueana',
            'niueane',
            'nueano',
            'nueana',
            'nueani',
            'nueane',
            'nuese',
            'nuesi'
        ]
    ],
    'NZ' => [
        'name' => 'Nuova Zelanda',
        'fullName' => 'Nuova Zelanda',
        'demonyms' => [
            'Neożelandési'
        ],
        'keywords' => [
            'kiwi',
            'neozelandese'
        ]
    ],
    'OM' => [
        'name' => 'Oman',
        'fullName' => 'Sultanato dell\'Oman',
        'demonyms' => [
            'Omaniti'
        ],
        'keywords' => [
            'omanita',
            'sultanto',
            'di',
            'omanese',
            'omanesi'
        ]
    ],
    'PA' => [
        'name' => 'Panama',
        'fullName' => 'Repubblica di Panama',
        'demonyms' => [
            'Panamènsi'
        ],
        'keywords' => [
            'panamense',
            'panamese',
            'panamesi'
        ]
    ],
    'PE' => [
        'name' => 'Perù',
        'fullName' => 'Repubblica del Perù',
        'demonyms' => [
            'Peruviani'
        ],
        'keywords' => [
            'peruviano',
            'peruviana',
            'peruviane',
            'andino',
            'andina',
            'andine',
            'andini'
        ]
    ],
    'PF' => [
        'name' => 'Polinesia Francese',
        'fullName' => 'Collettività d\'oltremare della Polinesia Francese',
        'demonyms' => [
            'Polineṡiani'
        ],
        'keywords' => [
            'com',
            'polineiano',
            'polineiana',
            'polineiane'
        ]
    ],
    'PG' => [
        'name' => 'Papua Nuova Guinea',
        'fullName' => 'Stato Indipendente della Papua Nuova Guinea',
        'demonyms' => [
            'Papüani'
        ],
        'keywords' => [
            'papuano',
            'papuana',
            'papuane'
        ]
    ],
    'PH' => [
        'name' => 'Filippine',
        'fullName' => 'Repubblica delle Filippine',
        'demonyms' => [
            'Filippini'
        ],
        'keywords' => [
            'filippino',
            'filippina'
        ]
    ],
    'PK' => [
        'name' => 'Pakistan',
        'fullName' => 'Repubblica Islamica del Pakistan',
        'demonyms' => [
            'Pachistani'
        ],
        'keywords' => [
            'pachistano',
            'pachistana',
            'pachistane',
            'pachistan',
            'pakistano',
            'pakistana',
            'pakistane',
            'pakistani'
        ]
    ],
    'PL' => [
        'name' => 'Polonia',
        'fullName' => 'Repubblica di Polonia',
        'demonyms' => [
            'Polacchi',
            'Pollacchi'
        ],
        'keywords' => [
            'polacco',
            'polacca',
            'polacche',
            'pollacco',
            'pollacca',
            'pollacche'
        ]
    ],
    'PM' => [
        'name' => 'Saint Pierre e Miquelon',
        'fullName' => 'Collettività d\'oltremare di Saint-Pierre and Miquelon',
        'demonyms' => [
            'Miqueloniani',
            'Miquelonesi',
            'Sanpierresi'
        ],
        'keywords' => [
            'com',
            'miqueloniano',
            'miqueloniana',
            'miqueloniane',
            'miquelonese',
            'sanpierrese'
        ]
    ],
    'PN' => [
        'name' => 'Pitcairn',
        'fullName' => 'Isole Pitcairn, Henderson, Ducie e Oeno',
        'demonyms' => [
            'Pitcairnesi'
        ],
        'keywords' => [
            'pitcairnese'
        ]
    ],
    'PR' => [
        'name' => 'Portorico',
        'fullName' => 'Stato libero associato di Porto Rico',
        'demonyms' => [
            'Portoricani'
        ],
        'keywords' => [
            'portoricco',
            'portoricano',
            'portoricana',
            'portoricane',
            'caraibi',
            'isole',
            'vergini',
            'grandi',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'portoriccano',
            'portoriccana',
            'portoriccane',
            'portoriccani',
            'portorichese',
            'portorichesi',
            'portoricchese',
            'portoricchesi'
        ]
    ],
    'PS' => [
        'name' => 'Palestina',
        'fullName' => 'Stato di Palestina',
        'demonyms' => [
            'Palestinési'
        ],
        'keywords' => [
            'palestinese',
            'palestiniano',
            'palestiniana',
            'palestiniani',
            'palestiniane'
        ]
    ],
    'PT' => [
        'name' => 'Portogallo',
        'fullName' => 'Repubblica Portoghese',
        'demonyms' => [
            'Portoghési',
            'Lusitani'
        ],
        'keywords' => [
            'portoghese',
            'lusitano',
            'lusitana',
            'lusitane'
        ]
    ],
    'PW' => [
        'name' => 'Palau',
        'fullName' => 'Repubblica di Palau',
        'demonyms' => [
            'Palaulani'
        ],
        'keywords' => [
            'palaulano',
            'palaulana',
            'palaulane'
        ]
    ],
    'PY' => [
        'name' => 'Paraguay',
        'fullName' => 'Repubblica del Paraguay',
        'demonyms' => [
            'Paraguaiani',
            'Paraguayani'
        ],
        'keywords' => [
            'paraguaiano',
            'paraguaiana',
            'paraguaiane',
            'paraguayano',
            'paraguayana',
            'paraguayane',
            'paraguagio',
            'paraguagia',
            'paraguagi',
            'paraguagie'
        ]
    ],
    'QA' => [
        'name' => 'Qatar',
        'fullName' => 'Stato del Qatar',
        'demonyms' => [
            'Qatariani'
        ],
        'keywords' => [
            'qatariano',
            'qatariana',
            'qatariane',
            'qatariota',
            'qatarioti',
            'qatarini',
            'qatarina',
            'qatarine',
            'qatarino',
            'katariota',
            'katarioti',
            'katarini',
            'katarina',
            'katarine',
            'katarino',
            'katariano',
            'katariana',
            'katariane',
            'katariani',
            'catariota',
            'catarioti',
            'catarini',
            'catarina',
            'catarine',
            'catarino',
            'catariano',
            'catariana',
            'catariane',
            'catariani'
        ]
    ],
    'RE' => [
        'name' => 'La Riunione',
        'fullName' => 'Dipartimento della Réunion',
        'demonyms' => [
            'Reunionési'
        ],
        'keywords' => [
            'dom',
            'reunionese'
        ]
    ],
    'RO' => [
        'name' => 'Romania',
        'fullName' => 'Romania',
        'demonyms' => [
            'Romèni',
            'Rumèni'
        ],
        'keywords' => [
            'romeno',
            'romena',
            'romene',
            'rumeno',
            'rumena',
            'rumene'
        ]
    ],
    'RS' => [
        'name' => 'Serbia',
        'fullName' => 'Repubblica di Serbia',
        'demonyms' => [
            'Sèrbi'
        ],
        'keywords' => [
            'serbo',
            'serba',
            'serbe',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'RU' => [
        'name' => 'Russia',
        'fullName' => 'Federazione Russa',
        'demonyms' => [
            'Russi'
        ],
        'keywords' => [
            'russo',
            'russa',
            'russe'
        ]
    ],
    'RW' => [
        'name' => 'Ruanda',
        'fullName' => 'Repubblica del Ruanda',
        'demonyms' => [
            'Ruandési'
        ],
        'keywords' => [
            'ruandese'
        ]
    ],
    'SA' => [
        'name' => 'Arabia Saudita',
        'fullName' => 'Regno dell\'Arabia Saudita',
        'demonyms' => [
            'Sauditi'
        ],
        'keywords' => [
            'saudiano',
            'saudiana',
            'saudiani',
            'saudiane'
        ]
    ],
    'SB' => [
        'name' => 'Isole Salomone',
        'fullName' => 'Isole Salomone',
        'demonyms' => [
            'Salomonesi'
        ],
        'keywords' => [
            'salomonese'
        ]
    ],
    'SC' => [
        'name' => 'Seychelles',
        'fullName' => 'Repubblica delle Seychelles',
        'demonyms' => [
            'Seychellesi',
            'Seicellesi'
        ],
        'keywords' => [
            'seychellese',
            'seicellese'
        ]
    ],
    'SD' => [
        'name' => 'Sudan',
        'fullName' => 'Repubblica del Sudan',
        'demonyms' => [
            'Sudanési'
        ],
        'keywords' => [
            'sudanese'
        ]
    ],
    'SE' => [
        'name' => 'Svezia',
        'fullName' => 'Regno di Svezia',
        'demonyms' => [
            'Svedési',
            'Svezzési'
        ],
        'keywords' => [
            'svedese',
            'svezzese'
        ]
    ],
    'SG' => [
        'name' => 'Singapore',
        'fullName' => 'Repubblica di Singapore',
        'demonyms' => [
            'Singaporiani'
        ],
        'keywords' => [
            'singaporiano',
            'singaporiana',
            'singaporiane'
        ]
    ],
    'SH' => [
        'name' => 'Sant\'Elena',
        'fullName' => 'Isole di Sant\'Elena, Ascensione e Tristan da Cunha',
        'demonyms' => [
            'Tristaniani',
            'Ascensionesi',
            'Santeleniani'
        ],
        'keywords' => [
            'tristaniano',
            'tristaniana',
            'tristaniane',
            'ascensionese',
            'santeleniano',
            'santeleniana',
            'santeleniane'
        ]
    ],
    'SI' => [
        'name' => 'Slovenia',
        'fullName' => 'Repubblica di Slovenia',
        'demonyms' => [
            'Slovèni'
        ],
        'keywords' => [
            'sloveno',
            'slovena',
            'slovene',
            'balcani',
            'balcanico',
            'balcanica',
            'balcanici',
            'balcaniche'
        ]
    ],
    'SJ' => [
        'name' => 'Svalbard e Jan Mayen',
        'fullName' => 'Isole Svalbard e Jan Mayen',
        'demonyms' => [
            'Svalbardesi'
        ],
        'keywords' => [
            'svalbardese'
        ]
    ],
    'SK' => [
        'name' => 'Slovacchia',
        'fullName' => 'Repubblica Slovacca',
        'demonyms' => [
            'Slovàcchi'
        ],
        'keywords' => [
            'slovacco',
            'slovacca',
            'slovacche'
        ]
    ],
    'SL' => [
        'name' => 'Sierra Leone',
        'fullName' => 'Repubblica della Sierra Leone',
        'demonyms' => [
            'Sierraleonési'
        ],
        'keywords' => [
            'sierraleonese'
        ]
    ],
    'SM' => [
        'name' => 'San Marino',
        'fullName' => 'Repubblica di San Marino',
        'demonyms' => [
            'Sammarinési',
            'Sanmarinési'
        ],
        'keywords' => [
            'serenissima',
            'repubblica',
            'di',
            'sammarinese',
            'sanmarinese'
        ]
    ],
    'SN' => [
        'name' => 'Senegal',
        'fullName' => 'Repubblica del Senegal',
        'demonyms' => [
            'Senegalési'
        ],
        'keywords' => [
            'senegalese'
        ]
    ],
    'SO' => [
        'name' => 'Somalia',
        'fullName' => 'Repubblica Federale di Somalia',
        'demonyms' => [
            'Sòmali',
            'Somàli'
        ],
        'keywords' => [
            'somalo',
            'somala',
            'somale'
        ]
    ],
    'SR' => [
        'name' => 'Suriname',
        'fullName' => 'Repubblica del Suriname',
        'demonyms' => [
            'Surinamensi'
        ],
        'keywords' => [
            'surinamense',
            'surinamese',
            'surinamesi'
        ]
    ],
    'SS' => [
        'name' => 'Sud Sudan',
        'fullName' => 'Repubblica del Sudan del Sud',
        'demonyms' => [
            'Sudanési del sud',
            'Sudsudanési'
        ],
        'keywords' => [
            'sudanese',
            'sudsudanese'
        ]
    ],
    'ST' => [
        'name' => 'São Tomé e Príncipe',
        'fullName' => 'Repubblica Democratica di São Tomé e Príncipe',
        'demonyms' => [
            'Saotomensi'
        ],
        'keywords' => [
            'santomense',
            'santomensi',
            'saotomense',
            'saotomese',
            'saotomesi'
        ]
    ],
    'SV' => [
        'name' => 'El Salvador',
        'fullName' => 'Repubblica di El Salvador',
        'demonyms' => [
            'Salvadorégni'
        ],
        'keywords' => [
            'salvadoregno',
            'salvadoregna',
            'salvadoregne',
            'salvadoriano',
            'salvadoriana',
            'salvadoriani',
            'salvadoriane'
        ]
    ],
    'SX' => [
        'name' => 'Sint Maarten',
        'fullName' => 'Sint Maarten',
        'demonyms' => [
            'Sanmartinesi',
            'Sammartinesi'
        ],
        'keywords' => [
            'sss',
            'caraibi',
            'isole',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'olandesi',
            'sanmartinese',
            'sammartinese'
        ]
    ],
    'SY' => [
        'name' => 'Siria',
        'fullName' => 'Repubblica Araba di Siria',
        'demonyms' => [
            'Siriani'
        ],
        'keywords' => [
            'siriano',
            'siriana',
            'siriane',
            'siriaco',
            'siriaca',
            'siriache',
            'siriaci'
        ]
    ],
    'SZ' => [
        'name' => 'eSwatini',
        'fullName' => 'Regno di eSwatini',
        'demonyms' => [
            'Swati',
            'Swazi'
        ],
        'keywords' => [
            'swaziland',
            'swato',
            'swata',
            'swate',
            'swazo',
            'swaza',
            'swaze'
        ]
    ],
    'TC' => [
        'name' => 'Isole Turks e Caicos',
        'fullName' => 'Isole di Turks and Caicos',
        'demonyms' => [
            'Turks',
            'Caicosiani'
        ],
        'keywords' => [
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'caicosiano',
            'caicosiana',
            'caicosiane'
        ]
    ],
    'TD' => [
        'name' => 'Ciad',
        'fullName' => 'Repubblica del Ciad',
        'demonyms' => [
            'Ciadiani'
        ],
        'keywords' => [
            'ciadiano',
            'ciadiana',
            'ciadiane'
        ]
    ],
    'TF' => [
        'name' => 'Terre Australi e Antartiche Francesi',
        'fullName' => 'Territorio delle Terre Australi e Antartiche Francesi',
        'demonyms' => [],
        'keywords' => [
            'taaf',
            'adelien'
        ]
    ],
    'TG' => [
        'name' => 'Togo',
        'fullName' => 'Repubblica togolese',
        'demonyms' => [
            'Togolési'
        ],
        'keywords' => [
            'togolese'
        ]
    ],
    'TH' => [
        'name' => 'Tailandia',
        'fullName' => 'Regno di Thailandia',
        'demonyms' => [
            'Thailandési',
            'Tailandési'
        ],
        'keywords' => [
            'thailandese',
            'tailandese'
        ]
    ],
    'TJ' => [
        'name' => 'Tagikistan',
        'fullName' => 'Repubblica del Tagikistan',
        'demonyms' => [
            'Tagiki',
            'Tagichi',
            'Tagicchi'
        ],
        'keywords' => [
            'tagiko',
            'tagika',
            'tagike',
            'tagico',
            'tagica',
            'tagiche',
            'tagicco',
            'tagicca',
            'tagicche'
        ]
    ],
    'TK' => [
        'name' => 'Tokelau',
        'fullName' => 'Isole Tokelau',
        'demonyms' => [
            'Tokelauani'
        ],
        'keywords' => [
            'isole',
            'dellunione',
            'tokelauano',
            'tokelauana',
            'tokelauane'
        ]
    ],
    'TL' => [
        'name' => 'Timor Est',
        'fullName' => 'Repubblica Democratica di Timor Est',
        'demonyms' => [
            'Timorési'
        ],
        'keywords' => [
            'timorese'
        ]
    ],
    'TM' => [
        'name' => 'Turkmenistan',
        'fullName' => 'Repubblica del Turkmenistan',
        'demonyms' => [
            'Turkmèni'
        ],
        'keywords' => [
            'turkmeno',
            'turkmena',
            'turkmene',
            'turcmeno',
            'turcmena',
            'turcmene',
            'turcmeni'
        ]
    ],
    'TN' => [
        'name' => 'Tunisia',
        'fullName' => 'Repubblica di Tunisia',
        'demonyms' => [
            'Tuniṡini'
        ],
        'keywords' => [
            'tuniino',
            'tuniina',
            'tuniine'
        ]
    ],
    'TO' => [
        'name' => 'Tonga',
        'fullName' => 'Regno di Tonga',
        'demonyms' => [
            'Tongani'
        ],
        'keywords' => [
            'tongano',
            'tongana',
            'tongane'
        ]
    ],
    'TR' => [
        'name' => 'Turchia',
        'fullName' => 'Repubblica di Turchia',
        'demonyms' => [
            'Turchi'
        ],
        'keywords' => [
            'turco',
            'turca',
            'turche'
        ]
    ],
    'TT' => [
        'name' => 'Trinidad e Tobago',
        'fullName' => 'Repubblica di Trinidad e Tobago',
        'demonyms' => [
            'Trinidadiani',
            'Tobagani'
        ],
        'keywords' => [
            'trinidadiano',
            'trinidadiana',
            'trinidadiane',
            'tobagano',
            'tobagana',
            'tobagane'
        ]
    ],
    'TV' => [
        'name' => 'Tuvalu',
        'fullName' => 'Tuvalu',
        'demonyms' => [
            'Tuvalüani'
        ],
        'keywords' => [
            'tuvaluano',
            'tuvaluana',
            'tuvaluane'
        ]
    ],
    'TW' => [
        'name' => 'Taiwan',
        'fullName' => 'Repubblica di Cina',
        'demonyms' => [
            'Taiwanési'
        ],
        'keywords' => [
            'formosa',
            'taiwanese',
            'cinese',
            'cinesi'
        ]
    ],
    'TZ' => [
        'name' => 'Tanzania',
        'fullName' => 'Repubblica Unita di Tanzania',
        'demonyms' => [
            'Tanżaniani'
        ],
        'keywords' => [
            'tanzaniano',
            'tanzaniana',
            'tanzaniane'
        ]
    ],
    'UA' => [
        'name' => 'Ucraina',
        'fullName' => 'Ucraina',
        'demonyms' => [
            'Ucràini'
        ],
        'keywords' => [
            'piccola',
            'russia',
            'ucraino',
            'ucraine',
            'ukraina',
            'ukraino'
        ]
    ],
    'UG' => [
        'name' => 'Uganda',
        'fullName' => 'Repubblica dell\'Uganda',
        'demonyms' => [
            'Ugandési'
        ],
        'keywords' => [
            'ugandese'
        ]
    ],
    'UM' => [
        'name' => 'Isole minori esterne degli Stati Uniti',
        'fullName' => 'Isole minori esterne degli Stati Uniti',
        'demonyms' => [
            'Statunitènsi'
        ],
        'keywords' => [
            'usmoi',
            'statunitense',
            'isolano',
            'isolana',
            'isolani',
            'isolane',
            'isola',
            'di',
            'wake',
            'atollo',
            'johnston',
            'midway',
            'kingman',
            'reef',
            'palmyra',
            'jarvis',
            'baker',
            'howland',
            'navassa',
            'caraibi',
            'pacifico'
        ]
    ],
    'US' => [
        'name' => 'Stati Uniti',
        'fullName' => 'Stati Uniti d\'America',
        'demonyms' => [
            'Statunitènsi',
            'Americani',
            'Nordamericani'
        ],
        'keywords' => [
            'usa',
            'us',
            'america',
            'statunitense',
            'americano',
            'americana',
            'americane',
            'nordamericano',
            'nordamericana',
            'nordamericane'
        ]
    ],
    'UY' => [
        'name' => 'Uruguay',
        'fullName' => 'Repubblica Orientale dell\'Uruguay',
        'demonyms' => [
            'Uruguaiani',
            'Uruguayani'
        ],
        'keywords' => [
            'uruguaiano',
            'uruguaiana',
            'uruguaiane',
            'uruguayano',
            'uruguayana',
            'uruguayane',
            'uruguagio',
            'uruguagia',
            'uruguagi',
            'uruguagie'
        ]
    ],
    'UZ' => [
        'name' => 'Uzbekistan',
        'fullName' => 'Repubblica dell\'Uzbekistan',
        'demonyms' => [
            'Użbèki',
            'Usbèki',
            'Usbèchi',
            'Użbèchi',
            'Usbècchi'
        ],
        'keywords' => [
            'uzbeko',
            'uzbeka',
            'uzbeke',
            'usbeko',
            'usbeka',
            'usbeke',
            'usbeco',
            'usbeca',
            'usbeche',
            'uzbeco',
            'uzbeca',
            'uzbeche',
            'usbecco',
            'usbecca',
            'usbecche'
        ]
    ],
    'VA' => [
        'name' => 'Città del Vaticano',
        'fullName' => 'Vatican City State',
        'demonyms' => [
            'Vaticani'
        ],
        'keywords' => [
            'vaticana',
            'vaticane',
            'pontificio',
            'pontificia',
            'pontifici',
            'pontificie',
            'stato',
            'della',
            'santa',
            'sede',
            'apostolica'
        ]
    ],
    'VC' => [
        'name' => 'Saint Vincent e Grenadine',
        'fullName' => 'Saint Vincent e Grenadine',
        'demonyms' => [
            'Sanvincentini'
        ],
        'keywords' => [
            'caraibi',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'sanvincentino',
            'sanvincentina',
            'sanvincentine'
        ]
    ],
    'VE' => [
        'name' => 'Venezuela',
        'fullName' => 'Repubblica Bolivariana del Venezuela',
        'demonyms' => [
            'Venezuelani',
            'Veneżuelani',
            'Venezolani',
            'Veneżolani'
        ],
        'keywords' => [
            'venezuelano',
            'venezuelana',
            'venezuelane',
            'venezolano',
            'venezolana',
            'venezolane'
        ]
    ],
    'VG' => [
        'name' => 'Isole Vergini Britanniche',
        'fullName' => 'Isole Vergini Britanniche',
        'demonyms' => [
            'Verginiani'
        ],
        'keywords' => [
            'caraibi',
            'anglo',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'verginiano',
            'verginiana',
            'verginiane'
        ]
    ],
    'VI' => [
        'name' => 'Isole Vergini Americane',
        'fullName' => 'Isole Vergini degli Stati Uniti',
        'demonyms' => [
            'Verginiani'
        ],
        'keywords' => [
            'caraibi',
            'americo',
            'piccole',
            'antille',
            'caraibico',
            'caraibica',
            'caraibici',
            'caraibiche',
            'antillano',
            'antillana',
            'antillani',
            'antillane',
            'verginiano',
            'verginiana',
            'verginiane'
        ]
    ],
    'VN' => [
        'name' => 'Vietnam',
        'fullName' => 'Repubblica Socialista del Vietnam',
        'demonyms' => [
            'Vietnamiti'
        ],
        'keywords' => [
            'vietnamita',
            'viet',
            'nam',
            'vietnamite'
        ]
    ],
    'VU' => [
        'name' => 'Vanuatu',
        'fullName' => 'Repubblica di Vanuatu',
        'demonyms' => [
            'Vanuatiani'
        ],
        'keywords' => [
            'vanuatuane',
            'vanuatuano',
            'vanuatuana',
            'vanuatiano',
            'vanuatiana',
            'vanuatiane'
        ]
    ],
    'WF' => [
        'name' => 'Wallis e Futuna',
        'fullName' => 'Collettività d\'oltremare delle isole Wallis e Futuna',
        'demonyms' => [
            'Wallisiani',
            'Futuniani',
            'Uveani'
        ],
        'keywords' => [
            'alofi',
            'com',
            'futunese',
            'futunesi',
            'wallisiano',
            'wallisiana',
            'wallisiane',
            'futuniano',
            'futuniana',
            'futuniane',
            'uveano',
            'uveana',
            'uveane'
        ]
    ],
    'WS' => [
        'name' => 'Samoa',
        'fullName' => 'Stato indipendente di Samoa',
        'demonyms' => [
            'Samoani'
        ],
        'keywords' => [
            'samoano',
            'samoana',
            'samoane'
        ]
    ],
    'XK' => [
        'name' => 'Kosovo',
        'fullName' => 'Repubblica del Kosovo',
        'demonyms' => [
            'Kosovari',
            'Kossovari',
            'Cossovari'
        ],
        'keywords' => [
            'kossovo',
            'cossovo',
            'cosovo'
        ]
    ],
    'YE' => [
        'name' => 'Yemen',
        'fullName' => 'Repubblica dello Yemen',
        'demonyms' => [
            'Yemeniti'
        ],
        'keywords' => [
            'yemenita',
            'iemenita',
            'iemeniti'
        ]
    ],
    'YT' => [
        'name' => 'Mayotte',
        'fullName' => 'Collettività dipartimentale di Mayotte',
        'demonyms' => [
            'Maoresi'
        ],
        'keywords' => [
            'dom',
            'maorese',
            'comoriano',
            'comoriana',
            'comoriani',
            'comoriane',
            'mahorais',
            'maore',
            'mahoriano',
            'mahoriana',
            'mahoriane',
            'mahoriani'
        ]
    ],
    'ZA' => [
        'name' => 'Sud Africa',
        'fullName' => 'Repubblica del Sudafrica',
        'demonyms' => [
            'Sud-Africani',
            'Sudafricani'
        ],
        'keywords' => [
            'sudafricano',
            'sudafricana',
            'sudafricane'
        ]
    ],
    'ZM' => [
        'name' => 'Zambia',
        'fullName' => 'Repubblica dello Zambia',
        'demonyms' => [
            'Zambiano'
        ],
        'keywords' => [
            'zambiana',
            'zambiani',
            'zambiane',
            'di'
        ]
    ],
    'ZW' => [
        'name' => 'Zimbabwe',
        'fullName' => 'Repubblica dello Zimbabwe',
        'demonyms' => [
            'Zimbabwesi'
        ],
        'keywords' => [
            'zimbabwese'
        ]
    ]
];
