<?php

/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

return [
    'AED' => [
        'name' => 'Dirham degli Emirati Arabi Uniti'
    ],
    'AFN' => [
        'name' => 'Afghani'
    ],
    'ALL' => [
        'name' => 'Lek'
    ],
    'AMD' => [
        'name' => 'Dram Armeno'
    ],
    'ANG' => [
        'name' => 'Fiorino delle Antille Olandesi'
    ],
    'AOA' => [
        'name' => 'Kwanza'
    ],
    'ARS' => [
        'name' => 'Peso Argentino'
    ],
    'AUD' => [
        'name' => 'Dollaro Australiano'
    ],
    'AWG' => [
        'name' => 'Fiorino di Aruba'
    ],
    'AZN' => [
        'name' => 'Manat Azero'
    ],
    'BAM' => [
        'name' => 'Marco Convertibile'
    ],
    'BBD' => [
        'name' => 'Dollaro di Barbados'
    ],
    'BDT' => [
        'name' => 'Taka'
    ],
    'BGN' => [
        'name' => 'Lev Bulgaro'
    ],
    'BHD' => [
        'name' => 'Dinaro del Bahrain'
    ],
    'BIF' => [
        'name' => 'Franco del Burundi'
    ],
    'BMD' => [
        'name' => 'Dollaro delle Bermuda'
    ],
    'BND' => [
        'name' => 'Dollaro del Brunei'
    ],
    'BOB' => [
        'name' => 'Boliviano'
    ],
    'BOV' => [
        'name' => 'Mvdol'
    ],
    'BRL' => [
        'name' => 'Real Brasiliano'
    ],
    'BSD' => [
        'name' => 'Dollaro delle Bahamas'
    ],
    'BTN' => [
        'name' => 'Ngultrum'
    ],
    'BWP' => [
        'name' => 'Pula'
    ],
    'BYN' => [
        'name' => 'Rublo Bielorusso'
    ],
    'BZD' => [
        'name' => 'Dollaro del Belize'
    ],
    'CAD' => [
        'name' => 'Dollaro Canadese'
    ],
    'CDF' => [
        'name' => 'Franco Congolese'
    ],
    'CHE' => [
        'name' => 'Euro WIR'
    ],
    'CHF' => [
        'name' => 'Franco Svizzero'
    ],
    'CHW' => [
        'name' => 'Franco WIR'
    ],
    'CLF' => [
        'name' => 'Unidad de Fomento'
    ],
    'CLP' => [
        'name' => 'Peso Cileno'
    ],
    'CNY' => [
        'name' => 'Renminbi Cinese'
    ],
    'COP' => [
        'name' => 'Peso Colombiano'
    ],
    'COU' => [
        'name' => 'Unidad de Valor Real'
    ],
    'CRC' => [
        'name' => 'Colón Costaricano'
    ],
    'CUC' => [
        'name' => 'Peso Cubano Convertible'
    ],
    'CUP' => [
        'name' => 'Peso Cubano'
    ],
    'CVE' => [
        'name' => 'Escudo di Capo Verde'
    ],
    'CZK' => [
        'name' => 'Corona Ceca'
    ],
    'DJF' => [
        'name' => 'Franco di Gibuti'
    ],
    'DKK' => [
        'name' => 'Corona Danese'
    ],
    'DOP' => [
        'name' => 'Peso Dominicano'
    ],
    'DZD' => [
        'name' => 'Dinaro Algerino'
    ],
    'EGP' => [
        'name' => 'Sterlina Egiziana'
    ],
    'ERN' => [
        'name' => 'Nakfa'
    ],
    'ETB' => [
        'name' => 'Birr Etiope'
    ],
    'EUR' => [
        'name' => 'Euro'
    ],
    'FJD' => [
        'name' => 'Dollaro delle Figi'
    ],
    'FKP' => [
        'name' => 'Sterlina delle Falkland'
    ],
    'GBP' => [
        'name' => 'Sterlina Britannica'
    ],
    'GEL' => [
        'name' => 'Lari Georgiano'
    ],
    'GHS' => [
        'name' => 'Cedi del Ghana'
    ],
    'GIP' => [
        'name' => 'Sterlina di Gibilterra'
    ],
    'GMD' => [
        'name' => 'Dalasi'
    ],
    'GNF' => [
        'name' => 'Franco della Guinea'
    ],
    'GTQ' => [
        'name' => 'Quetzal'
    ],
    'GYD' => [
        'name' => 'Dollaro della Guyana'
    ],
    'HKD' => [
        'name' => 'Dollaro di Hong Kong'
    ],
    'HNL' => [
        'name' => 'Lempira'
    ],
    'HTG' => [
        'name' => 'Gourde'
    ],
    'HUF' => [
        'name' => 'Fiorino Ungherese'
    ],
    'IDR' => [
        'name' => 'Rupia Indonesiana'
    ],
    'ILS' => [
        'name' => 'Nuovo Sheqel Israeliano'
    ],
    'INR' => [
        'name' => 'Rupia Indiana'
    ],
    'IQD' => [
        'name' => 'Dinaro Iracheno'
    ],
    'IRR' => [
        'name' => 'Rial Iraniano'
    ],
    'ISK' => [
        'name' => 'Corona Islandese'
    ],
    'JMD' => [
        'name' => 'Dollaro Giamaicano'
    ],
    'JOD' => [
        'name' => 'Dinaro Giordano'
    ],
    'JPY' => [
        'name' => 'Yen Giapponese'
    ],
    'KES' => [
        'name' => 'Scellino Keniota'
    ],
    'KGS' => [
        'name' => 'Som Kirghiso'
    ],
    'KHR' => [
        'name' => 'Riel Cambogiano'
    ],
    'KMF' => [
        'name' => 'Franco Comoriano'
    ],
    'KPW' => [
        'name' => 'Won Nordcoreano'
    ],
    'KRW' => [
        'name' => 'Won Sudcoreano'
    ],
    'KWD' => [
        'name' => 'Dinaro Kuwaitiano'
    ],
    'KYD' => [
        'name' => 'Dollaro delle Isole Cayman'
    ],
    'KZT' => [
        'name' => 'Tenge Kazako'
    ],
    'LAK' => [
        'name' => 'Kip del Laos'
    ],
    'LBP' => [
        'name' => 'Sterlina Libanese'
    ],
    'LKR' => [
        'name' => 'Rupia dello Sri Lanka'
    ],
    'LRD' => [
        'name' => 'Dollaro Liberiano'
    ],
    'LSL' => [
        'name' => 'Loti'
    ],
    'LYD' => [
        'name' => 'Dinaro Libico'
    ],
    'MAD' => [
        'name' => 'Dirham Marocchino'
    ],
    'MDL' => [
        'name' => 'Leu Moldavo'
    ],
    'MGA' => [
        'name' => 'Ariary Malgascio'
    ],
    'MKD' => [
        'name' => 'Dinaro Macedone'
    ],
    'MMK' => [
        'name' => 'Kyat Birmano'
    ],
    'MNT' => [
        'name' => 'Tugrik Mongolo'
    ],
    'MOP' => [
        'name' => 'Pataca'
    ],
    'MRU' => [
        'name' => 'Ouguiya'
    ],
    'MUR' => [
        'name' => 'Rupia Mauriziana'
    ],
    'MVR' => [
        'name' => 'Rufiyaa'
    ],
    'MWK' => [
        'name' => 'Kwacha Malawiano'
    ],
    'MXN' => [
        'name' => 'Peso Messicano'
    ],
    'MXV' => [
        'name' => 'Unidad de Inversion (UDI) Messicana'
    ],
    'MYR' => [
        'name' => 'Ringgit Malese'
    ],
    'MZN' => [
        'name' => 'Metical Mozambicano'
    ],
    'NAD' => [
        'name' => 'Dollaro Namibiano'
    ],
    'NGN' => [
        'name' => 'Naira Nigeriana'
    ],
    'NIO' => [
        'name' => 'Cordoba Oro'
    ],
    'NOK' => [
        'name' => 'Corona Norvegese'
    ],
    'NPR' => [
        'name' => 'Rupia Nepalese'
    ],
    'NZD' => [
        'name' => 'Dollaro Neozelandese'
    ],
    'OMR' => [
        'name' => 'Rial Omanita'
    ],
    'PAB' => [
        'name' => 'Balboa'
    ],
    'PEN' => [
        'name' => 'Sol Peruviano'
    ],
    'PGK' => [
        'name' => 'Kina della Papua Nuova Guinea'
    ],
    'PHP' => [
        'name' => 'Peso Filippino'
    ],
    'PKR' => [
        'name' => 'Rupia Pakistana'
    ],
    'PLN' => [
        'name' => 'Zloty Polacco'
    ],
    'PYG' => [
        'name' => 'Guarani'
    ],
    'QAR' => [
        'name' => 'Rial Qatariota'
    ],
    'RON' => [
        'name' => 'Leu Rumeno'
    ],
    'RSD' => [
        'name' => 'Dinaro Serbo'
    ],
    'RUB' => [
        'name' => 'Rublo Russo'
    ],
    'RWF' => [
        'name' => 'Franco Ruandese'
    ],
    'SAR' => [
        'name' => 'Riyal Saudita'
    ],
    'SBD' => [
        'name' => 'Dollaro delle Isole Salomone'
    ],
    'SCR' => [
        'name' => 'Rupia delle Seychelles'
    ],
    'SDG' => [
        'name' => 'Sterlina Sudanese'
    ],
    'SEK' => [
        'name' => 'Corona Svedese'
    ],
    'SGD' => [
        'name' => 'Dollaro di Singapore'
    ],
    'SHP' => [
        'name' => 'Sterlina di Sant\'Elena'
    ],
    'SLE' => [
        'name' => 'Leone'
    ],
    'SLL' => [
        'name' => 'Leone (dismesso)'
    ],
    'SOS' => [
        'name' => 'Scellino Somalo'
    ],
    'SRD' => [
        'name' => 'Dollaro del Suriname'
    ],
    'SSP' => [
        'name' => 'Sterlina Sudsudanese'
    ],
    'STN' => [
        'name' => 'Dobra'
    ],
    'SVC' => [
        'name' => 'Colón Salvadoregno'
    ],
    'SYP' => [
        'name' => 'Sterlina Siriana'
    ],
    'SZL' => [
        'name' => 'Lilangeni'
    ],
    'THB' => [
        'name' => 'Baht Tailandese'
    ],
    'TJS' => [
        'name' => 'Somoni Tagiko'
    ],
    'TMT' => [
        'name' => 'Manat Turkmeno'
    ],
    'TND' => [
        'name' => 'Dinaro Tunisino'
    ],
    'TOP' => [
        'name' => 'Pa\'anga'
    ],
    'TRY' => [
        'name' => 'Lira Turca'
    ],
    'TTD' => [
        'name' => 'Dollaro di Trinidad e Tobago'
    ],
    'TWD' => [
        'name' => 'Nuovo Dollaro di Taiwan'
    ],
    'TZS' => [
        'name' => 'Scellino della Tanzania'
    ],
    'UAH' => [
        'name' => 'Grivnia Ucraina'
    ],
    'UGX' => [
        'name' => 'Scellino Ugandese'
    ],
    'USD' => [
        'name' => 'Dollaro Statunitense'
    ],
    'USN' => [
        'name' => 'Dollaro Statunitense (giorno successivo)'
    ],
    'UYI' => [
        'name' => 'Peso Uruguayo in Unidades Indexadas (UI)'
    ],
    'UYU' => [
        'name' => 'Peso Uruguayo'
    ],
    'UYW' => [
        'name' => 'Unidad Previsional'
    ],
    'UZS' => [
        'name' => 'Sum Uzbeko'
    ],
    'VED' => [
        'name' => 'Bolívar Venezuelano Digitale'
    ],
    'VES' => [
        'name' => 'Bolívar Venezuelano'
    ],
    'VND' => [
        'name' => 'Dong Vietnamita'
    ],
    'VUV' => [
        'name' => 'Vatu'
    ],
    'WST' => [
        'name' => 'Tala'
    ],
    'XAF' => [
        'name' => 'Franco CFA BEAC'
    ],
    'XAG' => [
        'name' => 'Argento'
    ],
    'XAU' => [
        'name' => 'Oro'
    ],
    'XBA' => [
        'name' => 'Unità composita europea dei mercati obbligazionari (EURCO)'
    ],
    'XBB' => [
        'name' => 'Unità monetaria europea dei mercati obbligazionari (EMU-6)'
    ],
    'XBC' => [
        'name' => 'Unità di conto europea 9 (EUA-9)'
    ],
    'XBD' => [
        'name' => 'Unità di conto europea 17 (EUA-17)'
    ],
    'XCD' => [
        'name' => 'Dollaro dei Caraibi Orientali'
    ],
    'XDR' => [
        'name' => 'Diritti Speciali di Prelievo (SDR)'
    ],
    'XOF' => [
        'name' => 'Franco CFA BCEAO'
    ],
    'XPD' => [
        'name' => 'Palladio'
    ],
    'XPF' => [
        'name' => 'Franco CFP'
    ],
    'XPT' => [
        'name' => 'Platino'
    ],
    'XSU' => [
        'name' => 'Sucre'
    ],
    'XTS' => [
        'name' => 'Codici riservati specificamente per scopi di prova'
    ],
    'XUA' => [
        'name' => 'Unità di conto ADB'
    ],
    'XXX' => [
        'name' => 'Codici assegnati per transazioni senza valuta'
    ],
    'YER' => [
        'name' => 'Rial dello Yemen'
    ],
    'ZAR' => [
        'name' => 'Rand Sudafricano'
    ],
    'ZMW' => [
        'name' => 'Kwacha dello Zambia'
    ],
    'ZWL' => [
        'name' => 'Dollaro dello Zimbabwe'
    ]
];
