<?php

/**
 * This file has been automatically generated by the `build` script in the `dev` section.
 * Any modifications you make will be overwritten.
 * To modify the parameters in this file, please follow these steps:
 * - Go to the `dev/origin` section.
 * - Modify the corresponding JSON file.
 * - Run the `build` script again from the root of this project using one of these commands:
 *   - `dev/build`
 *   - `sh dev/build`
 * For further and more detailed information, please read the README.md file in the dev section.
*/

return [
  'CONV-G20' => [
    'name' => 'Gruppo dei Venti (G20)',
  ],
  'CONV-G7' => [
    'name' => 'Gruppo dei Sette (G7)',
  ],
  'CONV-SCHENGEN' => [
    'name' => 'Spazio Schengen',
  ],
  'CONV-UNCAC' => [
    'name' => 'Convenzione delle Nazioni Unite contro la Corruzione (CNUC)',
  ],
  'GEOG-AF' => [
    'name' => 'Africa',
  ],
  'GEOG-AF-NO' => [
    'name' => 'Africa Settentrionale',
  ],
  'GEOG-AF-SS' => [
    'name' => 'Africa Sub-Sahariana',
  ],
  'GEOG-AF-SS-EA' => [
    'name' => 'Africa Orientale',
  ],
  'GEOG-AF-SS-MD' => [
    'name' => 'Africa Centrale',
  ],
  'GEOG-AF-SS-SO' => [
    'name' => 'Africa Meridionale',
  ],
  'GEOG-AF-SS-WE' => [
    'name' => 'Africa Occidentale',
  ],
  'GEOG-AM' => [
    'name' => 'Americhe',
  ],
  'GEOG-AM-LA' => [
    'name' => 'America Latina e Caraibi',
  ],
  'GEOG-AM-LA-CA' => [
    'name' => 'Caraibi',
  ],
  'GEOG-AM-LA-CT' => [
    'name' => 'America Centrale',
  ],
  'GEOG-AM-LA-SO' => [
    'name' => 'America Meridionale',
  ],
  'GEOG-AM-NO' => [
    'name' => 'America Settentrionale',
  ],
  'GEOG-AQ' => [
    'name' => 'Antartide',
  ],
  'GEOG-AS' => [
    'name' => 'Asia',
  ],
  'GEOG-AS-CT' => [
    'name' => 'Asia Centrale',
  ],
  'GEOG-AS-EA' => [
    'name' => 'Asia Orientale',
  ],
  'GEOG-AS-SE' => [
    'name' => 'Asia Sud-Orientale',
  ],
  'GEOG-AS-SO' => [
    'name' => 'Asia Meridionale',
  ],
  'GEOG-AS-WE' => [
    'name' => 'Asia Occidentale',
  ],
  'GEOG-EU' => [
    'name' => 'Europa',
  ],
  'GEOG-EU-EA' => [
    'name' => 'Europa Orientale',
  ],
  'GEOG-EU-NO' => [
    'name' => 'Europa Settentrionale',
  ],
  'GEOG-EU-NO-CH' => [
    'name' => 'Isole del Canale',
  ],
  'GEOG-EU-SO' => [
    'name' => 'Europa Meridionale',
  ],
  'GEOG-EU-WE' => [
    'name' => 'Europa Occidentale',
  ],
  'GEOG-OC' => [
    'name' => 'Oceania',
  ],
  'GEOG-OC-AN' => [
    'name' => 'Australia e Nuova Zelanda',
  ],
  'GEOG-OC-ME' => [
    'name' => 'Melanesia',
  ],
  'GEOG-OC-MI' => [
    'name' => 'Micronesia',
  ],
  'GEOG-OC-PO' => [
    'name' => 'Polinesia',
  ],
  'ORGS-ACTO' => [
    'name' => 'Organizzazione del Trattato di Cooperazione Amazzonica (ACTO)',
  ],
  'ORGS-ASEAN' => [
    'name' => 'Associazione delle Nazioni del Sud-est Asiatico (ASEAN)',
  ],
  'ORGS-AU' => [
    'name' => 'Unione Africana (AU)',
  ],
  'ORGS-BRICS' => [
    'name' => 'BRICS',
  ],
  'ORGS-CIS' => [
    'name' => 'Comunità degli Stati Indipendenti (CSI)',
  ],
  'ORGS-COE' => [
    'name' => 'Consiglio d\'Europa (CoE)',
  ],
  'ORGS-CSTO' => [
    'name' => 'Organizzazione del Trattato di Sicurezza Collettiva (OTSC)',
  ],
  'ORGS-CWNAT' => [
    'name' => 'Commonwealth delle Nazioni',
  ],
  'ORGS-CWRLM' => [
    'name' => 'Reame del Commonwealth',
  ],
  'ORGS-EU' => [
    'name' => 'Unione Europea (UE)',
  ],
  'ORGS-IBRD' => [
    'name' => 'Banca Internazionale per la Ricostruzione e lo Sviluppo (BIRS)',
  ],
  'ORGS-ICC' => [
    'name' => 'Corte Penale Internazionale (CPI)',
  ],
  'ORGS-ICSID' => [
    'name' => 'Centro Internazionale per la Regolamentazione delle Controversie relative agli Investimenti (ICSID)',
  ],
  'ORGS-IDA' => [
    'name' => 'Associazione Internazionale per lo Sviluppo (IDA)',
  ],
  'ORGS-IFC' => [
    'name' => 'Corporazione Finanziaria Internazionale (IFC)',
  ],
  'ORGS-IPOL' => [
    'name' => 'Organizzazione Internazionale di Polizia Criminale (Interpol)',
  ],
  'ORGS-MIGA' => [
    'name' => 'Agenzia Multilaterale di Garanzia degli Investimenti (MIGA)',
  ],
  'ORGS-NATO' => [
    'name' => 'Organizzazione del Trattato dell\'Atlantico del Nord (NATO)',
  ],
  'ORGS-OAS' => [
    'name' => 'Organizzazione degli Stati Americani (OAS)',
  ],
  'ORGS-OECD' => [
    'name' => 'Organizzazione per la Cooperazione e lo Sviluppo Economico (OCSE)',
  ],
  'ORGS-OPEC' => [
    'name' => 'Organizzazione dei Paesi Esportatori di Petrolio (OPEC)',
  ],
  'ORGS-OSCE' => [
    'name' => 'Organizzazione per la Sicurezza e la Cooperazione in Europa (OSCE)',
  ],
  'ORGS-SCO' => [
    'name' => 'Organizzazione di Cooperazione di Shanghai (SCO)',
  ],
  'ORGS-UN' => [
    'name' => 'Nazioni Unite (ONU)',
  ],
  'ORGS-WCO' => [
    'name' => 'Organizzazione Mondiale delle Dogane (OMD)',
  ],
  'ORGS-WTO' => [
    'name' => 'Organizzazione Mondiale del Commercio (OMC)',
  ],
  'ZONE-EZ' => [
    'name' => 'Eurozona (EZ)',
  ],
];
