<?php

/**
 * This file has been automatically generated by the `build` script in the `dev` section.
 * Any modifications you make will be overwritten.
 * To modify the parameters in this file, please follow these steps:
 * - Go to the `dev/origin` section.
 * - Modify the corresponding JSON file.
 * - Run the `build` script again from the root of this project using one of these commands:
 *   - `dev/build`
 *   - `sh dev/build`
 * For further and more detailed information, please read the README.md file in the dev section.
*/

return [
  'settings' => [
    'languages' => [
      'default' => 'en',
      'inPackage' => [
         'en',
         'it',
      ],
    ],
  ],
];
