<?php

/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */

return [
    'settings' => [
        'languages' => [
            'default' => 'en',
            'inPackage' => [
                'en' => 'en_GB',
                'it' => 'it_IT'
            ]
        ]
    ]
];
