<?php
        
/**
 * This file has been automatically generated by the `data-geoCodes` application.
 * Any modifications you make will be overwritten during upgrades.
 * To avoid this, you can save the data directory in another location and launch the app specifying the new directory.
 * If you want to contribute to the development of the data, please follow these steps:
 * - Install Node.js on your system (you can use the instructions at https://nodejs.org/en/download/package-manager).
 * - Clone the repository from GitHub `https://github.com/alibe1971/data-geoCodes`.
 * - Modify the JSON files in the directory.
 * - Run the `node build` script from your terminal.
 * - The built files will be located inside the directory:
 *   - `Data/built/php`
 * - Submit a pull request to publish your changes.
 * - You can also clone the Php application, integrate the built data, and submit two separate pull requests:
 *   - One for the data modifications.
 *   - Another for integrating the modified data into the specific app.
 * For further detailed information, please refer to the documentation.
 */
 
 
return [
    [
        'isoAlpha' => 'AED',
        'isoNumber' => '784',
        'symbol' => 'د.إ',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'AFN',
        'isoNumber' => '971',
        'symbol' => '؋',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ALL',
        'isoNumber' => '008',
        'symbol' => 'Lek',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'AMD',
        'isoNumber' => '051',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ANG',
        'isoNumber' => '532',
        'symbol' => 'ƒ',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'AOA',
        'isoNumber' => '973',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ARS',
        'isoNumber' => '032',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'AUD',
        'isoNumber' => '036',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'AWG',
        'isoNumber' => '533',
        'symbol' => 'ƒ',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'AZN',
        'isoNumber' => '944',
        'symbol' => '₼',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BAM',
        'isoNumber' => '977',
        'symbol' => 'KM',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BBD',
        'isoNumber' => '052',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BDT',
        'isoNumber' => '050',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BGN',
        'isoNumber' => '975',
        'symbol' => 'лв',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BHD',
        'isoNumber' => '048',
        'symbol' => null,
        'decimal' => 3
    ],
    [
        'isoAlpha' => 'BIF',
        'isoNumber' => '108',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'BMD',
        'isoNumber' => '060',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BND',
        'isoNumber' => '096',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BOB',
        'isoNumber' => '068',
        'symbol' => '$b',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BOV',
        'isoNumber' => '984',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BRL',
        'isoNumber' => '986',
        'symbol' => 'R$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BSD',
        'isoNumber' => '044',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BTN',
        'isoNumber' => '064',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BWP',
        'isoNumber' => '072',
        'symbol' => 'P',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BYN',
        'isoNumber' => '933',
        'symbol' => 'Br',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'BZD',
        'isoNumber' => '084',
        'symbol' => 'BZ$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CAD',
        'isoNumber' => '124',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CDF',
        'isoNumber' => '976',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CHE',
        'isoNumber' => '947',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CHF',
        'isoNumber' => '756',
        'symbol' => 'CHF',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CHW',
        'isoNumber' => '948',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CLF',
        'isoNumber' => '990',
        'symbol' => null,
        'decimal' => 4
    ],
    [
        'isoAlpha' => 'CLP',
        'isoNumber' => '152',
        'symbol' => '$',
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'CNY',
        'isoNumber' => '156',
        'symbol' => '¥',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'COP',
        'isoNumber' => '170',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'COU',
        'isoNumber' => '970',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CRC',
        'isoNumber' => '188',
        'symbol' => '₡',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CUC',
        'isoNumber' => '931',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CUP',
        'isoNumber' => '192',
        'symbol' => '₱',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CVE',
        'isoNumber' => '132',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'CZK',
        'isoNumber' => '203',
        'symbol' => 'Kč',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'DJF',
        'isoNumber' => '262',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'DKK',
        'isoNumber' => '208',
        'symbol' => 'kr',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'DOP',
        'isoNumber' => '214',
        'symbol' => 'RD$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'DZD',
        'isoNumber' => '012',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'EGP',
        'isoNumber' => '818',
        'symbol' => '£',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ERN',
        'isoNumber' => '232',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ETB',
        'isoNumber' => '230',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'EUR',
        'isoNumber' => '978',
        'symbol' => '€',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'FJD',
        'isoNumber' => '242',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'FKP',
        'isoNumber' => '238',
        'symbol' => '£',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'GBP',
        'isoNumber' => '826',
        'symbol' => '£',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'GEL',
        'isoNumber' => '981',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'GHS',
        'isoNumber' => '936',
        'symbol' => '¢',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'GIP',
        'isoNumber' => '292',
        'symbol' => '£',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'GMD',
        'isoNumber' => '270',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'GNF',
        'isoNumber' => '324',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'GTQ',
        'isoNumber' => '320',
        'symbol' => 'Q',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'GYD',
        'isoNumber' => '328',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'HKD',
        'isoNumber' => '344',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'HNL',
        'isoNumber' => '340',
        'symbol' => 'L',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'HTG',
        'isoNumber' => '332',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'HUF',
        'isoNumber' => '348',
        'symbol' => 'Ft',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'IDR',
        'isoNumber' => '360',
        'symbol' => 'Rp',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ILS',
        'isoNumber' => '376',
        'symbol' => '₪',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'INR',
        'isoNumber' => '356',
        'symbol' => '₹',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'IQD',
        'isoNumber' => '368',
        'symbol' => null,
        'decimal' => 3
    ],
    [
        'isoAlpha' => 'IRR',
        'isoNumber' => '364',
        'symbol' => '﷼',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ISK',
        'isoNumber' => '352',
        'symbol' => 'kr',
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'JMD',
        'isoNumber' => '388',
        'symbol' => 'J$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'JOD',
        'isoNumber' => '400',
        'symbol' => null,
        'decimal' => 3
    ],
    [
        'isoAlpha' => 'JPY',
        'isoNumber' => '392',
        'symbol' => '¥',
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'KES',
        'isoNumber' => '404',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'KGS',
        'isoNumber' => '417',
        'symbol' => 'лв',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'KHR',
        'isoNumber' => '116',
        'symbol' => '៛',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'KMF',
        'isoNumber' => '174',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'KPW',
        'isoNumber' => '408',
        'symbol' => '₩',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'KRW',
        'isoNumber' => '410',
        'symbol' => '₩',
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'KWD',
        'isoNumber' => '414',
        'symbol' => null,
        'decimal' => 3
    ],
    [
        'isoAlpha' => 'KYD',
        'isoNumber' => '136',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'KZT',
        'isoNumber' => '398',
        'symbol' => 'лв',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'LAK',
        'isoNumber' => '418',
        'symbol' => 'LAK',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'LBP',
        'isoNumber' => '422',
        'symbol' => '£',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'LKR',
        'isoNumber' => '144',
        'symbol' => '₨',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'LRD',
        'isoNumber' => '430',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'LSL',
        'isoNumber' => '426',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'LYD',
        'isoNumber' => '434',
        'symbol' => null,
        'decimal' => 3
    ],
    [
        'isoAlpha' => 'MAD',
        'isoNumber' => '504',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MDL',
        'isoNumber' => '498',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MGA',
        'isoNumber' => '969',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MKD',
        'isoNumber' => '807',
        'symbol' => 'ден',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MMK',
        'isoNumber' => '104',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MNT',
        'isoNumber' => '496',
        'symbol' => '₮',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MOP',
        'isoNumber' => '446',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MRU',
        'isoNumber' => '929',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MUR',
        'isoNumber' => '480',
        'symbol' => '₨',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MVR',
        'isoNumber' => '462',
        'symbol' => 'Rf',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MWK',
        'isoNumber' => '454',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MXN',
        'isoNumber' => '484',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MXV',
        'isoNumber' => '979',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MYR',
        'isoNumber' => '458',
        'symbol' => 'RM',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'MZN',
        'isoNumber' => '943',
        'symbol' => 'MT',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'NAD',
        'isoNumber' => '516',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'NGN',
        'isoNumber' => '566',
        'symbol' => '₦',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'NIO',
        'isoNumber' => '558',
        'symbol' => 'C$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'NOK',
        'isoNumber' => '578',
        'symbol' => 'kr',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'NPR',
        'isoNumber' => '524',
        'symbol' => '₨',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'NZD',
        'isoNumber' => '554',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'OMR',
        'isoNumber' => '512',
        'symbol' => '﷼',
        'decimal' => 3
    ],
    [
        'isoAlpha' => 'PAB',
        'isoNumber' => '590',
        'symbol' => 'B/.',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'PEN',
        'isoNumber' => '604',
        'symbol' => 'S/.',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'PGK',
        'isoNumber' => '598',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'PHP',
        'isoNumber' => '608',
        'symbol' => '₱',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'PKR',
        'isoNumber' => '586',
        'symbol' => '₨',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'PLN',
        'isoNumber' => '985',
        'symbol' => 'zł',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'PYG',
        'isoNumber' => '600',
        'symbol' => '₲',
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'QAR',
        'isoNumber' => '634',
        'symbol' => '﷼',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'RON',
        'isoNumber' => '946',
        'symbol' => 'lei',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'RSD',
        'isoNumber' => '941',
        'symbol' => 'дин.',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'RUB',
        'isoNumber' => '643',
        'symbol' => '₽',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'RWF',
        'isoNumber' => '646',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'SAR',
        'isoNumber' => '682',
        'symbol' => '﷼',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SBD',
        'isoNumber' => '090',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SCR',
        'isoNumber' => '690',
        'symbol' => '₨',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SDG',
        'isoNumber' => '938',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SEK',
        'isoNumber' => '752',
        'symbol' => 'kr',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SGD',
        'isoNumber' => '702',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SHP',
        'isoNumber' => '654',
        'symbol' => '£',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SLE',
        'isoNumber' => '925',
        'symbol' => 'Le',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SLL',
        'isoNumber' => '694',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SOS',
        'isoNumber' => '706',
        'symbol' => 'S',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SRD',
        'isoNumber' => '968',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SSP',
        'isoNumber' => '728',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'STN',
        'isoNumber' => '930',
        'symbol' => 'Db',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SVC',
        'isoNumber' => '222',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SYP',
        'isoNumber' => '760',
        'symbol' => '£',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'SZL',
        'isoNumber' => '748',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'THB',
        'isoNumber' => '764',
        'symbol' => '฿',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'TJS',
        'isoNumber' => '972',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'TMT',
        'isoNumber' => '934',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'TND',
        'isoNumber' => '788',
        'symbol' => null,
        'decimal' => 3
    ],
    [
        'isoAlpha' => 'TOP',
        'isoNumber' => '776',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'TRY',
        'isoNumber' => '949',
        'symbol' => '₺',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'TTD',
        'isoNumber' => '780',
        'symbol' => 'TT$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'TWD',
        'isoNumber' => '901',
        'symbol' => 'NT$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'TZS',
        'isoNumber' => '834',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'UAH',
        'isoNumber' => '980',
        'symbol' => '₴',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'UGX',
        'isoNumber' => '800',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'USD',
        'isoNumber' => '840',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'USN',
        'isoNumber' => '997',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'UYI',
        'isoNumber' => '940',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'UYU',
        'isoNumber' => '858',
        'symbol' => '$U',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'UYW',
        'isoNumber' => '927',
        'symbol' => null,
        'decimal' => 4
    ],
    [
        'isoAlpha' => 'UZS',
        'isoNumber' => '860',
        'symbol' => 'лв',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'VED',
        'isoNumber' => '926',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'VES',
        'isoNumber' => '928',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'VND',
        'isoNumber' => '704',
        'symbol' => '₫',
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'VUV',
        'isoNumber' => '548',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'WST',
        'isoNumber' => '882',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'XAF',
        'isoNumber' => '950',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'XAG',
        'isoNumber' => '961',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XAU',
        'isoNumber' => '959',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XBA',
        'isoNumber' => '955',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XBB',
        'isoNumber' => '956',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XBC',
        'isoNumber' => '957',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XBD',
        'isoNumber' => '958',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XCD',
        'isoNumber' => '951',
        'symbol' => '$',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'XDR',
        'isoNumber' => '960',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XOF',
        'isoNumber' => '952',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'XPD',
        'isoNumber' => '964',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XPF',
        'isoNumber' => '953',
        'symbol' => null,
        'decimal' => 0
    ],
    [
        'isoAlpha' => 'XPT',
        'isoNumber' => '962',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XSU',
        'isoNumber' => '994',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XTS',
        'isoNumber' => '963',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XUA',
        'isoNumber' => '965',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'XXX',
        'isoNumber' => '999',
        'symbol' => null,
        'decimal' => null
    ],
    [
        'isoAlpha' => 'YER',
        'isoNumber' => '886',
        'symbol' => '﷼',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ZAR',
        'isoNumber' => '710',
        'symbol' => 'R',
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ZMW',
        'isoNumber' => '967',
        'symbol' => null,
        'decimal' => 2
    ],
    [
        'isoAlpha' => 'ZWL',
        'isoNumber' => '932',
        'symbol' => null,
        'decimal' => 2
    ]
];